//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastConsig.Core.Web.Credito
{


   public partial class SimuladorProposta
   {

      /// <summary>
      /// Identificacao control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.HtmlControls.HtmlGenericControl Identificacao;

      /// <summary>
      /// ddlPromotora control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomDropDownList ddlPromotora;

      /// <summary>
      /// ddlRedeLojas control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomDropDownList ddlRedeLojas;

      /// <summary>
      /// ddlLojas control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomDropDownList ddlLojas;

      /// <summary>
      /// ddlProduto control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomDropDownList ddlProduto;

      /// <summary>
      /// INSS control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.HtmlControls.HtmlGenericControl INSS;

      /// <summary>
      /// ddlTipoBeneficio control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomDropDownList ddlTipoBeneficio;

      /// <summary>
      /// txtNumeroBeneficio control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomTextBox txtNumeroBeneficio;

      /// <summary>
      /// ddlIndicadorAnafalbetismo control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomDropDownList ddlIndicadorAnafalbetismo;

      /// <summary>
      /// SIAPE control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.HtmlControls.HtmlGenericControl SIAPE;

      /// <summary>
      /// ddlOrgao control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomDropDownList ddlOrgao;

      /// <summary>
      /// CustomTextBox1 control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomTextBox CustomTextBox1;

      /// <summary>
      /// labelInstituidor control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.HtmlControls.HtmlGenericControl labelInstituidor;

      /// <summary>
      /// txtInstituidor control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomTextBox txtInstituidor;

      /// <summary>
      /// DadosCliente control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.HtmlControls.HtmlGenericControl DadosCliente;

      /// <summary>
      /// txtCPF control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomTextBox txtCPF;

      /// <summary>
      /// txtDataNascimento control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomTextBox txtDataNascimento;

      /// <summary>
      /// txtNome control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomTextBox txtNome;

      /// <summary>
      /// txtCelular control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomTextBox txtCelular;

      /// <summary>
      /// txtEmail control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomTextBox txtEmail;

      /// <summary>
      /// ddlTipoComunicacao control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomDropDownList ddlTipoComunicacao;

      /// <summary>
      /// DadosOperacao control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.HtmlControls.HtmlGenericControl DadosOperacao;

      /// <summary>
      /// ddlTabela control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomDropDownList ddlTabela;

      /// <summary>
      /// txtValorSolicitado control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomTextBox txtValorSolicitado;

      /// <summary>
      /// txtPrazo control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomTextBox txtPrazo;

      /// <summary>
      /// txtValorParcela control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomTextBox txtValorParcela;

      /// <summary>
      /// btnSimular control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomLinkButton btnSimular;

      /// <summary>
      /// btnNovaSimulacao control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomLinkButton btnNovaSimulacao;

      /// <summary>
      /// btnEnviarAutorizacao control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomLinkButton btnEnviarAutorizacao;

      /// <summary>
      /// btnSubmeter control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomLinkButton btnSubmeter;

      /// <summary>
      /// btnBuscarContratos control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomLinkButton btnBuscarContratos;
   }
}
