//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace FastConsig.CTC.Model.ACTC202 {
   using FastConsig.CTC.Model.Interfaces;
   using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC202.xsd")]
    [System.Xml.Serialization.XmlRootAttribute("ACTCDOC", Namespace="http://www.cip-bancos.org.br/ARQ/ACTC202.xsd", IsNullable=false)]
    public partial class ACTC202 : IACTC
   {
        
        private BCARQComplexType bCARQField;
        
        private SISARQComplexType sISARQField;
        
        private string eSTARQField;
        
        /// <remarks/>
        public BCARQComplexType BCARQ {
            get {
                return this.bCARQField;
            }
            set {
                this.bCARQField = value;
            }
        }
        
        /// <remarks/>
        public SISARQComplexType SISARQ {
            get {
                return this.sISARQField;
            }
            set {
                this.sISARQField = value;
            }
        }
        
        /// <remarks/>
        public string ESTARQ {
            get {
                return this.eSTARQField;
            }
            set {
                this.eSTARQField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC202.xsd")]
    public partial class BCARQComplexType {
        
        private string nomArqField;
        
        private string numCtrlEmisField;
        
        private string numCtrlDestOrField;
        
        private string iSPBEmissorField;
        
        private string iSPBDestinatarioField;
        
        private System.DateTime dtHrArqField;
        
        private string sitReqField;
        
        private Grupo_SeqComplexType grupo_SeqField;
        
        private System.DateTime dtRefField;
        
        /// <remarks/>
        public string NomArq {
            get {
                return this.nomArqField;
            }
            set {
                this.nomArqField = value;
            }
        }
        
        /// <remarks/>
        public string NumCtrlEmis {
            get {
                return this.numCtrlEmisField;
            }
            set {
                this.numCtrlEmisField = value;
            }
        }
        
        /// <remarks/>
        public string NumCtrlDestOr {
            get {
                return this.numCtrlDestOrField;
            }
            set {
                this.numCtrlDestOrField = value;
            }
        }
        
        /// <remarks/>
        public string ISPBEmissor {
            get {
                return this.iSPBEmissorField;
            }
            set {
                this.iSPBEmissorField = value;
            }
        }
        
        /// <remarks/>
        public string ISPBDestinatario {
            get {
                return this.iSPBDestinatarioField;
            }
            set {
                this.iSPBDestinatarioField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DtHrArq {
            get {
                return this.dtHrArqField;
            }
            set {
                this.dtHrArqField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string SitReq {
            get {
                return this.sitReqField;
            }
            set {
                this.sitReqField = value;
            }
        }
        
        /// <remarks/>
        public Grupo_SeqComplexType Grupo_Seq {
            get {
                return this.grupo_SeqField;
            }
            set {
                this.grupo_SeqField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime DtRef {
            get {
                return this.dtRefField;
            }
            set {
                this.dtRefField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC202.xsd")]
    public partial class Grupo_SeqComplexType {
        
        private string numSeqField;
        
        private Indr indrContField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string NumSeq {
            get {
                return this.numSeqField;
            }
            set {
                this.numSeqField = value;
            }
        }
        
        /// <remarks/>
        public Indr IndrCont {
            get {
                return this.indrContField;
            }
            set {
                this.indrContField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC202.xsd")]
    public enum Indr {
        
        /// <remarks/>
        S,
        
        /// <remarks/>
        N,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC202.xsd")]
    public partial class ACTC202ComplexType {
        
        private Grupo_ACTC202_PortlddComplexType[] grupo_ACTC202_PortlddField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Grupo_ACTC202_Portldd")]
        public Grupo_ACTC202_PortlddComplexType[] Grupo_ACTC202_Portldd {
            get {
                return this.grupo_ACTC202_PortlddField;
            }
            set {
                this.grupo_ACTC202_PortlddField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC202.xsd")]
    public partial class Grupo_ACTC202_PortlddComplexType {
        
        private string identdPartAdmdoField;
        
        private string nUPortlddCTCField;
        
        private string identdIFPropntField;
        
        private Grupo_IdentdContrto_ComplexType_1 grupo_ACTC202_IdentdContrtoField;
        
        private Grupo_ACTC_CliComplexType_CodErro[] grupo_ACTC202_CliField;
        
        private System.DateTime[] dtRefCalcSaldDevdrField;
        
        private Grupo_ACTC20x_PropPortlddComplexType grupo_ACTC202_PropPortlddField;
        
        private Grupo_EndImovl_ComplexType grupo_ACTC202_EndImovelField;
        
        private string emailConttoPropntField;
        
        private string telConttoPropntField;
        
        private Grupo_EndCartaPortldd_ComplexType grupo_ACTC202_EndCartaPortlddField;
        
        /// <remarks/>
        public string IdentdPartAdmdo {
            get {
                return this.identdPartAdmdoField;
            }
            set {
                this.identdPartAdmdoField = value;
            }
        }
        
        /// <remarks/>
        public string NUPortlddCTC {
            get {
                return this.nUPortlddCTCField;
            }
            set {
                this.nUPortlddCTCField = value;
            }
        }
        
        /// <remarks/>
        public string IdentdIFPropnt {
            get {
                return this.identdIFPropntField;
            }
            set {
                this.identdIFPropntField = value;
            }
        }
        
        /// <remarks/>
        public Grupo_IdentdContrto_ComplexType_1 Grupo_ACTC202_IdentdContrto {
            get {
                return this.grupo_ACTC202_IdentdContrtoField;
            }
            set {
                this.grupo_ACTC202_IdentdContrtoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Grupo_ACTC202_Cli")]
        public Grupo_ACTC_CliComplexType_CodErro[] Grupo_ACTC202_Cli {
            get {
                return this.grupo_ACTC202_CliField;
            }
            set {
                this.grupo_ACTC202_CliField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DtRefCalcSaldDevdr", DataType="date")]
        public System.DateTime[] DtRefCalcSaldDevdr {
            get {
                return this.dtRefCalcSaldDevdrField;
            }
            set {
                this.dtRefCalcSaldDevdrField = value;
            }
        }
        
        /// <remarks/>
        public Grupo_ACTC20x_PropPortlddComplexType Grupo_ACTC202_PropPortldd {
            get {
                return this.grupo_ACTC202_PropPortlddField;
            }
            set {
                this.grupo_ACTC202_PropPortlddField = value;
            }
        }
        
        /// <remarks/>
        public Grupo_EndImovl_ComplexType Grupo_ACTC202_EndImovel {
            get {
                return this.grupo_ACTC202_EndImovelField;
            }
            set {
                this.grupo_ACTC202_EndImovelField = value;
            }
        }
        
        /// <remarks/>
        public string EmailConttoPropnt {
            get {
                return this.emailConttoPropntField;
            }
            set {
                this.emailConttoPropntField = value;
            }
        }
        
        /// <remarks/>
        public string TelConttoPropnt {
            get {
                return this.telConttoPropntField;
            }
            set {
                this.telConttoPropntField = value;
            }
        }
        
        /// <remarks/>
        public Grupo_EndCartaPortldd_ComplexType Grupo_ACTC202_EndCartaPortldd {
            get {
                return this.grupo_ACTC202_EndCartaPortlddField;
            }
            set {
                this.grupo_ACTC202_EndCartaPortlddField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Grupo_ACTC60X_IdentdContrtoComplexType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC202.xsd")]
    public partial class Grupo_IdentdContrto_ComplexType_1 : Grupo_IdentdContrto_ComplexType {
        
        private CNPJ_CodErro cNPJCorrespBancField;
        
        /// <remarks/>
        public CNPJ_CodErro CNPJCorrespBanc {
            get {
                return this.cNPJCorrespBancField;
            }
            set {
                this.cNPJCorrespBancField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC202.xsd")]
    public partial class CNPJ_CodErro {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Grupo_ACTC701_IdentdContrtoComplexType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Grupo_ACTC70X_IdentdContrtoComplexType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Grupo_ACTC10X_IdentdContrtoComplexType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Grupo_IdentdContrto_ComplexType_1))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Grupo_ACTC60X_IdentdContrtoComplexType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC202.xsd")]
    public partial class Grupo_IdentdContrto_ComplexType {
        
        private CodContrtoOr_CodErro codContrtoOrField;
        
        private CNPJBase_CodErro cNPJBase_IFOrContrtoField;
        
        private TpContrto_CodErro tpContrtoField;
        
        private string codErroField;
        
        /// <remarks/>
        public CodContrtoOr_CodErro CodContrtoOr {
            get {
                return this.codContrtoOrField;
            }
            set {
                this.codContrtoOrField = value;
            }
        }
        
        /// <remarks/>
        public CNPJBase_CodErro CNPJBase_IFOrContrto {
            get {
                return this.cNPJBase_IFOrContrtoField;
            }
            set {
                this.cNPJBase_IFOrContrtoField = value;
            }
        }
        
        /// <remarks/>
        public TpContrto_CodErro TpContrto {
            get {
                return this.tpContrtoField;
            }
            set {
                this.tpContrtoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC202.xsd")]
    public partial class CodContrtoOr_CodErro {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC202.xsd")]
    public partial class CNPJBase_CodErro {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC202.xsd")]
    public partial class TpContrto_CodErro {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Grupo_ACTC70X_IdentdContrtoComplexType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC202.xsd")]
    public partial class Grupo_ACTC701_IdentdContrtoComplexType : Grupo_IdentdContrto_ComplexType {
        
        private TpEnteCons_CodErro tpEnteConsField;
        
        private CNPJ_CodErro cNPJCorrespBancField;
        
        /// <remarks/>
        public TpEnteCons_CodErro TpEnteCons {
            get {
                return this.tpEnteConsField;
            }
            set {
                this.tpEnteConsField = value;
            }
        }
        
        /// <remarks/>
        public CNPJ_CodErro CNPJCorrespBanc {
            get {
                return this.cNPJCorrespBancField;
            }
            set {
                this.cNPJCorrespBancField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC202.xsd")]
    public partial class TpEnteCons_CodErro {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="integer")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC202.xsd")]
    public partial class Grupo_ACTC70X_IdentdContrtoComplexType : Grupo_ACTC701_IdentdContrtoComplexType {
        
        private TpCt_CodErro tpCtField;
        
        private Agencia_CodErro agCliField;
        
        private CtBancaria_CodErro ctCliField;
        
        private CtPagto_CodErro ctPagtoField;
        
        private CtConjtaSoldria_CodErro ctConjtaSoldriaField;
        
        /// <remarks/>
        public TpCt_CodErro TpCt {
            get {
                return this.tpCtField;
            }
            set {
                this.tpCtField = value;
            }
        }
        
        /// <remarks/>
        public Agencia_CodErro AgCli {
            get {
                return this.agCliField;
            }
            set {
                this.agCliField = value;
            }
        }
        
        /// <remarks/>
        public CtBancaria_CodErro CtCli {
            get {
                return this.ctCliField;
            }
            set {
                this.ctCliField = value;
            }
        }
        
        /// <remarks/>
        public CtPagto_CodErro CtPagto {
            get {
                return this.ctPagtoField;
            }
            set {
                this.ctPagtoField = value;
            }
        }
        
        /// <remarks/>
        public CtConjtaSoldria_CodErro CtConjtaSoldria {
            get {
                return this.ctConjtaSoldriaField;
            }
            set {
                this.ctConjtaSoldriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC202.xsd")]
    public partial class TpCt_CodErro {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC202.xsd")]
    public partial class Agencia_CodErro {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="integer")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC202.xsd")]
    public partial class CtBancaria_CodErro {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="integer")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC202.xsd")]
    public partial class CtPagto_CodErro {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="integer")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC202.xsd")]
    public partial class CtConjtaSoldria_CodErro {
        
        private string codErroField;
        
        private CtConjtaSoldria valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public CtConjtaSoldria Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC202.xsd")]
    public enum CtConjtaSoldria {
        
        /// <remarks/>
        S,
        
        /// <remarks/>
        N,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC202.xsd")]
    public partial class Grupo_ACTC10X_IdentdContrtoComplexType : Grupo_IdentdContrto_ComplexType {
        
        private TpEnteCons_CodErro tpEnteConsField;
        
        private CNPJ_CodErro cNPJCorrespBancField;
        
        /// <remarks/>
        public TpEnteCons_CodErro TpEnteCons {
            get {
                return this.tpEnteConsField;
            }
            set {
                this.tpEnteConsField = value;
            }
        }
        
        /// <remarks/>
        public CNPJ_CodErro CNPJCorrespBanc {
            get {
                return this.cNPJCorrespBancField;
            }
            set {
                this.cNPJCorrespBancField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC202.xsd")]
    public partial class Grupo_ACTC60X_IdentdContrtoComplexType : Grupo_IdentdContrto_ComplexType_1 {
        
        private TpCt_CodErro tpCtField;
        
        private Agencia_CodErro agCliField;
        
        private CtBancaria_CodErro ctCliField;
        
        private CtPagto_CodErro ctPagtoField;
        
        private CtConjtaSoldria_CodErro ctConjtaSoldriaField;
        
        /// <remarks/>
        public TpCt_CodErro TpCt {
            get {
                return this.tpCtField;
            }
            set {
                this.tpCtField = value;
            }
        }
        
        /// <remarks/>
        public Agencia_CodErro AgCli {
            get {
                return this.agCliField;
            }
            set {
                this.agCliField = value;
            }
        }
        
        /// <remarks/>
        public CtBancaria_CodErro CtCli {
            get {
                return this.ctCliField;
            }
            set {
                this.ctCliField = value;
            }
        }
        
        /// <remarks/>
        public CtPagto_CodErro CtPagto {
            get {
                return this.ctPagtoField;
            }
            set {
                this.ctPagtoField = value;
            }
        }
        
        /// <remarks/>
        public CtConjtaSoldria_CodErro CtConjtaSoldria {
            get {
                return this.ctConjtaSoldriaField;
            }
            set {
                this.ctConjtaSoldriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC202.xsd")]
    public partial class Grupo_ACTC_CliComplexType_CodErro {
        
        private TpPessoa_CodErro tpCliField;
        
        private CNPJ_CPF_CodErro cNPJ_CPFCliField;
        
        private Nome_CodErro nomCliField;
        
        private Telefone_CodErro telCliField;
        
        private Email_CodErro emailCliField;
        
        private Texto_CodErro logradEndCliField;
        
        private Texto_CodErro compEndCliField;
        
        private NumEnd_CodErro numEndCliField;
        
        private CidEnd_CodErro cidEndCliField;
        
        private UF_CodErro uFEndCliField;
        
        private CEP_CodErro cEPEndCliField;
        
        private string codErroField;
        
        /// <remarks/>
        public TpPessoa_CodErro TpCli {
            get {
                return this.tpCliField;
            }
            set {
                this.tpCliField = value;
            }
        }
        
        /// <remarks/>
        public CNPJ_CPF_CodErro CNPJ_CPFCli {
            get {
                return this.cNPJ_CPFCliField;
            }
            set {
                this.cNPJ_CPFCliField = value;
            }
        }
        
        /// <remarks/>
        public Nome_CodErro NomCli {
            get {
                return this.nomCliField;
            }
            set {
                this.nomCliField = value;
            }
        }
        
        /// <remarks/>
        public Telefone_CodErro TelCli {
            get {
                return this.telCliField;
            }
            set {
                this.telCliField = value;
            }
        }
        
        /// <remarks/>
        public Email_CodErro EmailCli {
            get {
                return this.emailCliField;
            }
            set {
                this.emailCliField = value;
            }
        }
        
        /// <remarks/>
        public Texto_CodErro LogradEndCli {
            get {
                return this.logradEndCliField;
            }
            set {
                this.logradEndCliField = value;
            }
        }
        
        /// <remarks/>
        public Texto_CodErro CompEndCli {
            get {
                return this.compEndCliField;
            }
            set {
                this.compEndCliField = value;
            }
        }
        
        /// <remarks/>
        public NumEnd_CodErro NumEndCli {
            get {
                return this.numEndCliField;
            }
            set {
                this.numEndCliField = value;
            }
        }
        
        /// <remarks/>
        public CidEnd_CodErro CidEndCli {
            get {
                return this.cidEndCliField;
            }
            set {
                this.cidEndCliField = value;
            }
        }
        
        /// <remarks/>
        public UF_CodErro UFEndCli {
            get {
                return this.uFEndCliField;
            }
            set {
                this.uFEndCliField = value;
            }
        }
        
        /// <remarks/>
        public CEP_CodErro CEPEndCli {
            get {
                return this.cEPEndCliField;
            }
            set {
                this.cEPEndCliField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC202.xsd")]
    public partial class TpPessoa_CodErro {
        
        private string codErroField;
        
        private TpPessoa valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public TpPessoa Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC202.xsd")]
    public enum TpPessoa {
        
        /// <remarks/>
        F,
        
        /// <remarks/>
        J,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC202.xsd")]
    public partial class CNPJ_CPF_CodErro {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC202.xsd")]
    public partial class Nome_CodErro {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC202.xsd")]
    public partial class Telefone_CodErro {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC202.xsd")]
    public partial class Email_CodErro {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC202.xsd")]
    public partial class Texto_CodErro {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC202.xsd")]
    public partial class NumEnd_CodErro {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC202.xsd")]
    public partial class CidEnd_CodErro {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC202.xsd")]
    public partial class UF_CodErro {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC202.xsd")]
    public partial class CEP_CodErro {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC202.xsd")]
    public partial class Grupo_ACTC20x_PropPortlddComplexType {
        
        private Data_CodErro dtRefSaldDevdrContbField;
        
        private Valor_CodErro vlrSaldDevdrContbField;
        
        private TpContrto_CodErro tpContrtoPropField;
        
        private TpTaxa_CodErro tpTxField;
        
        private Percentual_CodErro txJurosNomlField;
        
        private Percentual_CodErro txJurosEftField;
        
        private Percentual_CodErro txCETField;
        
        private Percentual_CodErro cstEftSegrHabtnlField;
        
        private Valor_CodErro vlrAvalDFIField;
        
        private Qtd_CodErro przOpField;
        
        private CodMoeda_CodErro codMoedaField;
        
        private IndRemun_CodErro indRemunField;
        
        private RegmAmtzc_CodErro regmAmtzcField;
        
        private Valor_CodErro vlrParclInialField;
        
        private Valor_CodErro vlrParclAmtzInialField;
        
        private Valor_CodErro vlrParclJurosInialField;
        
        private Valor_CodErro premMIPInialField;
        
        private Valor_CodErro premDFIInialField;
        
        private Valor_CodErro tarMesInialField;
        
        private Data_CodErro dtVencPrimParclField;
        
        private Data_CodErro dtVencUltParclField;
        
        private string codErroField;
        
        /// <remarks/>
        public Data_CodErro DtRefSaldDevdrContb {
            get {
                return this.dtRefSaldDevdrContbField;
            }
            set {
                this.dtRefSaldDevdrContbField = value;
            }
        }
        
        /// <remarks/>
        public Valor_CodErro VlrSaldDevdrContb {
            get {
                return this.vlrSaldDevdrContbField;
            }
            set {
                this.vlrSaldDevdrContbField = value;
            }
        }
        
        /// <remarks/>
        public TpContrto_CodErro TpContrtoProp {
            get {
                return this.tpContrtoPropField;
            }
            set {
                this.tpContrtoPropField = value;
            }
        }
        
        /// <remarks/>
        public TpTaxa_CodErro TpTx {
            get {
                return this.tpTxField;
            }
            set {
                this.tpTxField = value;
            }
        }
        
        /// <remarks/>
        public Percentual_CodErro TxJurosNoml {
            get {
                return this.txJurosNomlField;
            }
            set {
                this.txJurosNomlField = value;
            }
        }
        
        /// <remarks/>
        public Percentual_CodErro TxJurosEft {
            get {
                return this.txJurosEftField;
            }
            set {
                this.txJurosEftField = value;
            }
        }
        
        /// <remarks/>
        public Percentual_CodErro TxCET {
            get {
                return this.txCETField;
            }
            set {
                this.txCETField = value;
            }
        }
        
        /// <remarks/>
        public Percentual_CodErro CstEftSegrHabtnl {
            get {
                return this.cstEftSegrHabtnlField;
            }
            set {
                this.cstEftSegrHabtnlField = value;
            }
        }
        
        /// <remarks/>
        public Valor_CodErro VlrAvalDFI {
            get {
                return this.vlrAvalDFIField;
            }
            set {
                this.vlrAvalDFIField = value;
            }
        }
        
        /// <remarks/>
        public Qtd_CodErro PrzOp {
            get {
                return this.przOpField;
            }
            set {
                this.przOpField = value;
            }
        }
        
        /// <remarks/>
        public CodMoeda_CodErro CodMoeda {
            get {
                return this.codMoedaField;
            }
            set {
                this.codMoedaField = value;
            }
        }
        
        /// <remarks/>
        public IndRemun_CodErro IndRemun {
            get {
                return this.indRemunField;
            }
            set {
                this.indRemunField = value;
            }
        }
        
        /// <remarks/>
        public RegmAmtzc_CodErro RegmAmtzc {
            get {
                return this.regmAmtzcField;
            }
            set {
                this.regmAmtzcField = value;
            }
        }
        
        /// <remarks/>
        public Valor_CodErro VlrParclInial {
            get {
                return this.vlrParclInialField;
            }
            set {
                this.vlrParclInialField = value;
            }
        }
        
        /// <remarks/>
        public Valor_CodErro VlrParclAmtzInial {
            get {
                return this.vlrParclAmtzInialField;
            }
            set {
                this.vlrParclAmtzInialField = value;
            }
        }
        
        /// <remarks/>
        public Valor_CodErro VlrParclJurosInial {
            get {
                return this.vlrParclJurosInialField;
            }
            set {
                this.vlrParclJurosInialField = value;
            }
        }
        
        /// <remarks/>
        public Valor_CodErro PremMIPInial {
            get {
                return this.premMIPInialField;
            }
            set {
                this.premMIPInialField = value;
            }
        }
        
        /// <remarks/>
        public Valor_CodErro PremDFIInial {
            get {
                return this.premDFIInialField;
            }
            set {
                this.premDFIInialField = value;
            }
        }
        
        /// <remarks/>
        public Valor_CodErro TarMesInial {
            get {
                return this.tarMesInialField;
            }
            set {
                this.tarMesInialField = value;
            }
        }
        
        /// <remarks/>
        public Data_CodErro DtVencPrimParcl {
            get {
                return this.dtVencPrimParclField;
            }
            set {
                this.dtVencPrimParclField = value;
            }
        }
        
        /// <remarks/>
        public Data_CodErro DtVencUltParcl {
            get {
                return this.dtVencUltParclField;
            }
            set {
                this.dtVencUltParclField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC202.xsd")]
    public partial class Data_CodErro {
        
        private string codErroField;
        
        private System.DateTime valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="date")]
        public System.DateTime Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC202.xsd")]
    public partial class Valor_CodErro {
        
        private string codErroField;
        
        private decimal valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public decimal Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC202.xsd")]
    public partial class TpTaxa_CodErro {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="integer")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC202.xsd")]
    public partial class Percentual_CodErro {
        
        private string codErroField;
        
        private decimal valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public decimal Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC202.xsd")]
    public partial class Qtd_CodErro {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="integer")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC202.xsd")]
    public partial class CodMoeda_CodErro {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="integer")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC202.xsd")]
    public partial class IndRemun_CodErro {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="integer")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC202.xsd")]
    public partial class RegmAmtzc_CodErro {
        
        private string codErroField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="integer")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC202.xsd")]
    public partial class Grupo_EndImovl_ComplexType {
        
        private Texto_CodErro logradEndImovlField;
        
        private Texto_CodErro compEndImovlField;
        
        private NumEnd_CodErro numEndImovlField;
        
        private CidEnd_CodErro cidEndImovlField;
        
        private UF_CodErro uFEndImovlField;
        
        private CEP_CodErro cEPEndImovlField;
        
        private string codErroField;
        
        /// <remarks/>
        public Texto_CodErro LogradEndImovl {
            get {
                return this.logradEndImovlField;
            }
            set {
                this.logradEndImovlField = value;
            }
        }
        
        /// <remarks/>
        public Texto_CodErro CompEndImovl {
            get {
                return this.compEndImovlField;
            }
            set {
                this.compEndImovlField = value;
            }
        }
        
        /// <remarks/>
        public NumEnd_CodErro NumEndImovl {
            get {
                return this.numEndImovlField;
            }
            set {
                this.numEndImovlField = value;
            }
        }
        
        /// <remarks/>
        public CidEnd_CodErro CidEndImovl {
            get {
                return this.cidEndImovlField;
            }
            set {
                this.cidEndImovlField = value;
            }
        }
        
        /// <remarks/>
        public UF_CodErro UFEndImovl {
            get {
                return this.uFEndImovlField;
            }
            set {
                this.uFEndImovlField = value;
            }
        }
        
        /// <remarks/>
        public CEP_CodErro CEPEndImovl {
            get {
                return this.cEPEndImovlField;
            }
            set {
                this.cEPEndImovlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC202.xsd")]
    public partial class Grupo_EndCartaPortldd_ComplexType {
        
        private Texto_CodErro logradEndCartaPortlddField;
        
        private Texto_CodErro compEndCartaPortlddField;
        
        private NumEnd_CodErro numEndCartaPortlddField;
        
        private CidEnd_CodErro cidEndCartaPortlddField;
        
        private UF_CodErro uFEndCartaPortlddField;
        
        private CEP_CodErro cEPEndCartaPortlddField;
        
        private string codErroField;
        
        /// <remarks/>
        public Texto_CodErro LogradEndCartaPortldd {
            get {
                return this.logradEndCartaPortlddField;
            }
            set {
                this.logradEndCartaPortlddField = value;
            }
        }
        
        /// <remarks/>
        public Texto_CodErro CompEndCartaPortldd {
            get {
                return this.compEndCartaPortlddField;
            }
            set {
                this.compEndCartaPortlddField = value;
            }
        }
        
        /// <remarks/>
        public NumEnd_CodErro NumEndCartaPortldd {
            get {
                return this.numEndCartaPortlddField;
            }
            set {
                this.numEndCartaPortlddField = value;
            }
        }
        
        /// <remarks/>
        public CidEnd_CodErro CidEndCartaPortldd {
            get {
                return this.cidEndCartaPortlddField;
            }
            set {
                this.cidEndCartaPortlddField = value;
            }
        }
        
        /// <remarks/>
        public UF_CodErro UFEndCartaPortldd {
            get {
                return this.uFEndCartaPortlddField;
            }
            set {
                this.uFEndCartaPortlddField = value;
            }
        }
        
        /// <remarks/>
        public CEP_CodErro CEPEndCartaPortldd {
            get {
                return this.cEPEndCartaPortlddField;
            }
            set {
                this.cEPEndCartaPortlddField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CodErro {
            get {
                return this.codErroField;
            }
            set {
                this.codErroField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC202.xsd")]
    public partial class SISARQComplexType {
        
        private ACTC202ComplexType itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ACTC202")]
        public ACTC202ComplexType Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
}
