//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
using FastConsig.CTC.Model.Interfaces;

namespace FastConsig.CTC.Model.AGEN001
{
   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlRootAttribute("ADDADOC", Namespace = "", IsNullable = false)]
   public partial class AGEN001 : IACTC
   {

      private BCARQComplexType bCARQField;

      private SISARQComplexType sISARQField;

      private string[] textField;

      /// <remarks/>
      public BCARQComplexType BCARQ
      {
         get
         {
            return this.bCARQField;
         }
         set
         {
            this.bCARQField = value;
         }
      }

      /// <remarks/>
      public SISARQComplexType SISARQ
      {
         get
         {
            return this.sISARQField;
         }
         set
         {
            this.sISARQField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlTextAttribute()]
      public string[] Text
      {
         get
         {
            return this.textField;
         }
         set
         {
            this.textField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   public partial class BCARQComplexType
   {

      private string nomArqField;

      private string numCtrlEmisField;

      private string numCtrlDestOrField;

      private string iSPBEmissorField;

      private string iSPBDestinatarioField;

      private System.DateTime dtHrField;

      private string sitReqField;

      private string indrFlagFimField;

      private System.DateTime dtMovtoField;

      private string[] textField;

      /// <remarks/>
      public string NomArq
      {
         get
         {
            return this.nomArqField;
         }
         set
         {
            this.nomArqField = value;
         }
      }

      /// <remarks/>
      public string NumCtrlEmis
      {
         get
         {
            return this.numCtrlEmisField;
         }
         set
         {
            this.numCtrlEmisField = value;
         }
      }

      /// <remarks/>
      public string NumCtrlDestOr
      {
         get
         {
            return this.numCtrlDestOrField;
         }
         set
         {
            this.numCtrlDestOrField = value;
         }
      }

      /// <remarks/>
      public string ISPBEmissor
      {
         get
         {
            return this.iSPBEmissorField;
         }
         set
         {
            this.iSPBEmissorField = value;
         }
      }

      /// <remarks/>
      public string ISPBDestinatario
      {
         get
         {
            return this.iSPBDestinatarioField;
         }
         set
         {
            this.iSPBDestinatarioField = value;
         }
      }

      /// <remarks/>
      public System.DateTime DtHrDDA
      {
         get
         {
            return this.dtHrField;
         }
         set
         {
            this.dtHrField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
      public string SitReq
      {
         get
         {
            return this.sitReqField;
         }
         set
         {
            this.sitReqField = value;
         }
      }

      /// <remarks/>
      public string IndrFlagFim
      {
         get
         {
            return this.indrFlagFimField;
         }
         set
         {
            this.indrFlagFimField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
      public System.DateTime DtMovto
      {
         get
         {
            return this.dtMovtoField;
         }
         set
         {
            this.dtMovtoField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlTextAttribute()]
      public string[] Text
      {
         get
         {
            return this.textField;
         }
         set
         {
            this.textField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   public partial class AGEN001ComplexType
   {

      private string iSPBEmissorField;

      private string iSPBDestinatarioField;

      private string msgECOField;

      private string[] textField;

      /// <remarks/>
      public string ISPBEmissor
      {
         get
         {
            return this.iSPBEmissorField;
         }
         set
         {
            this.iSPBEmissorField = value;
         }
      }

      /// <remarks/>
      public string ISPBDestinatario
      {
         get
         {
            return this.iSPBDestinatarioField;
         }
         set
         {
            this.iSPBDestinatarioField = value;
         }
      }

      /// <remarks/>
      public string MsgECO
      {
         get
         {
            return this.msgECOField;
         }
         set
         {
            this.msgECOField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlTextAttribute()]
      public string[] Text
      {
         get
         {
            return this.textField;
         }
         set
         {
            this.textField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   public partial class SISARQComplexType
   {

      private AGEN001ComplexType aGEN001Field;

      private string[] textField;

      /// <remarks/>
      public AGEN001ComplexType AGEN001
      {
         get
         {
            return this.aGEN001Field;
         }
         set
         {
            this.aGEN001Field = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlTextAttribute()]
      public string[] Text
      {
         get
         {
            return this.textField;
         }
         set
         {
            this.textField = value;
         }
      }
   }
}
