//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace FastConsig.CTC.Model.ACTC921
{
   using FastConsig.CTC.Model.Interfaces;
   using System.Xml.Serialization;


   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC921.xsd")]
   [System.Xml.Serialization.XmlRootAttribute("ACTCDOC", Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC921.xsd", IsNullable = false)]
   public partial class ACTC921 : IACTC
   {

      private BCARQComplexType bCARQField;

      private SISARQComplexType sISARQField;

      private string eSTARQField;

      /// <remarks/>
      public BCARQComplexType BCARQ
      {
         get
         {
            return this.bCARQField;
         }
         set
         {
            this.bCARQField = value;
         }
      }

      /// <remarks/>
      public SISARQComplexType SISARQ
      {
         get
         {
            return this.sISARQField;
         }
         set
         {
            this.sISARQField = value;
         }
      }

      /// <remarks/>
      public string ESTARQ
      {
         get
         {
            return this.eSTARQField;
         }
         set
         {
            this.eSTARQField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC921.xsd")]
   public partial class BCARQComplexType
   {

      private string nomArqField;

      private string numCtrlEmisField;

      private string numCtrlDestOrField;

      private string iSPBEmissorField;

      private string iSPBDestinatarioField;

      private System.DateTime dtHrArqField;

      private string sitReqField;

      private Grupo_SeqComplexType grupo_SeqField;

      private System.DateTime dtRefField;

      /// <remarks/>
      public string NomArq
      {
         get
         {
            return this.nomArqField;
         }
         set
         {
            this.nomArqField = value;
         }
      }

      /// <remarks/>
      public string NumCtrlEmis
      {
         get
         {
            return this.numCtrlEmisField;
         }
         set
         {
            this.numCtrlEmisField = value;
         }
      }

      /// <remarks/>
      public string NumCtrlDestOr
      {
         get
         {
            return this.numCtrlDestOrField;
         }
         set
         {
            this.numCtrlDestOrField = value;
         }
      }

      /// <remarks/>
      public string ISPBEmissor
      {
         get
         {
            return this.iSPBEmissorField;
         }
         set
         {
            this.iSPBEmissorField = value;
         }
      }

      /// <remarks/>
      public string ISPBDestinatario
      {
         get
         {
            return this.iSPBDestinatarioField;
         }
         set
         {
            this.iSPBDestinatarioField = value;
         }
      }

      /// <remarks/>
      public System.DateTime DtHrArq
      {
         get
         {
            return this.dtHrArqField;
         }
         set
         {
            this.dtHrArqField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
      public string SitReq
      {
         get
         {
            return this.sitReqField;
         }
         set
         {
            this.sitReqField = value;
         }
      }

      /// <remarks/>
      public Grupo_SeqComplexType Grupo_Seq
      {
         get
         {
            return this.grupo_SeqField;
         }
         set
         {
            this.grupo_SeqField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
      public System.DateTime DtRef
      {
         get
         {
            return this.dtRefField;
         }
         set
         {
            this.dtRefField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC921.xsd")]
   public partial class Grupo_SeqComplexType
   {

      private string numSeqField;

      private Indr indrContField;

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
      public string NumSeq
      {
         get
         {
            return this.numSeqField;
         }
         set
         {
            this.numSeqField = value;
         }
      }

      /// <remarks/>
      public Indr IndrCont
      {
         get
         {
            return this.indrContField;
         }
         set
         {
            this.indrContField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC921.xsd")]
   public enum Indr
   {

      /// <remarks/>
      S,

      /// <remarks/>
      N,
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC921.xsd")]
   public partial class Grupo_ACTC921_CliComplexType
   {

      private TpPessoa tpCliField;

      private string cNPJ_CPFCliField;

      private string nomCliField;

      private string telCliField;

      private string emailCliField;

      /// <remarks/>
      public TpPessoa TpCli
      {
         get
         {
            return this.tpCliField;
         }
         set
         {
            this.tpCliField = value;
         }
      }

      /// <remarks/>
      public string CNPJ_CPFCli
      {
         get
         {
            return this.cNPJ_CPFCliField;
         }
         set
         {
            this.cNPJ_CPFCliField = value;
         }
      }

      /// <remarks/>
      public string NomCli
      {
         get
         {
            return this.nomCliField;
         }
         set
         {
            this.nomCliField = value;
         }
      }

      /// <remarks/>
      public string TelCli
      {
         get
         {
            return this.telCliField;
         }
         set
         {
            this.telCliField = value;
         }
      }

      /// <remarks/>
      public string EmailCli
      {
         get
         {
            return this.emailCliField;
         }
         set
         {
            this.emailCliField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC921.xsd")]
   public enum TpPessoa
   {

      /// <remarks/>
      F,

      /// <remarks/>
      J,
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC921.xsd")]
   public partial class Grupo_ACTC921_EvtTarComplexType
   {

      private string codEvtTarField;

      private System.DateTime dtEvtTarField;

      private string nUPortlddCTCField;

      private string iSPBPropntField;

      private string codContrtoOrField;

      private string cNPJBase_IFOrContrtoField;

      private string tpEnteConsField;

      private Grupo_ACTC921_CliComplexType[] grupo_ACTC921_CliField;

      /// <remarks/>
      public string CodEvtTar
      {
         get
         {
            return this.codEvtTarField;
         }
         set
         {
            this.codEvtTarField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
      public System.DateTime DtEvtTar
      {
         get
         {
            return this.dtEvtTarField;
         }
         set
         {
            this.dtEvtTarField = value;
         }
      }

      /// <remarks/>
      public string NUPortlddCTC
      {
         get
         {
            return this.nUPortlddCTCField;
         }
         set
         {
            this.nUPortlddCTCField = value;
         }
      }

      /// <remarks/>
      public string ISPBPropnt
      {
         get
         {
            return this.iSPBPropntField;
         }
         set
         {
            this.iSPBPropntField = value;
         }
      }

      /// <remarks/>
      public string CodContrtoOr
      {
         get
         {
            return this.codContrtoOrField;
         }
         set
         {
            this.codContrtoOrField = value;
         }
      }

      /// <remarks/>
      public string CNPJBase_IFOrContrto
      {
         get
         {
            return this.cNPJBase_IFOrContrtoField;
         }
         set
         {
            this.cNPJBase_IFOrContrtoField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
      public string TpEnteCons
      {
         get
         {
            return this.tpEnteConsField;
         }
         set
         {
            this.tpEnteConsField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute("Grupo_ACTC921_Cli")]
      public Grupo_ACTC921_CliComplexType[] Grupo_ACTC921_Cli
      {
         get
         {
            return this.grupo_ACTC921_CliField;
         }
         set
         {
            this.grupo_ACTC921_CliField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC921.xsd")]
   public partial class Grupo_ACTC921_TpContrtoComplexType
   {

      private string tpContrtoField;

      private Grupo_ACTC921_EvtTarComplexType[] grupo_ACTC921_EvtTarField;

      /// <remarks/>
      public string TpContrto
      {
         get
         {
            return this.tpContrtoField;
         }
         set
         {
            this.tpContrtoField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute("Grupo_ACTC921_EvtTar")]
      public Grupo_ACTC921_EvtTarComplexType[] Grupo_ACTC921_EvtTar
      {
         get
         {
            return this.grupo_ACTC921_EvtTarField;
         }
         set
         {
            this.grupo_ACTC921_EvtTarField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC921.xsd")]
   public partial class Grupo_ACTC921_RelatConclcTarComplexType
   {

      private string identdPartAdmdoField;

      private string numCtrlCIPField;

      private string tpRelatField;

      private string anoMesRefApurcField;

      private System.DateTime dtIniApurcField;

      private System.DateTime dtFimApurcField;

      private string sitProcField;

      private Grupo_ACTC921_TpContrtoComplexType[] grupo_ACTC921_TpContrtoField;

      /// <remarks/>
      public string IdentdPartAdmdo
      {
         get
         {
            return this.identdPartAdmdoField;
         }
         set
         {
            this.identdPartAdmdoField = value;
         }
      }

      /// <remarks/>
      public string NumCtrlCIP
      {
         get
         {
            return this.numCtrlCIPField;
         }
         set
         {
            this.numCtrlCIPField = value;
         }
      }

      /// <remarks/>
      public string TpRelat
      {
         get
         {
            return this.tpRelatField;
         }
         set
         {
            this.tpRelatField = value;
         }
      }

      /// <remarks/>
      public string AnoMesRefApurc
      {
         get
         {
            return this.anoMesRefApurcField;
         }
         set
         {
            this.anoMesRefApurcField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
      public System.DateTime DtIniApurc
      {
         get
         {
            return this.dtIniApurcField;
         }
         set
         {
            this.dtIniApurcField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
      public System.DateTime DtFimApurc
      {
         get
         {
            return this.dtFimApurcField;
         }
         set
         {
            this.dtFimApurcField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
      public string SitProc
      {
         get
         {
            return this.sitProcField;
         }
         set
         {
            this.sitProcField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute("Grupo_ACTC921_TpContrto")]
      public Grupo_ACTC921_TpContrtoComplexType[] Grupo_ACTC921_TpContrto
      {
         get
         {
            return this.grupo_ACTC921_TpContrtoField;
         }
         set
         {
            this.grupo_ACTC921_TpContrtoField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC921.xsd")]
   public partial class ACTC921ComplexType
   {

      private Grupo_ACTC921_RelatConclcTarComplexType grupo_ACTC921_RelatConclcTarField;

      /// <remarks/>
      public Grupo_ACTC921_RelatConclcTarComplexType Grupo_ACTC921_RelatConclcTar
      {
         get
         {
            return this.grupo_ACTC921_RelatConclcTarField;
         }
         set
         {
            this.grupo_ACTC921_RelatConclcTarField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC921.xsd")]
   public partial class SISARQComplexType
   {

      private ACTC921ComplexType itemField;

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute("ACTC921")]
      public ACTC921ComplexType Item
      {
         get
         {
            return this.itemField;
         }
         set
         {
            this.itemField = value;
         }
      }
   }
}
