//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace FastConsig.CTC.Model.ACTC900
{
   using FastConsig.CTC.Model.Interfaces;
   using System.Xml.Serialization;


   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC900.xsd")]
   [System.Xml.Serialization.XmlRootAttribute("ACTCDOC", Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC900.xsd", IsNullable = false)]
   public partial class ACTC900 : IACTC
   {

      private BCARQComplexType bCARQField;

      private SISARQComplexType sISARQField;

      private string eSTARQField;

      /// <remarks/>
      public BCARQComplexType BCARQ
      {
         get
         {
            return this.bCARQField;
         }
         set
         {
            this.bCARQField = value;
         }
      }

      /// <remarks/>
      public SISARQComplexType SISARQ
      {
         get
         {
            return this.sISARQField;
         }
         set
         {
            this.sISARQField = value;
         }
      }

      /// <remarks/>
      public string ESTARQ
      {
         get
         {
            return this.eSTARQField;
         }
         set
         {
            this.eSTARQField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC900.xsd")]
   public partial class BCARQComplexType
   {

      private string nomArqField;

      private string numCtrlEmisField;

      private string numCtrlDestOrField;

      private string iSPBEmissorField;

      private string iSPBDestinatarioField;

      private System.DateTime dtHrArqField;

      private string sitReqField;

      private Grupo_SeqComplexType grupo_SeqField;

      private System.DateTime dtRefField;

      /// <remarks/>
      public string NomArq
      {
         get
         {
            return this.nomArqField;
         }
         set
         {
            this.nomArqField = value;
         }
      }

      /// <remarks/>
      public string NumCtrlEmis
      {
         get
         {
            return this.numCtrlEmisField;
         }
         set
         {
            this.numCtrlEmisField = value;
         }
      }

      /// <remarks/>
      public string NumCtrlDestOr
      {
         get
         {
            return this.numCtrlDestOrField;
         }
         set
         {
            this.numCtrlDestOrField = value;
         }
      }

      /// <remarks/>
      public string ISPBEmissor
      {
         get
         {
            return this.iSPBEmissorField;
         }
         set
         {
            this.iSPBEmissorField = value;
         }
      }

      /// <remarks/>
      public string ISPBDestinatario
      {
         get
         {
            return this.iSPBDestinatarioField;
         }
         set
         {
            this.iSPBDestinatarioField = value;
         }
      }

      /// <remarks/>
      public System.DateTime DtHrArq
      {
         get
         {
            return this.dtHrArqField;
         }
         set
         {
            this.dtHrArqField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
      public string SitReq
      {
         get
         {
            return this.sitReqField;
         }
         set
         {
            this.sitReqField = value;
         }
      }

      /// <remarks/>
      public Grupo_SeqComplexType Grupo_Seq
      {
         get
         {
            return this.grupo_SeqField;
         }
         set
         {
            this.grupo_SeqField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
      public System.DateTime DtRef
      {
         get
         {
            return this.dtRefField;
         }
         set
         {
            this.dtRefField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC900.xsd")]
   public partial class Grupo_SeqComplexType
   {

      private string numSeqField;

      private Indr indrContField;

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
      public string NumSeq
      {
         get
         {
            return this.numSeqField;
         }
         set
         {
            this.numSeqField = value;
         }
      }

      /// <remarks/>
      public Indr IndrCont
      {
         get
         {
            return this.indrContField;
         }
         set
         {
            this.indrContField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC900.xsd")]
   public enum Indr
   {

      /// <remarks/>
      S,

      /// <remarks/>
      N,
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC900.xsd")]
   public partial class Data_CodErro
   {

      private string codErroField;

      private System.DateTime valueField;

      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string CodErro
      {
         get
         {
            return this.codErroField;
         }
         set
         {
            this.codErroField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlTextAttribute(DataType = "date")]
      public System.DateTime Value
      {
         get
         {
            return this.valueField;
         }
         set
         {
            this.valueField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC900.xsd")]
   public partial class MtvCanceltPortldd_CodErro
   {

      private string codErroField;

      private string valueField;

      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string CodErro
      {
         get
         {
            return this.codErroField;
         }
         set
         {
            this.codErroField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlTextAttribute(DataType = "integer")]
      public string Value
      {
         get
         {
            return this.valueField;
         }
         set
         {
            this.valueField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC900.xsd")]
   public partial class NU_CodErro
   {

      private string codErroField;

      private string valueField;

      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string CodErro
      {
         get
         {
            return this.codErroField;
         }
         set
         {
            this.codErroField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlTextAttribute()]
      public string Value
      {
         get
         {
            return this.valueField;
         }
         set
         {
            this.valueField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC900.xsd")]
   public partial class CNPJBase_CodErro
   {

      private string codErroField;

      private string valueField;

      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string CodErro
      {
         get
         {
            return this.codErroField;
         }
         set
         {
            this.codErroField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlTextAttribute()]
      public string Value
      {
         get
         {
            return this.valueField;
         }
         set
         {
            this.valueField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC900.xsd")]
   public partial class Grupo_ACTC900RET_CancelPortlddRecsdComplexType
   {

      private CNPJBase_CodErro identdPartAdmdoField;

      private NU_CodErro nUPortlddCTCField;

      private MtvCanceltPortldd_CodErro mtvCanceltPortlddField;

      private Data_CodErro dtCanceltPortlddField;

      private string codErroField;

      /// <remarks/>
      public CNPJBase_CodErro IdentdPartAdmdo
      {
         get
         {
            return this.identdPartAdmdoField;
         }
         set
         {
            this.identdPartAdmdoField = value;
         }
      }

      /// <remarks/>
      public NU_CodErro NUPortlddCTC
      {
         get
         {
            return this.nUPortlddCTCField;
         }
         set
         {
            this.nUPortlddCTCField = value;
         }
      }

      /// <remarks/>
      public MtvCanceltPortldd_CodErro MtvCanceltPortldd
      {
         get
         {
            return this.mtvCanceltPortlddField;
         }
         set
         {
            this.mtvCanceltPortlddField = value;
         }
      }

      /// <remarks/>
      public Data_CodErro DtCanceltPortldd
      {
         get
         {
            return this.dtCanceltPortlddField;
         }
         set
         {
            this.dtCanceltPortlddField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string CodErro
      {
         get
         {
            return this.codErroField;
         }
         set
         {
            this.codErroField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC900.xsd")]
   public partial class Grupo_ACTC900RET_CancelPortlddActoComplexType
   {

      private string identdPartAdmdoField;

      private string nUPortlddCTCField;

      /// <remarks/>
      public string IdentdPartAdmdo
      {
         get
         {
            return this.identdPartAdmdoField;
         }
         set
         {
            this.identdPartAdmdoField = value;
         }
      }

      /// <remarks/>
      public string NUPortlddCTC
      {
         get
         {
            return this.nUPortlddCTCField;
         }
         set
         {
            this.nUPortlddCTCField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC900.xsd")]
   public partial class ACTC900RETComplexType
   {

      private Grupo_ACTC900RET_CancelPortlddActoComplexType[] grupo_ACTC900RET_CanceltPortlddActoField;

      private Grupo_ACTC900RET_CancelPortlddRecsdComplexType[] grupo_ACTC900RET_CanceltPortlddRecsdField;

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute("Grupo_ACTC900RET_CanceltPortlddActo")]
      public Grupo_ACTC900RET_CancelPortlddActoComplexType[] Grupo_ACTC900RET_CanceltPortlddActo
      {
         get
         {
            return this.grupo_ACTC900RET_CanceltPortlddActoField;
         }
         set
         {
            this.grupo_ACTC900RET_CanceltPortlddActoField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute("Grupo_ACTC900RET_CanceltPortlddRecsd")]
      public Grupo_ACTC900RET_CancelPortlddRecsdComplexType[] Grupo_ACTC900RET_CanceltPortlddRecsd
      {
         get
         {
            return this.grupo_ACTC900RET_CanceltPortlddRecsdField;
         }
         set
         {
            this.grupo_ACTC900RET_CanceltPortlddRecsdField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC900.xsd")]
   public partial class ACTC900ComplexType
   {

      private Grupo_ACTC900_CancelPortlddComplexType[] grupo_ACTC900_CanceltPortlddField;

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute("Grupo_ACTC900_CanceltPortldd")]
      public Grupo_ACTC900_CancelPortlddComplexType[] Grupo_ACTC900_CanceltPortldd
      {
         get
         {
            return this.grupo_ACTC900_CanceltPortlddField;
         }
         set
         {
            this.grupo_ACTC900_CanceltPortlddField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC900.xsd")]
   public partial class Grupo_ACTC900_CancelPortlddComplexType
   {

      private string identdPartAdmdoField;

      private string nUPortlddCTCField;

      private string mtvCanceltPortlddField;

      private System.DateTime dtCanceltPortlddField;

      /// <remarks/>
      public string IdentdPartAdmdo
      {
         get
         {
            return this.identdPartAdmdoField;
         }
         set
         {
            this.identdPartAdmdoField = value;
         }
      }

      /// <remarks/>
      public string NUPortlddCTC
      {
         get
         {
            return this.nUPortlddCTCField;
         }
         set
         {
            this.nUPortlddCTCField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
      public string MtvCanceltPortldd
      {
         get
         {
            return this.mtvCanceltPortlddField;
         }
         set
         {
            this.mtvCanceltPortlddField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
      public System.DateTime DtCanceltPortldd
      {
         get
         {
            return this.dtCanceltPortlddField;
         }
         set
         {
            this.dtCanceltPortlddField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC900.xsd")]
   public partial class SISARQComplexType
   {

      private object itemField;

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute("ACTC900", typeof(ACTC900ComplexType))]
      [System.Xml.Serialization.XmlElementAttribute("ACTC900RET", typeof(ACTC900RETComplexType))]
      public object Item
      {
         get
         {
            return this.itemField;
         }
         set
         {
            this.itemField = value;
         }
      }
   }
}
