//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace FastConsig.CTC.Model.ACTC928 {
   using FastConsig.CTC.Model.Interfaces;
   using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC928.xsd")]
    [System.Xml.Serialization.XmlRootAttribute("ACTCDOC", Namespace="http://www.cip-bancos.org.br/ARQ/ACTC928.xsd", IsNullable=false)]
    public partial class ACTC928 : IACTC
   {
        
        private BCARQComplexType bCARQField;
        
        private SISARQComplexType sISARQField;
        
        private string eSTARQField;
        
        /// <remarks/>
        public BCARQComplexType BCARQ {
            get {
                return this.bCARQField;
            }
            set {
                this.bCARQField = value;
            }
        }
        
        /// <remarks/>
        public SISARQComplexType SISARQ {
            get {
                return this.sISARQField;
            }
            set {
                this.sISARQField = value;
            }
        }
        
        /// <remarks/>
        public string ESTARQ {
            get {
                return this.eSTARQField;
            }
            set {
                this.eSTARQField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC928.xsd")]
    public partial class BCARQComplexType {
        
        private string nomArqField;
        
        private string numCtrlEmisField;
        
        private string numCtrlDestOrField;
        
        private string iSPBEmissorField;
        
        private string iSPBDestinatarioField;
        
        private System.DateTime dtHrArqField;
        
        private string sitReqField;
        
        private Grupo_SeqComplexType grupo_SeqField;
        
        private System.DateTime dtRefField;
        
        /// <remarks/>
        public string NomArq {
            get {
                return this.nomArqField;
            }
            set {
                this.nomArqField = value;
            }
        }
        
        /// <remarks/>
        public string NumCtrlEmis {
            get {
                return this.numCtrlEmisField;
            }
            set {
                this.numCtrlEmisField = value;
            }
        }
        
        /// <remarks/>
        public string NumCtrlDestOr {
            get {
                return this.numCtrlDestOrField;
            }
            set {
                this.numCtrlDestOrField = value;
            }
        }
        
        /// <remarks/>
        public string ISPBEmissor {
            get {
                return this.iSPBEmissorField;
            }
            set {
                this.iSPBEmissorField = value;
            }
        }
        
        /// <remarks/>
        public string ISPBDestinatario {
            get {
                return this.iSPBDestinatarioField;
            }
            set {
                this.iSPBDestinatarioField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DtHrArq {
            get {
                return this.dtHrArqField;
            }
            set {
                this.dtHrArqField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string SitReq {
            get {
                return this.sitReqField;
            }
            set {
                this.sitReqField = value;
            }
        }
        
        /// <remarks/>
        public Grupo_SeqComplexType Grupo_Seq {
            get {
                return this.grupo_SeqField;
            }
            set {
                this.grupo_SeqField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime DtRef {
            get {
                return this.dtRefField;
            }
            set {
                this.dtRefField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC928.xsd")]
    public partial class Grupo_SeqComplexType {
        
        private string numSeqField;
        
        private Indr indrContField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string NumSeq {
            get {
                return this.numSeqField;
            }
            set {
                this.numSeqField = value;
            }
        }
        
        /// <remarks/>
        public Indr IndrCont {
            get {
                return this.indrContField;
            }
            set {
                this.indrContField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC928.xsd")]
    public enum Indr {
        
        /// <remarks/>
        S,
        
        /// <remarks/>
        N,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC928.xsd")]
    public partial class Grupo_ACTC928_Produto_ComplexType {
        
        private string descricaoProdutoField;
        
        /// <remarks/>
        public string DescricaoProduto {
            get {
                return this.descricaoProdutoField;
            }
            set {
                this.descricaoProdutoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC928.xsd")]
    public partial class Grupo_ACTC928_RelatorioParticipantes_ComplexType {
        
        private string nomeCliField;
        
        private string cnpjCliField;
        
        private string iSPBCliField;
        
        private Grupo_ACTC928_Produto_ComplexType[] grupo_ACTC928_ProdutoField;
        
        /// <remarks/>
        public string NomeCli {
            get {
                return this.nomeCliField;
            }
            set {
                this.nomeCliField = value;
            }
        }
        
        /// <remarks/>
        public string CnpjCli {
            get {
                return this.cnpjCliField;
            }
            set {
                this.cnpjCliField = value;
            }
        }
        
        /// <remarks/>
        public string ISPBCli {
            get {
                return this.iSPBCliField;
            }
            set {
                this.iSPBCliField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Grupo_ACTC928_Produto")]
        public Grupo_ACTC928_Produto_ComplexType[] Grupo_ACTC928_Produto {
            get {
                return this.grupo_ACTC928_ProdutoField;
            }
            set {
                this.grupo_ACTC928_ProdutoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC928.xsd")]
    public partial class ACTC928ComplexType {
        
        private string numCtrlCIPField;
        
        private Grupo_ACTC928_RelatorioParticipantes_ComplexType[] grupo_ACTC928_Grupo_ClienteField;
        
        /// <remarks/>
        public string NumCtrlCIP {
            get {
                return this.numCtrlCIPField;
            }
            set {
                this.numCtrlCIPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Grupo_ACTC928_Grupo_Cliente")]
        public Grupo_ACTC928_RelatorioParticipantes_ComplexType[] Grupo_ACTC928_Grupo_Cliente {
            get {
                return this.grupo_ACTC928_Grupo_ClienteField;
            }
            set {
                this.grupo_ACTC928_Grupo_ClienteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cip-bancos.org.br/ARQ/ACTC928.xsd")]
    public partial class SISARQComplexType {
        
        private ACTC928ComplexType itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ACTC928")]
        public ACTC928ComplexType Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
}
