CREATE TABLE FastConsig.dbo.CTCCodigoErro (
  Id int IDENTITY,
  Codigo varchar(8) NOT NULL,
  Descricao varchar(max) NOT NULL,
  CONSTRAINT PK_CTCCodigoErro_Id PRIMARY KEY CLUSTERED (Id)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

CREATE UNIQUE INDEX UK_CTCCodigoErro_Codigo
  ON FastConsig.dbo.CTCCodigoErro (Codigo)
  ON [PRIMARY]
GO

SET DATEFORMAT ymd
SET ARITHABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS, XACT_ABORT OFF
GO

SET IDENTITY_INSERT FastConsig.dbo.CTCCodigoErro ON
GO
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (1, 'ECTC0001', 'Portabilidade não encontrada')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (2, 'ECTC0002', 'Portabilidade não permitida, solicitante é o originador do contrato')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (3, 'ECTC0003', 'Valor duplicado')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (4, 'ECTC0004', 'Cliente Nuclea Principal não aderiu à funcionalidade')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (5, 'ECTC0005', 'Cliente Nuclea Administrado não aderiu à funcionalidade')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (6, 'ECTC0006', 'Cliente Nuclea Principal não aderiu à funcionalidade ACTCX02')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (7, 'ECTC0007', 'Cliente Nuclea Administrado não aderiu a funcionalidade ACTCX02')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (8, 'ECTC0008', 'Cliente Nuclea Principal não aderiu a funcionalidade ACTCX03')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (9, 'ECTC0009', 'Cliente Nuclea Administrado não aderiu a funcionalidade ACTCX03')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (10, 'ECTC0010', 'Cliente Nuclea Principal não aderiu a funcionalidade ACTCX04')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (11, 'ECTC0011', 'Cliente Nuclea Administrado não aderiu a funcionalidade ACTCX04')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (12, 'ECTC0012', 'Data de referência inválida')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (13, 'ECTC0013', 'Para Fluxo de Pagamento Irregular é obrigatório a informação da repetição das parcelas irregulares')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (14, 'ECTC0014', 'Data deve ser maior ou igual à data atual')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (15, 'ECTC0015', 'Falta informação de Data de Referência para saldo devedor contábil')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (16, 'ECTC0016', 'Data de referência para saldo devedor contábil não solicitada na requisição da portabilidade pela Instituição Interessada')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (17, 'ECTC0017', 'Grupo não deve ser informado para Fluxo de Pagamento Normal')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (18, 'ECTC0018', 'CNPJ inválido')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (19, 'ECTC0019', 'Arquivo fora de Grade Horária')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (20, 'ECTC0020', '.')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (21, 'ECTC0021', 'Data de referência menor que a Data Hora do Arquivo')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (22, 'ECTC0022', 'Instituição não Cliente Nuclea do CTC ')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (23, 'ECTC0023', 'Contrato com portabilidade em andamento')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (24, 'ECTC0024', 'Número do contrato no CTC inválido ou não encontrado ')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (25, 'ECTC0025', 'Data deve ser maior que a data de referência do sistema')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (26, 'ECTC0026', 'Data de vencimento da última parcela do contrato menor que data da contratação')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (27, 'ECTC0027', 'Data do saldo devedor incompatível com a data da liquidação da portabilidade')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (28, 'ECTC0028', 'Portabilidade já finalizada para o contrato informado')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (29, 'ECTC0029', 'Data de retenção deve ser maior ou igual que a data de solicitação da portabilidade que está sendo retida e menor ou igual que a data atual do sistema.')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (30, 'ECTC0030', '.')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (31, 'ECTC0031', 'Nome de Arquivo duplicado')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (32, 'ECTC0032', 'Contrato não encontrado')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (33, 'ECTC0033', 'Data de retenção do contrato deve ser informada para este status de portabilidade')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (34, 'ECTC0034', 'Cliente não pertencente ao contrato ')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (35, 'ECTC0035', 'Cliente repetido')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (36, 'ECTC0036', 'Cliente Nuclea Administrado não é administrado pelo Cliente Nuclea Principal')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (37, 'ECTC0038', 'Valor deve ser maior que zero')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (38, 'ECTC0039', 'Um mesmo contrato não pode ser repetido no arquivo')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (39, 'ECTC0040', 'Portabilidade não enviada para Instituição que está respondendo')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (40, 'ECTC0041', 'Portabilidade já respondida')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (41, 'ECTC0042', 'Portabilidade cancelada')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (42, 'ECTC0043', 'Motivo de cancelamento inválido para o participante')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (43, 'ECTC0044', 'Portabilidade finalizada')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (44, 'ECTC0045', 'Motivo de retenção inválido para este tipo de produto')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (45, 'ECTC0046', 'Motivo informado apenas pelo CTC')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (46, 'ECTC0047', 'Falta informação de Cliente')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (47, 'ECTC0048', 'Valor do IOF deve ser informado para o enquadramento "SFH – Carteira Hipotecária Comercial" ou "Outros"')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (48, 'ECTC0049', 'Tipo de pessoa não permitido para portabilidade')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (49, 'ECTC0050', 'Data não é dia útil')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (50, 'ECTC0051', 'Data deve ser maior que a Data de Contratação da Operação')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (51, 'ECTC0052', 'Data de vencimento não corresponde à quantidade de parcelas do contrato')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (52, 'ECTC0053', 'UF inválida')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (53, 'ECTC0054', 'Código do contrato original diferente da proposta')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (54, 'ECTC0055', 'CNPJ base da credora original diferente da proposta')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (55, 'ECTC0056', 'Data deve ser maior que a data de contratação da operação')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (56, 'ECTC0057', 'Data deve ser maior que a data de vencimento da primeira parcela')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (57, 'ECTC0058', 'Portabilidade não pode ser cancelada')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (58, 'ECTC0059', 'Data deve ser igual à data atual')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (59, 'ECTC0060', 'Portabilidade não pode ser liquidada')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (60, 'ECTC0061', 'Devem ser informadas três datas distintas')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (61, 'ECTC0062', 'Data de referência do cálculo do saldo devedor fora do prazo permitido')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (62, 'ECTC0063', 'Data de referência do cálculo do saldo devedor diferente da proposta')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (63, 'ECTC0064', 'Data de contratação deve ser menor que a data de referência')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (64, 'ECTC0065', 'Para Fluxo de Pagamento Normal é obrigatório a informação do Grupo Parcela Normal')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (65, 'ECTC0066', 'Para Fluxo de Pagamento Ambos é obrigatório a informação dos grupos Parcelas Normal e Parcela Irregular')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (66, 'ECTC0067', 'Grupo não deve ser informado para Fluxo de Pagamento Irregular')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (67, 'ECTC0068', 'Data deve ser menor ou igual à data atual')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (68, 'ECTC0069', 'Índice de remuneração deve ser informado para tipo de taxa pós-fixada')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (69, 'ECTC0070', 'Quantidade total de parcelas vencidas não pode ser maior que a quantidade total de parcelas do contrato')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (70, 'ECTC0071', 'Quantidade total de parcelas a vencer não pode ser maior que a quantidade total de parcelas do contrato')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (71, 'ECTC0072', 'Quantidade total de parcelas a vencer somada com a quantidade total de parcelas vencidas deve menor ou igual a quantidade total de parcelas do contrato')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (72, 'ECTC0073', 'Campo obrigatório para o tipo de contrato imobiliário (“0901” ou “0902” ou “0903”) não informado: Valor parcela amortização inicial, Valor parcela juros inicial, Prêmio MIP Inicial, Prêmio DFI Inicial, Tarifa Mensal Inicial, Custo Efetivo Seguro Habitacional, Valor Avaliação DFI para Proposta ou Prazo Operação (em meses)')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (73, 'ECTC0074', 'Valor parcela inicial (zero) deve ser igual ao somatório dos seguintes valores: Valor parcela amortização inicial (zero) + Valor parcela juros inicial (zero) + Prêmio MIP Inicial (zero) + Prêmio DFI Inicial (zero) + Tarifa Mensal Inicial (zero)')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (74, 'ECTC0075', 'CPF do titular deve ser informado para o motivo de retenção')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (75, 'ECTC0076', 'Nenhuma condição divergente informada')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (76, 'ECTC0077', 'Tipo do contrato original não informado')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (77, 'ECTC0078', 'Campo obrigatório para o tipo de contrato imobiliário (“0211” ou “0299”) não informado: Valor parcela amortização inicial (zero) ou Valor parcela juros inicial (zero).')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (78, 'ECTC0079', 'Formatação do código do contrato inválida. Não são permitidos espaços em branco nem caracteres especiais (“-“, “.” ou “/” ....).')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (79, 'ECTC0080', 'Tamanho inválido')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (80, 'ECTC0081', 'Indicador de uso FGTS PPP deve ser informado para enquadramento igual a “01-SFH âmbitos”')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (81, 'ECTC0082', 'Valor obrigatório para indicador de Uso FGTS igual a “Sim”')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (82, 'ECTC0083', 'Data deve ser maior ou igual que a data da última STR registrada')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (83, 'ECTC0084', 'Tipo de contrato diferente do registrado no DNA da proposta')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (84, 'ECTC0085', 'Portabilidade não permitida. Contrato com portabilidade em situação de “Decurso de prazo por não efetivação da portabilidade”')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (85, 'ECTC0086', 'Lista CNPJCes deve ser informada para motivo de retenção igual a “013-Contrato cedido sem coobrigação”')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (86, 'ECTC0087', 'A data inicial de apuração deve ser menor que a data final de apuração.')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (87, 'ECTC0088', 'Intervalo máximo de pesquisa excedeu o limite permitido. Limite padrão 30 dias.')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (88, 'ECTC0089', 'A data final de apuração é obrigatória se a data inicial de apuração for informada')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (89, 'ECTC0090', 'A data inicial de apuração é obrigatória se a data final de apuração for informada')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (90, 'ECTC0091', 'Pelo menos um filtro de pesquisa deve ser informado. Data de referência ou intervalo de datas de inicial e final de apuração.')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (91, 'ECTC0092', 'Cliente Nuclea principal diferente do emissor do arquivo')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (92, 'ECTC0093', 'Somente o Cliente Nuclea principal pode solicitar a lista de arquivos processados')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (93, 'ECTC0094', 'Número de controle da IF deve ser único')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (94, 'ECTC0095', 'Ano Mês referência informado fora do prazo permitido')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (95, 'ECTC0096', 'Data informada não permitida ')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (96, 'ECTC0097', 'Tipo de Contrato informado não permitido para o Tipo de Ente Consignante')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (97, 'ECTC0098', 'ISPB informado diferente do solicitante do arquivo')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (98, 'ECTC0099', 'Cliente Nuclea Administrado não aderiu à funcionalidade de retorno de relatório')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (99, 'ECTC0100', 'Data de vencimento da última parcela deve ser igual a data de vencimento da primeira parcela')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (100, 'ECTC0101', 'Tipo de Contrato não permitido para o tipo de enquadramento informado')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (101, 'ECTC0102', 'Campo Agência do Cliente não deve ser preenchido para o Tipo de Conta informado')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (102, 'ECTC0103', 'Campo Conta Corrente do Cliente não deve ser preenchido para o Tipo de Conta informado')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (103, 'ECTC0104', 'Campo Conta Pagamento não deve ser preenchido para o Tipo de Conta informado')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (104, 'ECTC0105', 'Campo obrigatório para o tipo de contrato informado')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (105, 'ECTC0106', 'Campo não permitido para o tipo de contrato informado')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (106, 'ECTC0107', 'Campo Conta Corrente do Cliente é obrigatório para o Tipo de Conta informado')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (107, 'ECTC0108', 'Campo Conta Pagamento é obrigatório para o Tipo de Conta informado')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (108, 'ECTC0109', 'Valor deve ser maior ou igual a zero')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (109, 'ECTC0110', 'Tipo de conta não permitido para portabilidade')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (110, 'ECTC0111', 'Data informada deve ser menor ou igual a data de referência do sistema e maior ou igual a data de referência do sistema menos a quantidade de dias úteis definida')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (111, 'ECTC0112', 'Conteúdo não permitido para o tipo de contrato informado')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (112, 'ECTC0113', 'Não é permitido efetuar a troca de modalidade para o mesmo produto')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (113, 'ECTC0114', 'Campo Agência do Cliente é obrigatório para o Tipo de Conta informado')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (114, 'ECTC0115', 'Campos Agência e Conta Corrente do Cliente são obrigatórios para o Tipo de Conta informado')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (115, 'ECTC0116', 'Motivo de cancelamento inválido para este tipo de produto')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (116, 'ECTC0117', 'É permitido informar somente uma data para este tipo de contrato')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (117, 'ECTC0118', 'É permitido informar somente um valor para este tipo de contrato')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (118, 'ECTC0119', 'Obrigatório informar três valores para quando o tipo de contrato vigente ou da proposta for imobiliário')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (119, 'ECTC0120', 'Grupo_ACTCx03_ParclNorml obrigatório para o tipo de contrato informado')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (120, 'ECTC0121', 'Grupo_ACTCx01_EndImovel obrigatório para o tipo de contrato informado')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (121, 'ECTC0122', 'Campo DtRefCalcSaldDevdr obrigatório para o tipo de contrato informado')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (122, 'ECTC0123', 'Campo OrigemRec obrigatório para o tipo de contrato informado')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (123, 'ECTC0124', 'Campo TpTx obrigatório para o tipo de contrato informado')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (124, 'ECTC0125', 'Campo Valor Face Parcela Contrato (VlrFaceParclContrto) obrigatório para o tipo de contrato informado')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (125, 'ECTC0126', 'Campo Tarifa do Cheque Especial (TarCheqEspcl) obrigatório para o tipo de contrato informado')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (126, 'ECTC0127', 'Campo Quantidade Dias de Isenção (QtdDiasIsen) obrigatório para o tipo de contrato informado')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (127, 'ECTC0128', 'Campo Prazo Operação (PrzOp) obrigatório para o tipo de contrato informado')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (128, 'ECTC0129', 'Campo Data de Contratação da Operação (DtContrOp) obrigatório para o tipo de contrato informado')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (129, 'ECTC0130', 'Campo Tipo Ente Consignante (TpEnteCons) obrigatório para o tipo de contrato informado')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (130, 'ECTC0131', 'Campo CNPJ Correspondente Bancário (CNPJCorrespBanc) obrigatório para o tipo de contrato informado')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (131, 'ECTC0132', 'Campo Tipo de Conta (TpCt) obrigatório para o tipo de contrato informado')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (132, 'ECTC0133', 'Campo Conta Conjunta ou Solidária (CtConjtaSoldria) obrigatório para o tipo de contrato informado')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (133, 'ECTC0134', 'Campo Regime Amortização (RegmAmtzc) obrigatório para o tipo de contrato informado')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (134, 'ECTC0135', 'Campo Quantidade Total Parcelas Contrato (QtdTotParclContrto) obrigatório para o tipo de contrato informado')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (135, 'ECTC0136', 'Campo Fluxo de Pagamento (FlxPagto) obrigatório para o tipo de contrato informado')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (136, 'ECTC0137', 'Campo Valor Parcela Inicial (zero) (VlrParclInial) obrigatório para o tipo de contrato informado')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (137, 'ECTC0138', 'Campo Valor Máximo de Cobertura (VlrMaxCob) obrigatório para o tipo de contrato informado')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (138, 'ECTC0139', 'Campo Taxa de Juros Nominal (TxJurosNoml) obrigatório para o tipo de contrato informado')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (139, 'ECTC0140', 'Campo Taxa CET (TxCET) obrigatório para o tipo de contrato informado')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (140, 'ECTC0141', 'Campo Qtd. Total Parcelas a Vencer e Não Pagas (QtdTotParclContrtoVencr) obrigatório para o tipo de contrato informado')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (141, 'ECTC0142', 'Campo Data da Última Parcela Paga (DtUltParclPaga) obrigatório para o tipo de contrato informado')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (142, 'ECTC0143', 'Campo Data da Última Parcela Vencida (DtUltParclVencd) obrigatório para o tipo de contrato informado')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (143, 'ECTC0144', 'Campo Valor da Última Parcela Vencida (VlrUltParclVencd) obrigatório para o tipo de contrato informado')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (144, 'ECTC0145', 'Campo Data Vencimento Última Parcela (DtVencUltParcl) obrigatório para o tipo de contrato informado')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (145, 'ECTC0146', 'Campo Valor Tarifa Mensal Atual (VlrTarMesAtl) obrigatório para o tipo de contrato informado')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (146, 'ECTC0147', 'Campo Enquadramento Contrato (EnqdmntContrto) obrigatório para o tipo de contrato informado')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (147, 'ECTC0148', 'Campo Prazo Remanescente Contrato (PrzRemnstContrto) obrigatório para o tipo de contrato informado')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (148, 'ECTC0149', 'Campo Situação do Contrato (SitContrto) obrigatório para o tipo de contrato informado')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (149, 'ECTC0150', 'Campo Quantidade de Dias em Atraso (QtdDiasAtr) obrigatório para o tipo de contrato informado')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (150, 'ECTC0151', 'Tipo de Contrato diferente do Tipo de Contrato enviado na proposta')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (151, 'ECTC0152', 'Formatação do Código de Contrato SCR inválida. Não são permitidos espaços em branco nem caracteres especiais (“-“, “.” ou “/” ....).')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (152, 'ECTC0153', 'Número Portabilidade CTC não pertence ao Tipo de Contrato')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (153, 'ECTC0154', 'Data deve ser maior ou igual a Data de Contratação da Operação')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (154, 'ECTC0155', 'Campo Agência Bancária IF Credora Original (AgBancIFOrigdr) obrigatório para o tipo de contrato informado')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (155, 'ECTC0156', 'Troca de modalidade não permitida entre produtos de Pessoa Física e Pessoa Jurídica')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (156, 'ECTC0157', 'Campo Data Liberação Valores Operação Contrato Original (DtLibVlrOperContrtoOrig) obrigatório para o tipo de contrato informado')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (157, 'ECTC0158', 'Campo Percentual Juros Pré Parcela Normal (PercJurPreParclNorml) obrigatório para o tipo de contrato informado')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (158, 'ECTC0159', 'Campo Percentual Juros Pós Parcela Normal (PercJurPosParclNorml) obrigatório para o tipo de contrato informado')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (159, 'ECTC0160', 'Campo Valor Juros PMT Parcela Irregular (VlrJurParclIrreglr) obrigatório para o tipo de contrato informado')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (160, 'ECTC0161', 'Campo IOF Básico Cobrado na Parcela Irregular (IOFRecParclIrreglr) obrigatório para o tipo de contrato informado')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (161, 'ECTC0162', 'Não é permitido mais de um Cliente com o mesmo CPF')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (162, 'ECTC0163', 'Formatação do IPOC inválida. Não é permitido informar somente espaços em branco')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (163, 'ECTC0164', 'Tipo de Contrato Proposta deve ser igual ao Tipo de Contrato')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (164, 'ECTC0165', 'Formatação do Código de Contrato Original inválida. Não é permitido informar todos os caracteres iguais')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (165, 'ECTC0166', 'Campo Data Digitação Proposta Correspondente Bancário (DtDigPropPortlddCorrespBanc) obrigatório quando o CNPJ do Correspondente Bancário for diferente da IF Proponente')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (166, 'ECTC0167', 'Campo Valor Máximo de Cobertura (VlrMaxCob) deve ser maior ou igual ao valor informado no campo “Valor Saldo Devedor Contábil para Proposta”')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (167, 'ECTC0168', 'Campo Valor Máximo de Cobertura (VlrMaxCob) deve ser maior ou igual a soma dos campos “Valor Saldo Devedor Contábil para Proposta” e “Valor Saldo Devedor Contábil para Proposta AD”')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (168, 'ECTC0169', 'Campo Índice de Remuneração (IndRemun) obrigatório para o Tipo de Taxa informado')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (169, 'ECTC0170', 'Tipo de Taxa (Tptx) não permitida para o produto informado')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (170, 'ECTC0171', 'Campo Percentual Juros Pré Parcela Normal (PercJurPreParclNorml) obrigatório para o Tipo de Taxa informado')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (171, 'ECTC0172', 'Campo Percentual Juros Pós Parcela Normal (PercJurPosParclNorml) obrigatório para o Tipo de Taxa informado')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (172, 'ECTC0173', 'Campos Percentual Juros Pré e Pós Parcela Normal (PercJurPreParclNorml /PercJurPosParclNorml) obrigatórios para o Tipo de Taxa informado')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (173, 'ECTC0174', 'Valor obrigatório para Indicador de Autorização da Troca de Garantia (Ind_AutTrocaGarantia) igual a “Sim”')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (174, 'ECTC0175', 'Campo Indicador de Autorização da Troca de Garantia (Ind_AutTrocaGarantia) obrigatório para o PRONAMPE')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (175, 'ECTC0176', 'Campo informado permitido apenas para o PRONAMPE')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (176, 'ECTC0177', 'Valor obrigatório para Tipo de Taxa (TpTx) igual a “Ambas”')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (177, 'ECTC0178', 'A portabilidade deve ser respondida através da série de arquivo em que foi solicitada')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (178, 'ECTC0179', 'A situação da portabilidade não permite o envio do arquivo ACTC855')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (179, 'ECTC0180', 'O número da portabilidade não pertence ao proponente ')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (180, 'ECTC0181', 'Falha de comunicação com o FGO. Tente novamente!')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (181, 'ECTC0182', 'Formatação inválida: espaços em branco não são permitidos')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (182, 'ECTC0183', 'Conteúdo inválido: não é permitido informar apenas zeros')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (183, 'ECTC0184', 'Fluxo de pagamento irregular não permitido')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (184, 'ECTC0185', 'A pré-reserva já está efetivada')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (185, 'ECTC0186', 'Faixa de RCO fora do período de vigência')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (186, 'ECTC0187', 'CNPJ do Cessionário não permite portabilidade')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (187, 'ECTC9998', 'Erro inesperado – FGO')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (188, 'ECTC9999', 'Erro inesperado')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (189, 'EGEN0001', 'XML Mal Formado')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (190, 'EGEN0002', 'BCMSG Ausente')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (191, 'EGEN0003', 'SISMSG Ausente')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (192, 'EGEN0004', 'ISPB Emissor Não Informado')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (193, 'EGEN0005', 'ISPB Emissor Inválido')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (194, 'EGEN0006', 'ISPB Emissor Não Autorizado ao CODMSG Solicitado')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (195, 'EGEN0007', 'ISPB Emissor Não Autorizado para a Fila Requerida')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (196, 'EGEN0008', 'ISPB Destinatário Não Informado')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (197, 'EGEN0009', 'ISPB Destinatário Não Confere com Destino')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (198, 'EGEN0010', 'NuOP Não Informado')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (199, 'EGEN0011', 'NuOP já registrado')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (200, 'EGEN0012', 'NuOP Não Confere com ISPB')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (201, 'EGEN0013', 'NuOP Inválido')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (202, 'EGEN0014', 'CODMSG Não Informado')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (203, 'EGEN0015', 'CODMSG Inexistente')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (204, 'EGEN0016', 'Erro na Conversão do Código')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (205, 'EGEN0017', 'XML Inválido. Campo Obrigatório Ausente')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (206, 'EGEN0018', 'XML Inválido. Campo Não Faz Parte da Mensagem')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (207, 'EGEN0019', 'Tipo ID Emissor Ausente/Inválido')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (208, 'EGEN0020', 'Tipo ID Destinatário Ausente/Inválido')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (209, 'EGEN0021', 'ISPB Emissora em Contingência')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (210, 'EGEN0022', 'Campo Obrigatório Não Informado')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (211, 'EGEN0023', 'Conteúdo Inválido')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (212, 'EGEN0024', 'Informe NumCtrlSTR ou NUOp')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (213, 'EGEN0025', 'NUOp Referente ao NumCtrlSTR Incompatível com o NUOp Informado')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (214, 'EGEN0026', 'NUOp Não Encontrado')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (215, 'EGEN0027', 'Mensagem Não Encontrada')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (216, 'EGEN0028', 'Tipo de Retorno Inválido')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (217, 'EGEN0029', 'Nome do Arquivo Não Tratado pelo Destinatário')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (218, 'EGEN0030', 'Nome do Arquivo Inválido')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (219, 'EGEN0031', 'Identificador do Arquivo Inválido')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (220, 'EGEN0032', 'Recepção de Arquivo Fora do Horário')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (221, 'EGEN0033', 'Tipo de Transmissão Inválido')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (222, 'EGEN0034', 'XML Inválido. Formato deve ser Unicode UTF-16 BE')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (223, 'EGEN0035', '"Namespace" inválido.')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (224, 'EGEN0036', 'Domínio de Sistema Inválido.')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (225, 'EGEN0037', 'Formato inválido de arquivo ZIP')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (226, 'EGEN0038', 'Erro na continuação da mensagem. Última mensagem na sequência não é a final')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (227, 'EGEN0039', 'Erro na continuação da mensagem. Não houve recebimento de mensagem final')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (228, 'EGEN0040', 'Erro na continuação da mensagem. Parte fixa da mensagem de continuação difere da primeira mensagem')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (229, 'EGEN0041', 'Cliente Nuclea Não Está em Contingência Integral')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (230, 'EGEN0042', 'Existe Outro Arquivo Pendente de Confirmação/Cancelamento na Data-Movimento')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (231, 'EGEN0043', 'XML Inválido - Não Está de Acordo com a Definição do XSD')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (232, 'EGEN0044', 'Mensagem Não Admite Segmentação')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (233, 'EGEN0045', 'Número de Sequência da Mensagem Inválido')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (234, 'EGEN0046', 'Existe Outro Arquivo em Validação na Data-Movimento')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (235, 'EGEN0047', 'Indicador Continuidade Inválido')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (236, 'EGEN0048', 'Erro na continuação da mensagem. Existe segmento rejeitado da mensagem.')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (237, 'EGEN0049', 'Quantidade de Repetição Inválida')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (238, 'EGEN0050', 'Erro de Processamento')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (239, 'EGEN0051', 'ISPB Emissor Não Autorizado à Requisição do Arquivo')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (240, 'EGEN0052', 'ISPB Emissor Não Autorizado ao Envio do Arquivo')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (241, 'EGEN0053', 'CPF duplicado')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (242, 'EGEN0054', 'Tipo de Responsável inválido')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (243, 'EGEN0055', 'Quantidades de Tipos de Responsáveis inválidas')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (244, 'EGEN0056', 'Tipo de Responsável duplicado')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (245, 'EGEN0057', 'CPF inválido')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (246, 'EGEN0058', 'Número de telefone inválido')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (247, 'EGEN0059', 'Endereço eletrônico inválido')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (248, 'EGEN0079', 'Formato do Dado Inválido')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (249, 'EGEN0080', 'Tamanho do Dado Inválido')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (250, 'EGEN0081', 'Tamanho do Bloco BCMSG+SISMSG Inválido')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (251, 'EGEN0082', 'Tamanho do USERMSG Inválido')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (252, 'EGEN0083', 'USERMSG Ausente')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (253, 'EGEN0084', 'BCMSG Inválido')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (254, 'EGEN0085', 'Tamanho de mensagem inválido')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (255, 'EGEN0086', 'Tamanho do SISMSG inválido')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (256, 'EGEN0152', 'Cliente Nuclea em Contingência')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (257, 'EGEN0153', 'ISPB Emissor Incompatível com ISPB Informado')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (258, 'EGEN0154', 'Mensagem Indisponível')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (259, 'EGEN0155', 'Mensagem Não Processável pelo Recebedor')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (260, 'EGEN0300', 'Mensagem Fora do Horário')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (261, 'EGEN1001', 'ISPB Inválido')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (262, 'EGEN1002', 'ISPB Não Informado')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (263, 'EGEN1003', 'Código da Certificadora ou Número do Certificado a Inativar Não Informado')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (264, 'EGEN1004', 'Código do Certificado a Ativar Igual a Zeros')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (265, 'EGEN1005', 'Código do Certificado a Ativar Não Informado')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (266, 'EGEN1006', 'Situação do Certificado Não Informada')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (267, 'EGEN1007', 'Situação do Certificado Inválida')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (268, 'EGEN1009', 'Data Movimento Inválida')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (269, 'EGEN1010', 'Data Movimento Diferente da Data de Processamento')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (270, 'EGEN1011', 'Certificado/Cartório Não Ativo')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (271, 'EGEN1013', 'Código da Certificadora do Certificado a Inativar Não Informado')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (272, 'EGEN1014', 'Certificado a Inativar Não Informado')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (273, 'EGEN1015', 'Ativando um Certificado sem desativar o que está ativo')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (274, 'EGEN1016', 'Data de Validade do Certif. a Ativar Menor que a Data Corrente')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (275, 'EGEN1017', 'Certificado inválido')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (276, 'EGEN1018', 'Não é permitido ativar o certificado antes da data estabelecida')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (277, 'EGEN1055', 'Campos da Repetição Fora da Sequência ou Não Existe Tag de Grupo')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (278, 'EGEN1101', 'Valor Não Informado')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (279, 'EGEN1102', 'Valor Inválido')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (280, 'EGEN1103', 'Chave de Segurança Não Informada')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (281, 'EGEN1104', 'Chave de Segurança Inválida')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (282, 'EGEN1105', 'Tabelas de Contingência Indisponíveis')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (283, 'EGEN1106', 'Números Randômicos Esgotados')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (284, 'EGEN1107', 'Data Movimento Não Informada')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (285, 'EGEN9901', 'Tamanho do Cabeçalho de Segurança Zerado ou Incompatível c/os Possíveis')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (286, 'EGEN9902', 'Versão Inválida ou Incompatível com o Tamanho e/ou Conexão')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (287, 'EGEN9903', 'Algoritmo da Chave do Destinatário Inválido ou Divergente do Certificado')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (288, 'EGEN9904', 'Algoritmo Simétrico Inválido')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (289, 'EGEN9905', 'Algoritmo da Chave de Assinatura Inválido ou Divergente do Certificado')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (290, 'EGEN9906', 'Algoritmo de "Hash" Não Corresponde aos Indicados')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (291, 'EGEN9907', 'Código da AC do Certificado do Destinatário Inválido')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (292, 'EGEN9908', 'Número de Série do Certificado Destino Inválido (Não Foi Emitido pela AC)')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (293, 'EGEN9909', 'Código da AC do Certificado de Assinatura Inválido')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (294, 'EGEN9910', 'Número Série do Certificado de Assinatura Inválido (Não Foi Emitido p/AC)')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (295, 'EGEN9911', 'Assinatura da Mensagem Inválida ou com Erro')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (296, 'EGEN9912', 'Certificado Não é do Emissor da Mensagem (Titular da Fila no MQ)')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (297, 'EGEN9913', 'Erro na Extração da Chave Simétrica')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (298, 'EGEN9914', 'Erro Gerado pelo Algoritmo Simétrico')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (299, 'EGEN9915', 'Tamanho da Mensagem Não Múltiplo de 8 Bytes')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (300, 'EGEN9916', 'Certificado Usado Não Está Ativado')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (301, 'EGEN9917', 'Certificado Usado Está Revogado, Vencido ou Excluído pela Instituição')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (302, 'EGEN9918', 'Erro Genérico da Camada de Segurança')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (303, 'EGEN9919', 'Indicação de Uso Específico Inválida ou Incompatível')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (304, 'EGEN9920', 'Certificado Inválido (usar certificado "a ativar" na GEN0006)')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (305, 'ECTC0207', 'Data de liberação do novo recurso precisa ser dia útil.')
INSERT FastConsig.dbo.CTCCodigoErro(Id, Codigo, Descricao) VALUES (306, 'ECTC0208', 'Data de liberação do novo recurso deve ser maior ou igual data da contratação da operação.')
GO
SET IDENTITY_INSERT FastConsig.dbo.CTCCodigoErro OFF
GO