CREATE TABLE FastConsig.dbo.CTCTipoPessoa (
  Id int IDENTITY,
  Codigo varchar(1) NOT NULL,
  Descricao varchar(50) NOT NULL,
  CONSTRAINT PK_CTCTipoPessoa_Id PRIMARY KEY CLUSTERED (Id),
  CONSTRAINT KEY_CTCTipoPessoa_Codigo UNIQUE (Codigo)
)
ON [PRIMARY]
GO

CREATE INDEX IDX_CTCTipoPessoa_Codigo
  ON FastConsig.dbo.CTCTipoPessoa (Codigo)
  ON [PRIMARY]
GO

SET DATEFORMAT ymd
SET ARITHABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS, XACT_ABORT OFF
GO

SET IDENTITY_INSERT FastConsig.dbo.CTCTipoPessoa ON
GO
INSERT FastConsig.dbo.CTCTipoPessoa(Id, Codigo, Descricao) VALUES (1, 'F', 'Pessoa Física')
INSERT FastConsig.dbo.CTCTipoPessoa(Id, Codigo, Descricao) VALUES (2, 'J', 'Pessoa Jurídica')
GO
SET IDENTITY_INSERT FastConsig.dbo.CTCTipoPessoa OFF
GO