CREATE TABLE FastConsig.dbo.CTCTipoArquivo (
  Id int IDENTITY,
  Codigo varchar(1) NOT NULL,
  Descricao varchar(50) NOT NULL,
  CONSTRAINT PK_CTCTipoArquivo_Id PRIMARY KEY CLUSTERED (Id)
)
ON [PRIMARY]
GO

CREATE UNIQUE INDEX UK_CTCTipoArquivo_Codigo
  ON FastConsig.dbo.CTCTipoArquivo (Codigo)
  ON [PRIMARY]
GO

SET DATEFORMAT ymd
SET ARITHABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS, XACT_ABORT OFF
GO

SET IDENTITY_INSERT FastConsig.dbo.CTCTipoArquivo ON
GO
INSERT FastConsig.dbo.CTCTipoArquivo(Id, Codigo, Descricao) VALUES (1, '1', 'Entrada')
INSERT FastConsig.dbo.CTCTipoArquivo(Id, Codigo, Descricao) VALUES (2, '2', 'Saída')
GO
SET IDENTITY_INSERT FastConsig.dbo.CTCTipoArquivo OFF
GO