CREATE TABLE FastConsig.dbo.CTCSituacaoArquivo (
  Id int IDENTITY,
  Descricao varchar(50) NOT NULL,
  CONSTRAINT PK_CTCSituacaoArquivo_Id PRIMARY KEY CLUSTERED (Id)
)
ON [PRIMARY]
GO

SET DATEFORMAT ymd
SET ARITHABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS, XACT_ABORT OFF
GO

SET IDENTITY_INSERT FastConsig.dbo.CTCSituacaoArquivo ON
GO
INSERT FastConsig.dbo.CTCSituacaoArquivo(Id, Descricao) VALUES (1, 'Importação')
INSERT FastConsig.dbo.CTCSituacaoArquivo(Id, Descricao) VALUES (2, 'Processamento')
GO
SET IDENTITY_INSERT FastConsig.dbo.CTCSituacaoArquivo OFF
GO