CREATE TABLE FastConsig.dbo.CTCVigenciaFaixasRCO (
  Id int IDENTITY,
  VigenciaInicial date NOT NULL,
  VigenciaFinal date NULL,
  CONSTRAINT PK_CTCVigenciaFaixasRCO_Id PRIMARY KEY CLUSTERED (Id)
)
ON [PRIMARY]
GO

SET DATEFORMAT ymd
SET ARITHABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS, XACT_ABORT OFF
GO

SET IDENTITY_INSERT FastConsig.dbo.CTCVigenciaFaixasRCO ON
GO
INSERT FastConsig.dbo.CTCVigenciaFaixasRCO(Id, VigenciaInicial, VigenciaFinal) VALUES (1, '2023-01-01', NULL)
GO
SET IDENTITY_INSERT FastConsig.dbo.CTCVigenciaFaixasRCO OFF
GO