CREATE TABLE FastConsig.dbo.CTCMotivoRetencaoContrato (
  Id int IDENTITY,
  Codigo varchar(3) NOT NULL,
  Descricao varchar(100) NOT NULL,
  Consignado bit NULL,
  CreditoImobiliario bit NULL,
  CreditoPessoal bit NULL,
  FinancimentoVeiculo bit NULL,
  OutrosCreditos bit NULL,
  ChequeEspecial bit NULL,
  AdiantamentoDepositante bit NULL,
  CapitalGiro bit NULL,
  Pronampe bit NULL,
  CONSTRAINT PK_CTCMotivoRetencaoContrato_Id PRIMARY KEY CLUSTERED (Id)
)
ON [PRIMARY]
GO

CREATE UNIQUE INDEX IDX_CTCMotivoRetencaoContrato_Codigo
  ON FastConsig.dbo.CTCMotivoRetencaoContrato (Codigo)
  ON [PRIMARY]
GO

SET DATEFORMAT ymd
SET ARITHABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS, XACT_ABORT OFF
GO

SET IDENTITY_INSERT FastConsig.dbo.CTCMotivoRetencaoContrato ON
GO
INSERT FastConsig.dbo.CTCMotivoRetencaoContrato(Id, Codigo, Descricao, Consignado, CreditoImobiliario, CreditoPessoal, FinancimentoVeiculo, OutrosCreditos, ChequeEspecial, AdiantamentoDepositante, CapitalGiro, Pronampe) VALUES (1, '1', 'Retenção do Cliente', CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'True'))
INSERT FastConsig.dbo.CTCMotivoRetencaoContrato(Id, Codigo, Descricao, Consignado, CreditoImobiliario, CreditoPessoal, FinancimentoVeiculo, OutrosCreditos, ChequeEspecial, AdiantamentoDepositante, CapitalGiro, Pronampe) VALUES (2, '2', 'Contrato não encontrado ou não é da modalidade especificada', CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'True'))
INSERT FastConsig.dbo.CTCMotivoRetencaoContrato(Id, Codigo, Descricao, Consignado, CreditoImobiliario, CreditoPessoal, FinancimentoVeiculo, OutrosCreditos, ChequeEspecial, AdiantamentoDepositante, CapitalGiro, Pronampe) VALUES (3, '3', 'Tipo de contrato inválido', CONVERT(bit, 'False'), CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), CONVERT(bit, 'True'), CONVERT(bit, 'True'))
INSERT FastConsig.dbo.CTCMotivoRetencaoContrato(Id, Codigo, Descricao, Consignado, CreditoImobiliario, CreditoPessoal, FinancimentoVeiculo, OutrosCreditos, ChequeEspecial, AdiantamentoDepositante, CapitalGiro, Pronampe) VALUES (4, '4', 'Portabilidade em andamento', CONVERT(bit, 'False'), CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), CONVERT(bit, 'False'))
INSERT FastConsig.dbo.CTCMotivoRetencaoContrato(Id, Codigo, Descricao, Consignado, CreditoImobiliario, CreditoPessoal, FinancimentoVeiculo, OutrosCreditos, ChequeEspecial, AdiantamentoDepositante, CapitalGiro, Pronampe) VALUES (5, '5', 'FGTS AMORTIZAR em uso', CONVERT(bit, 'False'), CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), CONVERT(bit, 'False'))
INSERT FastConsig.dbo.CTCMotivoRetencaoContrato(Id, Codigo, Descricao, Consignado, CreditoImobiliario, CreditoPessoal, FinancimentoVeiculo, OutrosCreditos, ChequeEspecial, AdiantamentoDepositante, CapitalGiro, Pronampe) VALUES (6, '6', 'Garantia em Execução', CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'True'))
INSERT FastConsig.dbo.CTCMotivoRetencaoContrato(Id, Codigo, Descricao, Consignado, CreditoImobiliario, CreditoPessoal, FinancimentoVeiculo, OutrosCreditos, ChequeEspecial, AdiantamentoDepositante, CapitalGiro, Pronampe) VALUES (7, '7', 'FGTS funding', CONVERT(bit, 'False'), CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), CONVERT(bit, 'False'))
INSERT FastConsig.dbo.CTCMotivoRetencaoContrato(Id, Codigo, Descricao, Consignado, CreditoImobiliario, CreditoPessoal, FinancimentoVeiculo, OutrosCreditos, ChequeEspecial, AdiantamentoDepositante, CapitalGiro, Pronampe) VALUES (8, '8', 'Contrato cedido', CONVERT(bit, 'False'), CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), CONVERT(bit, 'False'))
INSERT FastConsig.dbo.CTCMotivoRetencaoContrato(Id, Codigo, Descricao, Consignado, CreditoImobiliario, CreditoPessoal, FinancimentoVeiculo, OutrosCreditos, ChequeEspecial, AdiantamentoDepositante, CapitalGiro, Pronampe) VALUES (9, '9', 'CPF/CNPJ não é do contrato', CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'True'))
INSERT FastConsig.dbo.CTCMotivoRetencaoContrato(Id, Codigo, Descricao, Consignado, CreditoImobiliario, CreditoPessoal, FinancimentoVeiculo, OutrosCreditos, ChequeEspecial, AdiantamentoDepositante, CapitalGiro, Pronampe) VALUES (10, '10', 'CPF informado não é o do titular', CONVERT(bit, 'False'), CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), CONVERT(bit, 'False'))
INSERT FastConsig.dbo.CTCMotivoRetencaoContrato(Id, Codigo, Descricao, Consignado, CreditoImobiliario, CreditoPessoal, FinancimentoVeiculo, OutrosCreditos, ChequeEspecial, AdiantamentoDepositante, CapitalGiro, Pronampe) VALUES (11, '11', 'Condições da proposta divergentes do contrato original', CONVERT(bit, 'False'), CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'True'))
INSERT FastConsig.dbo.CTCMotivoRetencaoContrato(Id, Codigo, Descricao, Consignado, CreditoImobiliario, CreditoPessoal, FinancimentoVeiculo, OutrosCreditos, ChequeEspecial, AdiantamentoDepositante, CapitalGiro, Pronampe) VALUES (12, '12', 'Cliente com ação judicial', CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'True'))
INSERT FastConsig.dbo.CTCMotivoRetencaoContrato(Id, Codigo, Descricao, Consignado, CreditoImobiliario, CreditoPessoal, FinancimentoVeiculo, OutrosCreditos, ChequeEspecial, AdiantamentoDepositante, CapitalGiro, Pronampe) VALUES (13, '13', 'Contrato cedido sem coobrigação', CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'True'))
INSERT FastConsig.dbo.CTCMotivoRetencaoContrato(Id, Codigo, Descricao, Consignado, CreditoImobiliario, CreditoPessoal, FinancimentoVeiculo, OutrosCreditos, ChequeEspecial, AdiantamentoDepositante, CapitalGiro, Pronampe) VALUES (14, '14', 'Indenização de seguro em andamento', CONVERT(bit, 'False'), CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), CONVERT(bit, 'False'))
INSERT FastConsig.dbo.CTCMotivoRetencaoContrato(Id, Codigo, Descricao, Consignado, CreditoImobiliario, CreditoPessoal, FinancimentoVeiculo, OutrosCreditos, ChequeEspecial, AdiantamentoDepositante, CapitalGiro, Pronampe) VALUES (15, '15', 'Contrato não registrado', CONVERT(bit, 'False'), CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), CONVERT(bit, 'False'))
INSERT FastConsig.dbo.CTCMotivoRetencaoContrato(Id, Codigo, Descricao, Consignado, CreditoImobiliario, CreditoPessoal, FinancimentoVeiculo, OutrosCreditos, ChequeEspecial, AdiantamentoDepositante, CapitalGiro, Pronampe) VALUES (16, '16', 'Contrato já liquidado', CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'True'))
INSERT FastConsig.dbo.CTCMotivoRetencaoContrato(Id, Codigo, Descricao, Consignado, CreditoImobiliario, CreditoPessoal, FinancimentoVeiculo, OutrosCreditos, ChequeEspecial, AdiantamentoDepositante, CapitalGiro, Pronampe) VALUES (17, '17', 'O cliente não solicitou a portabilidade', CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'True'))
INSERT FastConsig.dbo.CTCMotivoRetencaoContrato(Id, Codigo, Descricao, Consignado, CreditoImobiliario, CreditoPessoal, FinancimentoVeiculo, OutrosCreditos, ChequeEspecial, AdiantamentoDepositante, CapitalGiro, Pronampe) VALUES (18, '18', 'IF Credora Original Incorreta', CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'True'))
INSERT FastConsig.dbo.CTCMotivoRetencaoContrato(Id, Codigo, Descricao, Consignado, CreditoImobiliario, CreditoPessoal, FinancimentoVeiculo, OutrosCreditos, ChequeEspecial, AdiantamentoDepositante, CapitalGiro, Pronampe) VALUES (19, '19', 'Seguro obrigatório para operação diferente de funding FGTS', CONVERT(bit, 'False'), CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), NULL)
INSERT FastConsig.dbo.CTCMotivoRetencaoContrato(Id, Codigo, Descricao, Consignado, CreditoImobiliario, CreditoPessoal, FinancimentoVeiculo, OutrosCreditos, ChequeEspecial, AdiantamentoDepositante, CapitalGiro, Pronampe) VALUES (20, '20', 'Agência e/ou Conta não localizados', CONVERT(bit, 'False'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), CONVERT(bit, 'False'))
INSERT FastConsig.dbo.CTCMotivoRetencaoContrato(Id, Codigo, Descricao, Consignado, CreditoImobiliario, CreditoPessoal, FinancimentoVeiculo, OutrosCreditos, ChequeEspecial, AdiantamentoDepositante, CapitalGiro, Pronampe) VALUES (21, '21', 'Cheque Especial sem saldo devedor', CONVERT(bit, 'False'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), CONVERT(bit, 'False'))
INSERT FastConsig.dbo.CTCMotivoRetencaoContrato(Id, Codigo, Descricao, Consignado, CreditoImobiliario, CreditoPessoal, FinancimentoVeiculo, OutrosCreditos, ChequeEspecial, AdiantamentoDepositante, CapitalGiro, Pronampe) VALUES (22, '22', 'Natureza diferente de EI e MEI', CONVERT(bit, 'False'), CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'True'), CONVERT(bit, 'False'))
INSERT FastConsig.dbo.CTCMotivoRetencaoContrato(Id, Codigo, Descricao, Consignado, CreditoImobiliario, CreditoPessoal, FinancimentoVeiculo, OutrosCreditos, ChequeEspecial, AdiantamentoDepositante, CapitalGiro, Pronampe) VALUES (23, '23', 'Operação não é de PRONAMPE', CONVERT(bit, 'False'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), CONVERT(bit, 'True'))
INSERT FastConsig.dbo.CTCMotivoRetencaoContrato(Id, Codigo, Descricao, Consignado, CreditoImobiliario, CreditoPessoal, FinancimentoVeiculo, OutrosCreditos, ChequeEspecial, AdiantamentoDepositante, CapitalGiro, Pronampe) VALUES (24, '24', 'Processo de honra no FGO iniciado', CONVERT(bit, 'False'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), CONVERT(bit, 'False'), CONVERT(bit, 'True'))
INSERT FastConsig.dbo.CTCMotivoRetencaoContrato(Id, Codigo, Descricao, Consignado, CreditoImobiliario, CreditoPessoal, FinancimentoVeiculo, OutrosCreditos, ChequeEspecial, AdiantamentoDepositante, CapitalGiro, Pronampe) VALUES (25, '25', 'Portabilidade em andamento', CONVERT(bit, 'True'), CONVERT(bit, 'False'), CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'True'), CONVERT(bit, 'True'))
GO
SET IDENTITY_INSERT FastConsig.dbo.CTCMotivoRetencaoContrato OFF
GO