CREATE TABLE FastConsig.dbo.CTC922 (
  Id int IDENTITY,
  Arquivo int NOT NULL,
  DataReferencia date NOT NULL,
  CONSTRAINT PK_CTC922_Id PRIMARY KEY CLUSTERED (Id)
)
ON [PRIMARY]
GO

ALTER TABLE FastConsig.dbo.CTC922
  ADD CONSTRAINT FK_CTC922_Arquivo FOREIGN KEY (Arquivo) REFERENCES dbo.CTCArquivos (Id)
GO