CREATE TABLE FastConsig.dbo.CTC922TipoParte (
  Id int IDENTITY,
  Descricao varchar(50) NOT NULL,
  CONSTRAINT PK_CTC926TipoParte_Id PRIMARY KEY CLUSTERED (Id)
)
ON [PRIMARY]
GO

SET DATEFORMAT ymd
SET ARITHABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS, XACT_ABORT OFF
GO

SET IDENTITY_INSERT FastConsig.dbo.CTC922TipoParte ON
GO
INSERT FastConsig.dbo.CTC922TipoParte(Id, Descricao) VALUES (1, 'Originador')
INSERT FastConsig.dbo.CTC922TipoParte(Id, Descricao) VALUES (2, 'Proponente')
GO
SET IDENTITY_INSERT FastConsig.dbo.CTC922TipoParte OFF
GO