CREATE TABLE FastConsig.dbo.CTC928 (
  Id int IDENTITY,
  DataReferencia date NOT NULL,
  Arquivo int NULL,
  CONSTRAINT PK_CTC928_Id PRIMARY KEY CLUSTERED (Id)
)
ON [PRIMARY]
GO

ALTER TABLE FastConsig.dbo.CTC928
  ADD CONSTRAINT FK_CTC928_Arquivo FOREIGN KEY (Arquivo) REFERENCES dbo.CTCArquivos (Id)
GO