SET DATEFORMAT ymd
SET ARITHABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS, XACT_ABORT OFF
GO

INSERT Configuracao(Chave, Conteudo) VALUES (N'CTC.Caminho.Entrada.Criptografado', '\\server022\apps$\Integracoes\ConnectDirect_CIPCTC\Recebimento')
INSERT Configuracao(Chave, Conteudo) VALUES (N'CTC.Caminho.Entrada.Descriptografado', '\\server022\apps$\Integracoes\ConnectDirect_CIPCTC\Recebimento\XML')
INSERT Configuracao(Chave, Conteudo) VALUES (N'CTC.Caminho.Entrada.Ignorados', '\\server022\apps$\Integracoes\ConnectDirect_CIPCTC\Recebimento\Ignorados')
INSERT Configuracao(Chave, Conteudo) VALUES (N'CTC.Caminho.Entrada.Processados', '\\server022\apps$\Integracoes\ConnectDirect_CIPCTC\Recebimento\Processados')
INSERT Configuracao(Chave, Conteudo) VALUES (N'CTC.Caminho.Saida.Connect', '\\server022\apps$\Integracoes\ConnectDirect_CIPCTC\Envio')
INSERT Configuracao(Chave, Conteudo) VALUES (N'CTC.Caminho.Saida.Criptografado', 'D:\Batch\MonitorCTC\Aguardando')
INSERT Configuracao(Chave, Conteudo) VALUES (N'CTC.Caminho.Saida.Descriptografado', 'D:\Batch\MonitorCTC\Aguardando\XML')
INSERT Configuracao(Chave, Conteudo) VALUES (N'CTC.Caminho.Saida.Ignorados', 'D:\Batch\MonitorCTC\Aguardando\Ignorados')
INSERT Configuracao(Chave, Conteudo) VALUES (N'CTC.Caminho.Saida.Processados', 'D:\Batch\MonitorCTC\Aguardando\Processados')
INSERT Configuracao(Chave, Conteudo) VALUES (N'CTC.CNPJ.Instituicao', '')
INSERT Configuracao(Chave, Conteudo) VALUES (N'CTC.Criptografia', 'true')
INSERT Configuracao(Chave, Conteudo) VALUES (N'CTC.DataCancelamento', '23/10/2024 00:00:00')
INSERT Configuracao(Chave, Conteudo) VALUES (N'CTC.DataReferencia', '23/10/2024 00:00:00')
INSERT Configuracao(Chave, Conteudo) VALUES (N'CTC.DataSaldo', '24/10/2024 00:00:00')
INSERT Configuracao(Chave, Conteudo) VALUES (N'CTC.Dias.Aceite', '4')
INSERT Configuracao(Chave, Conteudo) VALUES (N'CTC.Dias.Retencao', '1')
INSERT Configuracao(Chave, Conteudo) VALUES (N'CTC.Dias.Tipo', 'U')
INSERT Configuracao(Chave, Conteudo) VALUES (N'CTC.EMail.Erro.Assunto', '[CTC] Falha na Importação do Arquivo')
INSERT Configuracao(Chave, Conteudo) VALUES (N'CTC.EMail.Erro.MailTo', 'lcgiro@gmail.com')
INSERT Configuracao(Chave, Conteudo) VALUES (N'CTC.EMail.Erro.Template', '')
INSERT Configuracao(Chave, Conteudo) VALUES (N'CTC.EMail.Exportacao.Notifica.Sucesso', 'false')
INSERT Configuracao(Chave, Conteudo) VALUES (N'CTC.EMail.Exportacao.Sucesso.Assunto', '[CTC] Arquivo Exportado com Sucesso')
INSERT Configuracao(Chave, Conteudo) VALUES (N'CTC.EMail.Exportacao.Sucesso.MailTo', 'lcgiro@gmail.com')
INSERT Configuracao(Chave, Conteudo) VALUES (N'CTC.EMail.Exportacao.Sucesso.Template', '')
INSERT Configuracao(Chave, Conteudo) VALUES (N'CTC.EMail.Ignorado.Assunto', '[CTC] Arquivo Ignorado no Monitoramento')
INSERT Configuracao(Chave, Conteudo) VALUES (N'CTC.EMail.Ignorado.MailTo', 'luiz.gro@bancopaulista.com.br')
INSERT Configuracao(Chave, Conteudo) VALUES (N'CTC.EMail.Ignorado.Template', '')
INSERT Configuracao(Chave, Conteudo) VALUES (N'CTC.EMail.Importacao.Notifica.Ignorados', 'false')
INSERT Configuracao(Chave, Conteudo) VALUES (N'CTC.EMail.Importacao.Notifica.Sucesso', 'false')
INSERT Configuracao(Chave, Conteudo) VALUES (N'CTC.EMail.Importacao.Sucesso.Assunto', '[CTC] Arquivo Importado com Sucesso')
INSERT Configuracao(Chave, Conteudo) VALUES (N'CTC.EMail.Importacao.Sucesso.MailTo', 'lcgiro@gmail.com')
INSERT Configuracao(Chave, Conteudo) VALUES (N'CTC.EMail.Importacao.Sucesso.Template', '')
INSERT Configuracao(Chave, Conteudo) VALUES (N'CTC.ISPB.Instituicao', '')
INSERT Configuracao(Chave, Conteudo) VALUES (N'CTC.Serial.Certificado.C3', '43aa2cd16ec56321')
INSERT Configuracao(Chave, Conteudo) VALUES (N'CTC.Serial.Certificado.Privado', '')
INSERT Configuracao(Chave, Conteudo) VALUES (N'CTC.Serial.Certificado.Publico', '')
INSERT Configuracao(Chave, Conteudo) VALUES (N'CTC.Url', 'http://')
GO