//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace FastConsig.CTC.Model.ACTC924
{
   using FastConsig.CTC.Model.Interfaces;
   using System.Xml.Serialization;


   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC924.xsd")]
   [System.Xml.Serialization.XmlRootAttribute("ACTCDOC", Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC924.xsd", IsNullable = false)]
   public partial class ACTC924 : IACTC
   {

      private BCARQComplexType bCARQField;

      private SISARQComplexType sISARQField;

      private string eSTARQField;

      /// <remarks/>
      public BCARQComplexType BCARQ
      {
         get
         {
            return this.bCARQField;
         }
         set
         {
            this.bCARQField = value;
         }
      }

      /// <remarks/>
      public SISARQComplexType SISARQ
      {
         get
         {
            return this.sISARQField;
         }
         set
         {
            this.sISARQField = value;
         }
      }

      /// <remarks/>
      public string ESTARQ
      {
         get
         {
            return this.eSTARQField;
         }
         set
         {
            this.eSTARQField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC924.xsd")]
   public partial class BCARQComplexType
   {

      private string nomArqField;

      private string numCtrlEmisField;

      private string numCtrlDestOrField;

      private string iSPBEmissorField;

      private string iSPBDestinatarioField;

      private System.DateTime dtHrArqField;

      private string sitReqField;

      private Grupo_SeqComplexType grupo_SeqField;

      private System.DateTime dtRefField;

      /// <remarks/>
      public string NomArq
      {
         get
         {
            return this.nomArqField;
         }
         set
         {
            this.nomArqField = value;
         }
      }

      /// <remarks/>
      public string NumCtrlEmis
      {
         get
         {
            return this.numCtrlEmisField;
         }
         set
         {
            this.numCtrlEmisField = value;
         }
      }

      /// <remarks/>
      public string NumCtrlDestOr
      {
         get
         {
            return this.numCtrlDestOrField;
         }
         set
         {
            this.numCtrlDestOrField = value;
         }
      }

      /// <remarks/>
      public string ISPBEmissor
      {
         get
         {
            return this.iSPBEmissorField;
         }
         set
         {
            this.iSPBEmissorField = value;
         }
      }

      /// <remarks/>
      public string ISPBDestinatario
      {
         get
         {
            return this.iSPBDestinatarioField;
         }
         set
         {
            this.iSPBDestinatarioField = value;
         }
      }

      /// <remarks/>
      public System.DateTime DtHrArq
      {
         get
         {
            return this.dtHrArqField;
         }
         set
         {
            this.dtHrArqField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
      public string SitReq
      {
         get
         {
            return this.sitReqField;
         }
         set
         {
            this.sitReqField = value;
         }
      }

      /// <remarks/>
      public Grupo_SeqComplexType Grupo_Seq
      {
         get
         {
            return this.grupo_SeqField;
         }
         set
         {
            this.grupo_SeqField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
      public System.DateTime DtRef
      {
         get
         {
            return this.dtRefField;
         }
         set
         {
            this.dtRefField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC924.xsd")]
   public partial class Grupo_SeqComplexType
   {

      private string numSeqField;

      private Indr indrContField;

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
      public string NumSeq
      {
         get
         {
            return this.numSeqField;
         }
         set
         {
            this.numSeqField = value;
         }
      }

      /// <remarks/>
      public Indr IndrCont
      {
         get
         {
            return this.indrContField;
         }
         set
         {
            this.indrContField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC924.xsd")]
   public enum Indr
   {

      /// <remarks/>
      S,

      /// <remarks/>
      N,
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC924.xsd")]
   public partial class Grupo_ACTC924_EftcPortlddComplexType
   {

      private System.DateTime dtEftcPortlddField;

      private string sitEftcPortlddField;

      private decimal vlrRCOField;

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
      public System.DateTime DtEftcPortldd
      {
         get
         {
            return this.dtEftcPortlddField;
         }
         set
         {
            this.dtEftcPortlddField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
      public string SitEftcPortldd
      {
         get
         {
            return this.sitEftcPortlddField;
         }
         set
         {
            this.sitEftcPortlddField = value;
         }
      }

      /// <remarks/>
      public decimal VlrRCO
      {
         get
         {
            return this.vlrRCOField;
         }
         set
         {
            this.vlrRCOField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC924.xsd")]
   public partial class Grupo_ACTC924_DevLiquidComplexType
   {

      private System.DateTime dtDevLiquidPortlddField;

      private string sitDevLiquidPortlddField;

      private string mtvDevLiquidPortlddField;

      private decimal vlrDevLiquidPortlddField;

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
      public System.DateTime DtDevLiquidPortldd
      {
         get
         {
            return this.dtDevLiquidPortlddField;
         }
         set
         {
            this.dtDevLiquidPortlddField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
      public string SitDevLiquidPortldd
      {
         get
         {
            return this.sitDevLiquidPortlddField;
         }
         set
         {
            this.sitDevLiquidPortlddField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
      public string MtvDevLiquidPortldd
      {
         get
         {
            return this.mtvDevLiquidPortlddField;
         }
         set
         {
            this.mtvDevLiquidPortlddField = value;
         }
      }

      /// <remarks/>
      public decimal VlrDevLiquidPortldd
      {
         get
         {
            return this.vlrDevLiquidPortlddField;
         }
         set
         {
            this.vlrDevLiquidPortlddField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC924.xsd")]
   public partial class Grupo_ACTC924_LiquidComplexType
   {

      private System.DateTime dtLiquidPortlddField;

      private string sitLiquidPortlddField;

      private decimal vlrLiquidPortlddField;

      private bool vlrLiquidPortlddFieldSpecified;

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
      public System.DateTime DtLiquidPortldd
      {
         get
         {
            return this.dtLiquidPortlddField;
         }
         set
         {
            this.dtLiquidPortlddField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
      public string SitLiquidPortldd
      {
         get
         {
            return this.sitLiquidPortlddField;
         }
         set
         {
            this.sitLiquidPortlddField = value;
         }
      }

      /// <remarks/>
      public decimal VlrLiquidPortldd
      {
         get
         {
            return this.vlrLiquidPortlddField;
         }
         set
         {
            this.vlrLiquidPortlddField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlIgnoreAttribute()]
      public bool VlrLiquidPortlddSpecified
      {
         get
         {
            return this.vlrLiquidPortlddFieldSpecified;
         }
         set
         {
            this.vlrLiquidPortlddFieldSpecified = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC924.xsd")]
   public partial class Grupo_ACTC924_CanceltComplexType
   {

      private System.DateTime dtCanceltPortlddField;

      private string mtvCanceltPortlddField;

      private string iSPBSolicttCancelField;

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
      public System.DateTime DtCanceltPortldd
      {
         get
         {
            return this.dtCanceltPortlddField;
         }
         set
         {
            this.dtCanceltPortlddField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
      public string MtvCanceltPortldd
      {
         get
         {
            return this.mtvCanceltPortlddField;
         }
         set
         {
            this.mtvCanceltPortlddField = value;
         }
      }

      /// <remarks/>
      public string ISPBSolicttCancel
      {
         get
         {
            return this.iSPBSolicttCancelField;
         }
         set
         {
            this.iSPBSolicttCancelField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC924.xsd")]
   public partial class Grupo_ACTC924_DcrsoPrzComplexType
   {

      private System.DateTime dtDcrsoPrzPortlddField;

      private string mtvDcrsoPrzPortlddField;

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
      public System.DateTime DtDcrsoPrzPortldd
      {
         get
         {
            return this.dtDcrsoPrzPortlddField;
         }
         set
         {
            this.dtDcrsoPrzPortlddField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
      public string MtvDcrsoPrzPortldd
      {
         get
         {
            return this.mtvDcrsoPrzPortlddField;
         }
         set
         {
            this.mtvDcrsoPrzPortlddField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC924.xsd")]
   public partial class Grupo_ACTC924_RetenComplexType
   {

      private System.DateTime dtRetenContrtoField;

      private string mtvRetenContrtoField;

      private string tpContrtoOrField;

      private string cPF_TitlarField;

      private string[] condcDivgteField;

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
      public System.DateTime DtRetenContrto
      {
         get
         {
            return this.dtRetenContrtoField;
         }
         set
         {
            this.dtRetenContrtoField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
      public string MtvRetenContrto
      {
         get
         {
            return this.mtvRetenContrtoField;
         }
         set
         {
            this.mtvRetenContrtoField = value;
         }
      }

      /// <remarks/>
      public string TpContrtoOr
      {
         get
         {
            return this.tpContrtoOrField;
         }
         set
         {
            this.tpContrtoOrField = value;
         }
      }

      /// <remarks/>
      public string CPF_Titlar
      {
         get
         {
            return this.cPF_TitlarField;
         }
         set
         {
            this.cPF_TitlarField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute("CondcDivgte", DataType = "integer")]
      public string[] CondcDivgte
      {
         get
         {
            return this.condcDivgteField;
         }
         set
         {
            this.condcDivgteField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC924.xsd")]
   public partial class Grupo_ACTC924_CliComplexType
   {

      private TpPessoa tpCliField;

      private string cNPJ_CPFCliField;

      private string nomCliField;

      private string telCliField;

      private string emailCliField;

      private string logradEndCliField;

      private string compEndCliField;

      private string numEndCliField;

      private string cidEndCliField;

      private string uFEndCliField;

      private string cEPEndCliField;

      /// <remarks/>
      public TpPessoa TpCli
      {
         get
         {
            return this.tpCliField;
         }
         set
         {
            this.tpCliField = value;
         }
      }

      /// <remarks/>
      public string CNPJ_CPFCli
      {
         get
         {
            return this.cNPJ_CPFCliField;
         }
         set
         {
            this.cNPJ_CPFCliField = value;
         }
      }

      /// <remarks/>
      public string NomCli
      {
         get
         {
            return this.nomCliField;
         }
         set
         {
            this.nomCliField = value;
         }
      }

      /// <remarks/>
      public string TelCli
      {
         get
         {
            return this.telCliField;
         }
         set
         {
            this.telCliField = value;
         }
      }

      /// <remarks/>
      public string EmailCli
      {
         get
         {
            return this.emailCliField;
         }
         set
         {
            this.emailCliField = value;
         }
      }

      /// <remarks/>
      public string LogradEndCli
      {
         get
         {
            return this.logradEndCliField;
         }
         set
         {
            this.logradEndCliField = value;
         }
      }

      /// <remarks/>
      public string CompEndCli
      {
         get
         {
            return this.compEndCliField;
         }
         set
         {
            this.compEndCliField = value;
         }
      }

      /// <remarks/>
      public string NumEndCli
      {
         get
         {
            return this.numEndCliField;
         }
         set
         {
            this.numEndCliField = value;
         }
      }

      /// <remarks/>
      public string CidEndCli
      {
         get
         {
            return this.cidEndCliField;
         }
         set
         {
            this.cidEndCliField = value;
         }
      }

      /// <remarks/>
      public string UFEndCli
      {
         get
         {
            return this.uFEndCliField;
         }
         set
         {
            this.uFEndCliField = value;
         }
      }

      /// <remarks/>
      public string CEPEndCli
      {
         get
         {
            return this.cEPEndCliField;
         }
         set
         {
            this.cEPEndCliField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC924.xsd")]
   public enum TpPessoa
   {

      /// <remarks/>
      F,

      /// <remarks/>
      J,
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC924.xsd")]
   public partial class Grupo_ACTC924_PortlddAprovdComplexType
   {

      private System.DateTime[] dtRefSaldDevdrContbPropntField;

      private decimal[] vlrSaldDevdrContbPropntField;

      private System.DateTime[] dtRefSaldDevdrContbOrContrtoField;

      private decimal[] vlrSaldDevdrContbOrContrtoField;

      private decimal vlrSaldDevdrContbADField;

      private bool vlrSaldDevdrContbADFieldSpecified;

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute("DtRefSaldDevdrContbPropnt", DataType = "date")]
      public System.DateTime[] DtRefSaldDevdrContbPropnt
      {
         get
         {
            return this.dtRefSaldDevdrContbPropntField;
         }
         set
         {
            this.dtRefSaldDevdrContbPropntField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute("VlrSaldDevdrContbPropnt")]
      public decimal[] VlrSaldDevdrContbPropnt
      {
         get
         {
            return this.vlrSaldDevdrContbPropntField;
         }
         set
         {
            this.vlrSaldDevdrContbPropntField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute("DtRefSaldDevdrContbOrContrto", DataType = "date")]
      public System.DateTime[] DtRefSaldDevdrContbOrContrto
      {
         get
         {
            return this.dtRefSaldDevdrContbOrContrtoField;
         }
         set
         {
            this.dtRefSaldDevdrContbOrContrtoField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute("VlrSaldDevdrContbOrContrto")]
      public decimal[] VlrSaldDevdrContbOrContrto
      {
         get
         {
            return this.vlrSaldDevdrContbOrContrtoField;
         }
         set
         {
            this.vlrSaldDevdrContbOrContrtoField = value;
         }
      }

      /// <remarks/>
      public decimal VlrSaldDevdrContbAD
      {
         get
         {
            return this.vlrSaldDevdrContbADField;
         }
         set
         {
            this.vlrSaldDevdrContbADField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlIgnoreAttribute()]
      public bool VlrSaldDevdrContbADSpecified
      {
         get
         {
            return this.vlrSaldDevdrContbADFieldSpecified;
         }
         set
         {
            this.vlrSaldDevdrContbADFieldSpecified = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC924.xsd")]
   public partial class Grupo_ACTC924_DadRelatPosAnlComplexType
   {

      private System.DateTime dtSolictcPortlddField;

      private string nUPortlddCTCField;

      private string sitPortlddCTCField;

      private string iSPBPropntField;

      private Grupo_ACTC924_PortlddAprovdComplexType[] grupo_ACTC924_PortlddAprovdField;

      private string codContrtoOrField;

      private string cNPJBase_IFOrContrtoField;

      private string tpContrtoField;

      private string tpEnteConsField;

      private string cNPJCorrespBancField;

      private Grupo_ACTC924_CliComplexType[] grupo_ACTC924_CliField;

      private Grupo_ACTC924_RetenComplexType[] grupo_ACTC924_RetenField;

      private Grupo_ACTC924_DcrsoPrzComplexType[] grupo_ACTC924_DcrsoPrzField;

      private Grupo_ACTC924_CanceltComplexType[] grupo_ACTC924_CanceltField;

      private Grupo_ACTC924_LiquidComplexType[] grupo_ACTC924_LiquidField;

      private Grupo_ACTC924_DevLiquidComplexType[] grupo_ACTC924_DevLiquidField;

      private Grupo_ACTC924_EftcPortlddComplexType[] grupo_ACTC924_EftcPortlddField;

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
      public System.DateTime DtSolictcPortldd
      {
         get
         {
            return this.dtSolictcPortlddField;
         }
         set
         {
            this.dtSolictcPortlddField = value;
         }
      }

      /// <remarks/>
      public string NUPortlddCTC
      {
         get
         {
            return this.nUPortlddCTCField;
         }
         set
         {
            this.nUPortlddCTCField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
      public string SitPortlddCTC
      {
         get
         {
            return this.sitPortlddCTCField;
         }
         set
         {
            this.sitPortlddCTCField = value;
         }
      }

      /// <remarks/>
      public string ISPBPropnt
      {
         get
         {
            return this.iSPBPropntField;
         }
         set
         {
            this.iSPBPropntField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute("Grupo_ACTC924_PortlddAprovd")]
      public Grupo_ACTC924_PortlddAprovdComplexType[] Grupo_ACTC924_PortlddAprovd
      {
         get
         {
            return this.grupo_ACTC924_PortlddAprovdField;
         }
         set
         {
            this.grupo_ACTC924_PortlddAprovdField = value;
         }
      }

      /// <remarks/>
      public string CodContrtoOr
      {
         get
         {
            return this.codContrtoOrField;
         }
         set
         {
            this.codContrtoOrField = value;
         }
      }

      /// <remarks/>
      public string CNPJBase_IFOrContrto
      {
         get
         {
            return this.cNPJBase_IFOrContrtoField;
         }
         set
         {
            this.cNPJBase_IFOrContrtoField = value;
         }
      }

      /// <remarks/>
      public string TpContrto
      {
         get
         {
            return this.tpContrtoField;
         }
         set
         {
            this.tpContrtoField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
      public string TpEnteCons
      {
         get
         {
            return this.tpEnteConsField;
         }
         set
         {
            this.tpEnteConsField = value;
         }
      }

      /// <remarks/>
      public string CNPJCorrespBanc
      {
         get
         {
            return this.cNPJCorrespBancField;
         }
         set
         {
            this.cNPJCorrespBancField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute("Grupo_ACTC924_Cli")]
      public Grupo_ACTC924_CliComplexType[] Grupo_ACTC924_Cli
      {
         get
         {
            return this.grupo_ACTC924_CliField;
         }
         set
         {
            this.grupo_ACTC924_CliField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute("Grupo_ACTC924_Reten")]
      public Grupo_ACTC924_RetenComplexType[] Grupo_ACTC924_Reten
      {
         get
         {
            return this.grupo_ACTC924_RetenField;
         }
         set
         {
            this.grupo_ACTC924_RetenField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute("Grupo_ACTC924_DcrsoPrz")]
      public Grupo_ACTC924_DcrsoPrzComplexType[] Grupo_ACTC924_DcrsoPrz
      {
         get
         {
            return this.grupo_ACTC924_DcrsoPrzField;
         }
         set
         {
            this.grupo_ACTC924_DcrsoPrzField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute("Grupo_ACTC924_Cancelt")]
      public Grupo_ACTC924_CanceltComplexType[] Grupo_ACTC924_Cancelt
      {
         get
         {
            return this.grupo_ACTC924_CanceltField;
         }
         set
         {
            this.grupo_ACTC924_CanceltField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute("Grupo_ACTC924_Liquid")]
      public Grupo_ACTC924_LiquidComplexType[] Grupo_ACTC924_Liquid
      {
         get
         {
            return this.grupo_ACTC924_LiquidField;
         }
         set
         {
            this.grupo_ACTC924_LiquidField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute("Grupo_ACTC924_DevLiquid")]
      public Grupo_ACTC924_DevLiquidComplexType[] Grupo_ACTC924_DevLiquid
      {
         get
         {
            return this.grupo_ACTC924_DevLiquidField;
         }
         set
         {
            this.grupo_ACTC924_DevLiquidField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute("Grupo_ACTC924_EftcPortldd")]
      public Grupo_ACTC924_EftcPortlddComplexType[] Grupo_ACTC924_EftcPortldd
      {
         get
         {
            return this.grupo_ACTC924_EftcPortlddField;
         }
         set
         {
            this.grupo_ACTC924_EftcPortlddField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC924.xsd")]
   public partial class Grupo_ACTC924_RelatPosAnlComplexType
   {

      private string identdPartAdmdoField;

      private string numCtrlCIPField;

      private string sitProcField;

      private Grupo_ACTC924_DadRelatPosAnlComplexType[] grupo_ACTC924_DadRelatPosAnlField;

      /// <remarks/>
      public string IdentdPartAdmdo
      {
         get
         {
            return this.identdPartAdmdoField;
         }
         set
         {
            this.identdPartAdmdoField = value;
         }
      }

      /// <remarks/>
      public string NumCtrlCIP
      {
         get
         {
            return this.numCtrlCIPField;
         }
         set
         {
            this.numCtrlCIPField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
      public string SitProc
      {
         get
         {
            return this.sitProcField;
         }
         set
         {
            this.sitProcField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute("Grupo_ACTC924_DadRelatPosAnl")]
      public Grupo_ACTC924_DadRelatPosAnlComplexType[] Grupo_ACTC924_DadRelatPosAnl
      {
         get
         {
            return this.grupo_ACTC924_DadRelatPosAnlField;
         }
         set
         {
            this.grupo_ACTC924_DadRelatPosAnlField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC924.xsd")]
   public partial class SISARQComplexType
   {

      private Grupo_ACTC924_RelatPosAnlComplexType itemField;

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute("ACTC924")]
      public Grupo_ACTC924_RelatPosAnlComplexType Item
      {
         get
         {
            return this.itemField;
         }
         set
         {
            this.itemField = value;
         }
      }
   }
}
