//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace FastConsig.CTC.Model.ACTC927
{
   using FastConsig.CTC.Model.Interfaces;
   using System.Xml.Serialization;


   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC927.xsd")]
   [System.Xml.Serialization.XmlRootAttribute("ACTCDOC", Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC927.xsd", IsNullable = false)]
   public partial class ACTC927 : IACTC
   {

      private BCARQComplexType bCARQField;

      private SISARQComplexType sISARQField;

      private string eSTARQField;

      /// <remarks/>
      public BCARQComplexType BCARQ
      {
         get
         {
            return this.bCARQField;
         }
         set
         {
            this.bCARQField = value;
         }
      }

      /// <remarks/>
      public SISARQComplexType SISARQ
      {
         get
         {
            return this.sISARQField;
         }
         set
         {
            this.sISARQField = value;
         }
      }

      /// <remarks/>
      public string ESTARQ
      {
         get
         {
            return this.eSTARQField;
         }
         set
         {
            this.eSTARQField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC927.xsd")]
   public partial class BCARQComplexType
   {

      private string nomArqField;

      private string numCtrlEmisField;

      private string numCtrlDestOrField;

      private string iSPBEmissorField;

      private string iSPBDestinatarioField;

      private System.DateTime dtHrArqField;

      private string sitReqField;

      private Grupo_SeqComplexType grupo_SeqField;

      private System.DateTime dtRefField;

      /// <remarks/>
      public string NomArq
      {
         get
         {
            return this.nomArqField;
         }
         set
         {
            this.nomArqField = value;
         }
      }

      /// <remarks/>
      public string NumCtrlEmis
      {
         get
         {
            return this.numCtrlEmisField;
         }
         set
         {
            this.numCtrlEmisField = value;
         }
      }

      /// <remarks/>
      public string NumCtrlDestOr
      {
         get
         {
            return this.numCtrlDestOrField;
         }
         set
         {
            this.numCtrlDestOrField = value;
         }
      }

      /// <remarks/>
      public string ISPBEmissor
      {
         get
         {
            return this.iSPBEmissorField;
         }
         set
         {
            this.iSPBEmissorField = value;
         }
      }

      /// <remarks/>
      public string ISPBDestinatario
      {
         get
         {
            return this.iSPBDestinatarioField;
         }
         set
         {
            this.iSPBDestinatarioField = value;
         }
      }

      /// <remarks/>
      public System.DateTime DtHrArq
      {
         get
         {
            return this.dtHrArqField;
         }
         set
         {
            this.dtHrArqField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
      public string SitReq
      {
         get
         {
            return this.sitReqField;
         }
         set
         {
            this.sitReqField = value;
         }
      }

      /// <remarks/>
      public Grupo_SeqComplexType Grupo_Seq
      {
         get
         {
            return this.grupo_SeqField;
         }
         set
         {
            this.grupo_SeqField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
      public System.DateTime DtRef
      {
         get
         {
            return this.dtRefField;
         }
         set
         {
            this.dtRefField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC927.xsd")]
   public partial class Grupo_SeqComplexType
   {

      private string numSeqField;

      private Indr indrContField;

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
      public string NumSeq
      {
         get
         {
            return this.numSeqField;
         }
         set
         {
            this.numSeqField = value;
         }
      }

      /// <remarks/>
      public Indr IndrCont
      {
         get
         {
            return this.indrContField;
         }
         set
         {
            this.indrContField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC927.xsd")]
   public enum Indr
   {

      /// <remarks/>
      S,

      /// <remarks/>
      N,
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC927.xsd")]
   public partial class Texto_CodErro
   {

      private string codErroField;

      private string valueField;

      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string CodErro
      {
         get
         {
            return this.codErroField;
         }
         set
         {
            this.codErroField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlTextAttribute()]
      public string Value
      {
         get
         {
            return this.valueField;
         }
         set
         {
            this.valueField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC927.xsd")]
   public partial class Grupo_ACTC927_PortabilidadeComplexType
   {

      private System.DateTime dtHrOperacaoField;

      private bool dtHrOperacaoFieldSpecified;

      private string cPF_CNPJ_ClienteField;

      private string nuPortabilidadeField;

      private string codigoContratoOriginalField;

      private string iSPB_IF_OriginadoraField;

      private string nomeReduzidoOriginadoraField;

      private string iSPB_IF_ProponenteField;

      private string nomeReduzidoProponenteField;

      private string situacaoPortabilidadeField;

      private System.DateTime dtSituacaoField;

      private bool dtSituacaoFieldSpecified;

      private string mtvRetencaoField;

      private string nomeMotivoRetencaoField;

      private string mtvCancelamentoField;

      private string nomeMotivoCancelamentoField;

      private string cNPJ_IF_SolicCancelamentoField;

      private string codigoTipoContratoField;

      private string descricaoTipoContratoField;

      private string codigoTipoContratoPropostaField;

      private Texto_CodErro descricaoTipoContratoPropostaField;

      private string codigoEnteConsignanteField;

      private string descricaoEnteConsignanteField;

      private string cNPJ_CorrespBancField;

      private string cEP_EnderecoClienteField;

      private string qtdTotParclField;

      private string qtdTotParclVencrField;

      private decimal vlrSaldoDevdContbField;

      private bool vlrSaldoDevdContbFieldSpecified;

      private decimal txJurosNomlField;

      private bool txJurosNomlFieldSpecified;

      private decimal txJuros_EFTField;

      private bool txJuros_EFTFieldSpecified;

      private decimal tx_CETField;

      private bool tx_CETFieldSpecified;

      private decimal vlrFaceParclField;

      private bool vlrFaceParclFieldSpecified;

      private System.DateTime dtVencPrimParclField;

      private bool dtVencPrimParclFieldSpecified;

      private System.DateTime dtVencUltParclField;

      private bool dtVencUltParclFieldSpecified;

      private System.DateTime dtDigitPropCorrespBancField;

      private bool dtDigitPropCorrespBancFieldSpecified;

      private System.DateTime dtContrOpOrigField;

      private bool dtContrOpOrigFieldSpecified;

      private string canOpOrigemField;

      private string cNPJ_CanOrigemField;

      /// <remarks/>
      public System.DateTime DtHrOperacao
      {
         get
         {
            return this.dtHrOperacaoField;
         }
         set
         {
            this.dtHrOperacaoField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlIgnoreAttribute()]
      public bool DtHrOperacaoSpecified
      {
         get
         {
            return this.dtHrOperacaoFieldSpecified;
         }
         set
         {
            this.dtHrOperacaoFieldSpecified = value;
         }
      }

      /// <remarks/>
      public string CPF_CNPJ_Cliente
      {
         get
         {
            return this.cPF_CNPJ_ClienteField;
         }
         set
         {
            this.cPF_CNPJ_ClienteField = value;
         }
      }

      /// <remarks/>
      public string NuPortabilidade
      {
         get
         {
            return this.nuPortabilidadeField;
         }
         set
         {
            this.nuPortabilidadeField = value;
         }
      }

      /// <remarks/>
      public string CodigoContratoOriginal
      {
         get
         {
            return this.codigoContratoOriginalField;
         }
         set
         {
            this.codigoContratoOriginalField = value;
         }
      }

      /// <remarks/>
      public string ISPB_IF_Originadora
      {
         get
         {
            return this.iSPB_IF_OriginadoraField;
         }
         set
         {
            this.iSPB_IF_OriginadoraField = value;
         }
      }

      /// <remarks/>
      public string NomeReduzidoOriginadora
      {
         get
         {
            return this.nomeReduzidoOriginadoraField;
         }
         set
         {
            this.nomeReduzidoOriginadoraField = value;
         }
      }

      /// <remarks/>
      public string ISPB_IF_Proponente
      {
         get
         {
            return this.iSPB_IF_ProponenteField;
         }
         set
         {
            this.iSPB_IF_ProponenteField = value;
         }
      }

      /// <remarks/>
      public string NomeReduzidoProponente
      {
         get
         {
            return this.nomeReduzidoProponenteField;
         }
         set
         {
            this.nomeReduzidoProponenteField = value;
         }
      }

      /// <remarks/>
      public string SituacaoPortabilidade
      {
         get
         {
            return this.situacaoPortabilidadeField;
         }
         set
         {
            this.situacaoPortabilidadeField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
      public System.DateTime DtSituacao
      {
         get
         {
            return this.dtSituacaoField;
         }
         set
         {
            this.dtSituacaoField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlIgnoreAttribute()]
      public bool DtSituacaoSpecified
      {
         get
         {
            return this.dtSituacaoFieldSpecified;
         }
         set
         {
            this.dtSituacaoFieldSpecified = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
      public string MtvRetencao
      {
         get
         {
            return this.mtvRetencaoField;
         }
         set
         {
            this.mtvRetencaoField = value;
         }
      }

      /// <remarks/>
      public string NomeMotivoRetencao
      {
         get
         {
            return this.nomeMotivoRetencaoField;
         }
         set
         {
            this.nomeMotivoRetencaoField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
      public string MtvCancelamento
      {
         get
         {
            return this.mtvCancelamentoField;
         }
         set
         {
            this.mtvCancelamentoField = value;
         }
      }

      /// <remarks/>
      public string NomeMotivoCancelamento
      {
         get
         {
            return this.nomeMotivoCancelamentoField;
         }
         set
         {
            this.nomeMotivoCancelamentoField = value;
         }
      }

      /// <remarks/>
      public string CNPJ_IF_SolicCancelamento
      {
         get
         {
            return this.cNPJ_IF_SolicCancelamentoField;
         }
         set
         {
            this.cNPJ_IF_SolicCancelamentoField = value;
         }
      }

      /// <remarks/>
      public string CodigoTipoContrato
      {
         get
         {
            return this.codigoTipoContratoField;
         }
         set
         {
            this.codigoTipoContratoField = value;
         }
      }

      /// <remarks/>
      public string DescricaoTipoContrato
      {
         get
         {
            return this.descricaoTipoContratoField;
         }
         set
         {
            this.descricaoTipoContratoField = value;
         }
      }

      /// <remarks/>
      public string CodigoTipoContratoProposta
      {
         get
         {
            return this.codigoTipoContratoPropostaField;
         }
         set
         {
            this.codigoTipoContratoPropostaField = value;
         }
      }

      /// <remarks/>
      public Texto_CodErro DescricaoTipoContratoProposta
      {
         get
         {
            return this.descricaoTipoContratoPropostaField;
         }
         set
         {
            this.descricaoTipoContratoPropostaField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
      public string CodigoEnteConsignante
      {
         get
         {
            return this.codigoEnteConsignanteField;
         }
         set
         {
            this.codigoEnteConsignanteField = value;
         }
      }

      /// <remarks/>
      public string DescricaoEnteConsignante
      {
         get
         {
            return this.descricaoEnteConsignanteField;
         }
         set
         {
            this.descricaoEnteConsignanteField = value;
         }
      }

      /// <remarks/>
      public string CNPJ_CorrespBanc
      {
         get
         {
            return this.cNPJ_CorrespBancField;
         }
         set
         {
            this.cNPJ_CorrespBancField = value;
         }
      }

      /// <remarks/>
      public string CEP_EnderecoCliente
      {
         get
         {
            return this.cEP_EnderecoClienteField;
         }
         set
         {
            this.cEP_EnderecoClienteField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
      public string QtdTotParcl
      {
         get
         {
            return this.qtdTotParclField;
         }
         set
         {
            this.qtdTotParclField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
      public string QtdTotParclVencr
      {
         get
         {
            return this.qtdTotParclVencrField;
         }
         set
         {
            this.qtdTotParclVencrField = value;
         }
      }

      /// <remarks/>
      public decimal VlrSaldoDevdContb
      {
         get
         {
            return this.vlrSaldoDevdContbField;
         }
         set
         {
            this.vlrSaldoDevdContbField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlIgnoreAttribute()]
      public bool VlrSaldoDevdContbSpecified
      {
         get
         {
            return this.vlrSaldoDevdContbFieldSpecified;
         }
         set
         {
            this.vlrSaldoDevdContbFieldSpecified = value;
         }
      }

      /// <remarks/>
      public decimal TxJurosNoml
      {
         get
         {
            return this.txJurosNomlField;
         }
         set
         {
            this.txJurosNomlField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlIgnoreAttribute()]
      public bool TxJurosNomlSpecified
      {
         get
         {
            return this.txJurosNomlFieldSpecified;
         }
         set
         {
            this.txJurosNomlFieldSpecified = value;
         }
      }

      /// <remarks/>
      public decimal TxJuros_EFT
      {
         get
         {
            return this.txJuros_EFTField;
         }
         set
         {
            this.txJuros_EFTField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlIgnoreAttribute()]
      public bool TxJuros_EFTSpecified
      {
         get
         {
            return this.txJuros_EFTFieldSpecified;
         }
         set
         {
            this.txJuros_EFTFieldSpecified = value;
         }
      }

      /// <remarks/>
      public decimal Tx_CET
      {
         get
         {
            return this.tx_CETField;
         }
         set
         {
            this.tx_CETField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlIgnoreAttribute()]
      public bool Tx_CETSpecified
      {
         get
         {
            return this.tx_CETFieldSpecified;
         }
         set
         {
            this.tx_CETFieldSpecified = value;
         }
      }

      /// <remarks/>
      public decimal VlrFaceParcl
      {
         get
         {
            return this.vlrFaceParclField;
         }
         set
         {
            this.vlrFaceParclField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlIgnoreAttribute()]
      public bool VlrFaceParclSpecified
      {
         get
         {
            return this.vlrFaceParclFieldSpecified;
         }
         set
         {
            this.vlrFaceParclFieldSpecified = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
      public System.DateTime DtVencPrimParcl
      {
         get
         {
            return this.dtVencPrimParclField;
         }
         set
         {
            this.dtVencPrimParclField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlIgnoreAttribute()]
      public bool DtVencPrimParclSpecified
      {
         get
         {
            return this.dtVencPrimParclFieldSpecified;
         }
         set
         {
            this.dtVencPrimParclFieldSpecified = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
      public System.DateTime DtVencUltParcl
      {
         get
         {
            return this.dtVencUltParclField;
         }
         set
         {
            this.dtVencUltParclField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlIgnoreAttribute()]
      public bool DtVencUltParclSpecified
      {
         get
         {
            return this.dtVencUltParclFieldSpecified;
         }
         set
         {
            this.dtVencUltParclFieldSpecified = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
      public System.DateTime DtDigitPropCorrespBanc
      {
         get
         {
            return this.dtDigitPropCorrespBancField;
         }
         set
         {
            this.dtDigitPropCorrespBancField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlIgnoreAttribute()]
      public bool DtDigitPropCorrespBancSpecified
      {
         get
         {
            return this.dtDigitPropCorrespBancFieldSpecified;
         }
         set
         {
            this.dtDigitPropCorrespBancFieldSpecified = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
      public System.DateTime DtContrOpOrig
      {
         get
         {
            return this.dtContrOpOrigField;
         }
         set
         {
            this.dtContrOpOrigField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlIgnoreAttribute()]
      public bool DtContrOpOrigSpecified
      {
         get
         {
            return this.dtContrOpOrigFieldSpecified;
         }
         set
         {
            this.dtContrOpOrigFieldSpecified = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
      public string CanOpOrigem
      {
         get
         {
            return this.canOpOrigemField;
         }
         set
         {
            this.canOpOrigemField = value;
         }
      }

      /// <remarks/>
      public string CNPJ_CanOrigem
      {
         get
         {
            return this.cNPJ_CanOrigemField;
         }
         set
         {
            this.cNPJ_CanOrigemField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC927.xsd")]
   public partial class ACTC927ComplexType
   {

      private string numCtrlCIPField;

      private string dataInicialField;

      private string dataFinalField;

      private Grupo_ACTC927_PortabilidadeComplexType[] grupo_ACTC927_Portabilidade_EfetivadaField;

      private Grupo_ACTC927_PortabilidadeComplexType[] grupo_ACTC927_Portabilidade_RetidaField;

      private Grupo_ACTC927_PortabilidadeComplexType[] grupo_ACTC927_Portabilidade_CanceladaField;

      /// <remarks/>
      public string NumCtrlCIP
      {
         get
         {
            return this.numCtrlCIPField;
         }
         set
         {
            this.numCtrlCIPField = value;
         }
      }

      /// <remarks/>
      public string DataInicial
      {
         get
         {
            return this.dataInicialField;
         }
         set
         {
            this.dataInicialField = value;
         }
      }

      /// <remarks/>
      public string DataFinal
      {
         get
         {
            return this.dataFinalField;
         }
         set
         {
            this.dataFinalField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute("Grupo_ACTC927_Portabilidade_Efetivada")]
      public Grupo_ACTC927_PortabilidadeComplexType[] Grupo_ACTC927_Portabilidade_Efetivada
      {
         get
         {
            return this.grupo_ACTC927_Portabilidade_EfetivadaField;
         }
         set
         {
            this.grupo_ACTC927_Portabilidade_EfetivadaField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute("Grupo_ACTC927_Portabilidade_Retida")]
      public Grupo_ACTC927_PortabilidadeComplexType[] Grupo_ACTC927_Portabilidade_Retida
      {
         get
         {
            return this.grupo_ACTC927_Portabilidade_RetidaField;
         }
         set
         {
            this.grupo_ACTC927_Portabilidade_RetidaField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute("Grupo_ACTC927_Portabilidade_Cancelada")]
      public Grupo_ACTC927_PortabilidadeComplexType[] Grupo_ACTC927_Portabilidade_Cancelada
      {
         get
         {
            return this.grupo_ACTC927_Portabilidade_CanceladaField;
         }
         set
         {
            this.grupo_ACTC927_Portabilidade_CanceladaField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC927.xsd")]
   public partial class SISARQComplexType
   {

      private ACTC927ComplexType itemField;

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute("ACTC927")]
      public ACTC927ComplexType Item
      {
         get
         {
            return this.itemField;
         }
         set
         {
            this.itemField = value;
         }
      }
   }
}
