//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace FastConsig.CTC.Model.ACTC204
{
   using FastConsig.CTC.Model.Interfaces;
   using System.Xml.Serialization;


   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC204.xsd")]
   [System.Xml.Serialization.XmlRootAttribute("ACTCDOC", Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC204.xsd", IsNullable = false)]
   public partial class ACTC204 : IACTC
   {

      private BCARQComplexType bCARQField;

      private SISARQComplexType sISARQField;

      private string eSTARQField;

      /// <remarks/>
      public BCARQComplexType BCARQ
      {
         get
         {
            return this.bCARQField;
         }
         set
         {
            this.bCARQField = value;
         }
      }

      /// <remarks/>
      public SISARQComplexType SISARQ
      {
         get
         {
            return this.sISARQField;
         }
         set
         {
            this.sISARQField = value;
         }
      }

      /// <remarks/>
      public string ESTARQ
      {
         get
         {
            return this.eSTARQField;
         }
         set
         {
            this.eSTARQField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC204.xsd")]
   public partial class BCARQComplexType
   {

      private string nomArqField;

      private string numCtrlEmisField;

      private string numCtrlDestOrField;

      private string iSPBEmissorField;

      private string iSPBDestinatarioField;

      private System.DateTime dtHrArqField;

      private string sitReqField;

      private Grupo_SeqComplexType grupo_SeqField;

      private System.DateTime dtRefField;

      /// <remarks/>
      public string NomArq
      {
         get
         {
            return this.nomArqField;
         }
         set
         {
            this.nomArqField = value;
         }
      }

      /// <remarks/>
      public string NumCtrlEmis
      {
         get
         {
            return this.numCtrlEmisField;
         }
         set
         {
            this.numCtrlEmisField = value;
         }
      }

      /// <remarks/>
      public string NumCtrlDestOr
      {
         get
         {
            return this.numCtrlDestOrField;
         }
         set
         {
            this.numCtrlDestOrField = value;
         }
      }

      /// <remarks/>
      public string ISPBEmissor
      {
         get
         {
            return this.iSPBEmissorField;
         }
         set
         {
            this.iSPBEmissorField = value;
         }
      }

      /// <remarks/>
      public string ISPBDestinatario
      {
         get
         {
            return this.iSPBDestinatarioField;
         }
         set
         {
            this.iSPBDestinatarioField = value;
         }
      }

      /// <remarks/>
      public System.DateTime DtHrArq
      {
         get
         {
            return this.dtHrArqField;
         }
         set
         {
            this.dtHrArqField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
      public string SitReq
      {
         get
         {
            return this.sitReqField;
         }
         set
         {
            this.sitReqField = value;
         }
      }

      /// <remarks/>
      public Grupo_SeqComplexType Grupo_Seq
      {
         get
         {
            return this.grupo_SeqField;
         }
         set
         {
            this.grupo_SeqField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
      public System.DateTime DtRef
      {
         get
         {
            return this.dtRefField;
         }
         set
         {
            this.dtRefField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC204.xsd")]
   public partial class Grupo_SeqComplexType
   {

      private string numSeqField;

      private Indr indrContField;

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
      public string NumSeq
      {
         get
         {
            return this.numSeqField;
         }
         set
         {
            this.numSeqField = value;
         }
      }

      /// <remarks/>
      public Indr IndrCont
      {
         get
         {
            return this.indrContField;
         }
         set
         {
            this.indrContField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC204.xsd")]
   public enum Indr
   {

      /// <remarks/>
      S,

      /// <remarks/>
      N,
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC204.xsd")]
   public partial class ACTC204ComplexType
   {

      private Grupo_ACTC204_PortlddComplexType[] grupo_ACTC204_PortlddField;

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute("Grupo_ACTC204_Portldd")]
      public Grupo_ACTC204_PortlddComplexType[] Grupo_ACTC204_Portldd
      {
         get
         {
            return this.grupo_ACTC204_PortlddField;
         }
         set
         {
            this.grupo_ACTC204_PortlddField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC204.xsd")]
   public partial class Grupo_ACTC204_PortlddComplexType
   {

      private string identdPartAdmdoField;

      private string nUPortlddCTCField;

      private object itemField;

      /// <remarks/>
      public string IdentdPartAdmdo
      {
         get
         {
            return this.identdPartAdmdoField;
         }
         set
         {
            this.identdPartAdmdoField = value;
         }
      }

      /// <remarks/>
      public string NUPortlddCTC
      {
         get
         {
            return this.nUPortlddCTCField;
         }
         set
         {
            this.nUPortlddCTCField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute("Grupo_ACTC204_EftcPortldd", typeof(Grupo_EftcPortldd_ComplexType))]
      [System.Xml.Serialization.XmlElementAttribute("Grupo_ACTC204_PortlddAprovd", typeof(Grupo_ACTC204_PortlddAprovComplexType))]
      [System.Xml.Serialization.XmlElementAttribute("Grupo_ACTC204_PortlddCancel", typeof(Grupo_PortlddCancel_ComplexType))]
      [System.Xml.Serialization.XmlElementAttribute("Grupo_ACTC204_PortlddRetd", typeof(Grupo_ACTC20x_PortlddRetdComplexType))]
      [System.Xml.Serialization.XmlElementAttribute("Grupo_ACTC204_SitLiquidPortldd", typeof(Grupo_SitLiquidPortldd_ComplexType))]
      public object Item
      {
         get
         {
            return this.itemField;
         }
         set
         {
            this.itemField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC204.xsd")]
   public partial class Grupo_EftcPortldd_ComplexType
   {

      private System.DateTime dtEftcPortlddField;

      private string sitEftcPortlddField;

      private decimal vlrRCOField;

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
      public System.DateTime DtEftcPortldd
      {
         get
         {
            return this.dtEftcPortlddField;
         }
         set
         {
            this.dtEftcPortlddField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
      public string SitEftcPortldd
      {
         get
         {
            return this.sitEftcPortlddField;
         }
         set
         {
            this.sitEftcPortlddField = value;
         }
      }

      /// <remarks/>
      public decimal VlrRCO
      {
         get
         {
            return this.vlrRCOField;
         }
         set
         {
            this.vlrRCOField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC204.xsd")]
   public partial class Grupo_ACTC204_PortlddAprovComplexType
   {

      private string codContrtoOrField;

      private string codContrtoSCRField;

      private string iPOCField;

      private Indr ind_MultIPOCField;

      private string cNPJBase_IFOrContrtoField;

      private string tpContrtoField;

      private System.DateTime dtContrOpField;

      private Grupo_CalcSaldDevdrComplexType[] grupo_ACTC204_CalcSaldDevdrField;

      private string tpTxField;

      private decimal txJurosNomlField;

      private decimal txJurosEftField;

      private string codMoedaField;

      private string indRemunField;

      private string regmAmtzcField;

      private decimal vlrTarMesAtlField;

      private string enqdmntContrtoField;

      private decimal iOFRecContrtoOrigField;

      private bool iOFRecContrtoOrigFieldSpecified;

      private string qtdTotParclContrtoField;

      private System.DateTime dtUltParclPagaField;

      private System.DateTime dtUltParclVencdField;

      private decimal vlrUltParclVencdField;

      private System.DateTime dtVencUltParclField;

      private string przRemnstContrtoField;

      private Indr usoFGTS_PPPField;

      private bool usoFGTS_PPPFieldSpecified;

      private decimal percPPPUtzField;

      private bool percPPPUtzFieldSpecified;

      private string qtdParclRemnstFGTS_PPPField;

      private decimal vlrFGTSNUtzTotSacdField;

      private bool vlrFGTSNUtzTotSacdFieldSpecified;

      private string cNPJIFOrigdrField;

      private string iSPBBcoIFOrigdrField;

      private string codBcoIFOrigdrField;

      private string agBancIFOrigdrField;

      private string ctBancIFOrigdrField;

      private string emailConttoIFOrigdrField;

      private string telConttoIFOrigdrField;

      /// <remarks/>
      public string CodContrtoOr
      {
         get
         {
            return this.codContrtoOrField;
         }
         set
         {
            this.codContrtoOrField = value;
         }
      }

      /// <remarks/>
      public string CodContrtoSCR
      {
         get
         {
            return this.codContrtoSCRField;
         }
         set
         {
            this.codContrtoSCRField = value;
         }
      }

      /// <remarks/>
      public string IPOC
      {
         get
         {
            return this.iPOCField;
         }
         set
         {
            this.iPOCField = value;
         }
      }

      /// <remarks/>
      public Indr Ind_MultIPOC
      {
         get
         {
            return this.ind_MultIPOCField;
         }
         set
         {
            this.ind_MultIPOCField = value;
         }
      }

      /// <remarks/>
      public string CNPJBase_IFOrContrto
      {
         get
         {
            return this.cNPJBase_IFOrContrtoField;
         }
         set
         {
            this.cNPJBase_IFOrContrtoField = value;
         }
      }

      /// <remarks/>
      public string TpContrto
      {
         get
         {
            return this.tpContrtoField;
         }
         set
         {
            this.tpContrtoField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
      public System.DateTime DtContrOp
      {
         get
         {
            return this.dtContrOpField;
         }
         set
         {
            this.dtContrOpField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute("Grupo_ACTC204_CalcSaldDevdr")]
      public Grupo_CalcSaldDevdrComplexType[] Grupo_ACTC204_CalcSaldDevdr
      {
         get
         {
            return this.grupo_ACTC204_CalcSaldDevdrField;
         }
         set
         {
            this.grupo_ACTC204_CalcSaldDevdrField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
      public string TpTx
      {
         get
         {
            return this.tpTxField;
         }
         set
         {
            this.tpTxField = value;
         }
      }

      /// <remarks/>
      public decimal TxJurosNoml
      {
         get
         {
            return this.txJurosNomlField;
         }
         set
         {
            this.txJurosNomlField = value;
         }
      }

      /// <remarks/>
      public decimal TxJurosEft
      {
         get
         {
            return this.txJurosEftField;
         }
         set
         {
            this.txJurosEftField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
      public string CodMoeda
      {
         get
         {
            return this.codMoedaField;
         }
         set
         {
            this.codMoedaField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
      public string IndRemun
      {
         get
         {
            return this.indRemunField;
         }
         set
         {
            this.indRemunField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
      public string RegmAmtzc
      {
         get
         {
            return this.regmAmtzcField;
         }
         set
         {
            this.regmAmtzcField = value;
         }
      }

      /// <remarks/>
      public decimal VlrTarMesAtl
      {
         get
         {
            return this.vlrTarMesAtlField;
         }
         set
         {
            this.vlrTarMesAtlField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
      public string EnqdmntContrto
      {
         get
         {
            return this.enqdmntContrtoField;
         }
         set
         {
            this.enqdmntContrtoField = value;
         }
      }

      /// <remarks/>
      public decimal IOFRecContrtoOrig
      {
         get
         {
            return this.iOFRecContrtoOrigField;
         }
         set
         {
            this.iOFRecContrtoOrigField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlIgnoreAttribute()]
      public bool IOFRecContrtoOrigSpecified
      {
         get
         {
            return this.iOFRecContrtoOrigFieldSpecified;
         }
         set
         {
            this.iOFRecContrtoOrigFieldSpecified = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
      public string QtdTotParclContrto
      {
         get
         {
            return this.qtdTotParclContrtoField;
         }
         set
         {
            this.qtdTotParclContrtoField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
      public System.DateTime DtUltParclPaga
      {
         get
         {
            return this.dtUltParclPagaField;
         }
         set
         {
            this.dtUltParclPagaField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
      public System.DateTime DtUltParclVencd
      {
         get
         {
            return this.dtUltParclVencdField;
         }
         set
         {
            this.dtUltParclVencdField = value;
         }
      }

      /// <remarks/>
      public decimal VlrUltParclVencd
      {
         get
         {
            return this.vlrUltParclVencdField;
         }
         set
         {
            this.vlrUltParclVencdField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
      public System.DateTime DtVencUltParcl
      {
         get
         {
            return this.dtVencUltParclField;
         }
         set
         {
            this.dtVencUltParclField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
      public string PrzRemnstContrto
      {
         get
         {
            return this.przRemnstContrtoField;
         }
         set
         {
            this.przRemnstContrtoField = value;
         }
      }

      /// <remarks/>
      public Indr UsoFGTS_PPP
      {
         get
         {
            return this.usoFGTS_PPPField;
         }
         set
         {
            this.usoFGTS_PPPField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlIgnoreAttribute()]
      public bool UsoFGTS_PPPSpecified
      {
         get
         {
            return this.usoFGTS_PPPFieldSpecified;
         }
         set
         {
            this.usoFGTS_PPPFieldSpecified = value;
         }
      }

      /// <remarks/>
      public decimal PercPPPUtz
      {
         get
         {
            return this.percPPPUtzField;
         }
         set
         {
            this.percPPPUtzField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlIgnoreAttribute()]
      public bool PercPPPUtzSpecified
      {
         get
         {
            return this.percPPPUtzFieldSpecified;
         }
         set
         {
            this.percPPPUtzFieldSpecified = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
      public string QtdParclRemnstFGTS_PPP
      {
         get
         {
            return this.qtdParclRemnstFGTS_PPPField;
         }
         set
         {
            this.qtdParclRemnstFGTS_PPPField = value;
         }
      }

      /// <remarks/>
      public decimal VlrFGTSNUtzTotSacd
      {
         get
         {
            return this.vlrFGTSNUtzTotSacdField;
         }
         set
         {
            this.vlrFGTSNUtzTotSacdField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlIgnoreAttribute()]
      public bool VlrFGTSNUtzTotSacdSpecified
      {
         get
         {
            return this.vlrFGTSNUtzTotSacdFieldSpecified;
         }
         set
         {
            this.vlrFGTSNUtzTotSacdFieldSpecified = value;
         }
      }

      /// <remarks/>
      public string CNPJIFOrigdr
      {
         get
         {
            return this.cNPJIFOrigdrField;
         }
         set
         {
            this.cNPJIFOrigdrField = value;
         }
      }

      /// <remarks/>
      public string ISPBBcoIFOrigdr
      {
         get
         {
            return this.iSPBBcoIFOrigdrField;
         }
         set
         {
            this.iSPBBcoIFOrigdrField = value;
         }
      }

      /// <remarks/>
      public string CodBcoIFOrigdr
      {
         get
         {
            return this.codBcoIFOrigdrField;
         }
         set
         {
            this.codBcoIFOrigdrField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
      public string AgBancIFOrigdr
      {
         get
         {
            return this.agBancIFOrigdrField;
         }
         set
         {
            this.agBancIFOrigdrField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
      public string CtBancIFOrigdr
      {
         get
         {
            return this.ctBancIFOrigdrField;
         }
         set
         {
            this.ctBancIFOrigdrField = value;
         }
      }

      /// <remarks/>
      public string EmailConttoIFOrigdr
      {
         get
         {
            return this.emailConttoIFOrigdrField;
         }
         set
         {
            this.emailConttoIFOrigdrField = value;
         }
      }

      /// <remarks/>
      public string TelConttoIFOrigdr
      {
         get
         {
            return this.telConttoIFOrigdrField;
         }
         set
         {
            this.telConttoIFOrigdrField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC204.xsd")]
   public partial class Grupo_CalcSaldDevdrComplexType
   {

      private Data_CodErro dtRefCalcSaldDevdrField;

      private Valor_CodErro vlrCalcSaldDevdrField;

      private string codErroField;

      /// <remarks/>
      public Data_CodErro DtRefCalcSaldDevdr
      {
         get
         {
            return this.dtRefCalcSaldDevdrField;
         }
         set
         {
            this.dtRefCalcSaldDevdrField = value;
         }
      }

      /// <remarks/>
      public Valor_CodErro VlrCalcSaldDevdr
      {
         get
         {
            return this.vlrCalcSaldDevdrField;
         }
         set
         {
            this.vlrCalcSaldDevdrField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string CodErro
      {
         get
         {
            return this.codErroField;
         }
         set
         {
            this.codErroField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC204.xsd")]
   public partial class Data_CodErro
   {

      private string codErroField;

      private System.DateTime valueField;

      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string CodErro
      {
         get
         {
            return this.codErroField;
         }
         set
         {
            this.codErroField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlTextAttribute(DataType = "date")]
      public System.DateTime Value
      {
         get
         {
            return this.valueField;
         }
         set
         {
            this.valueField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC204.xsd")]
   public partial class Valor_CodErro
   {

      private string codErroField;

      private decimal valueField;

      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string CodErro
      {
         get
         {
            return this.codErroField;
         }
         set
         {
            this.codErroField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlTextAttribute()]
      public decimal Value
      {
         get
         {
            return this.valueField;
         }
         set
         {
            this.valueField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC204.xsd")]
   public partial class Grupo_PortlddCancel_ComplexType
   {

      private string mtvCanceltPortlddField;

      private System.DateTime dtCanceltPortlddField;

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
      public string MtvCanceltPortldd
      {
         get
         {
            return this.mtvCanceltPortlddField;
         }
         set
         {
            this.mtvCanceltPortlddField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
      public System.DateTime DtCanceltPortldd
      {
         get
         {
            return this.dtCanceltPortlddField;
         }
         set
         {
            this.dtCanceltPortlddField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC204.xsd")]
   public partial class Grupo_ACTC20x_PortlddRetdComplexType
   {

      private MtvRetenContrto_CodErro mtvRetenContrtoField;

      private Data_CodErro dtRetenContrtoField;

      private TpContrto_CodErro tpContrtoOrField;

      private CPF_CodErro cPF_TitlrField;

      private CondcDivgte_CodErro[] condcDivgteField;

      private CNPJ_CodErro[] cNPJCesField;

      private string codErroField;

      /// <remarks/>
      public MtvRetenContrto_CodErro MtvRetenContrto
      {
         get
         {
            return this.mtvRetenContrtoField;
         }
         set
         {
            this.mtvRetenContrtoField = value;
         }
      }

      /// <remarks/>
      public Data_CodErro DtRetenContrto
      {
         get
         {
            return this.dtRetenContrtoField;
         }
         set
         {
            this.dtRetenContrtoField = value;
         }
      }

      /// <remarks/>
      public TpContrto_CodErro TpContrtoOr
      {
         get
         {
            return this.tpContrtoOrField;
         }
         set
         {
            this.tpContrtoOrField = value;
         }
      }

      /// <remarks/>
      public CPF_CodErro CPF_Titlr
      {
         get
         {
            return this.cPF_TitlrField;
         }
         set
         {
            this.cPF_TitlrField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute("CondcDivgte")]
      public CondcDivgte_CodErro[] CondcDivgte
      {
         get
         {
            return this.condcDivgteField;
         }
         set
         {
            this.condcDivgteField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute("CNPJCes")]
      public CNPJ_CodErro[] CNPJCes
      {
         get
         {
            return this.cNPJCesField;
         }
         set
         {
            this.cNPJCesField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string CodErro
      {
         get
         {
            return this.codErroField;
         }
         set
         {
            this.codErroField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC204.xsd")]
   public partial class MtvRetenContrto_CodErro
   {

      private string codErroField;

      private string valueField;

      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string CodErro
      {
         get
         {
            return this.codErroField;
         }
         set
         {
            this.codErroField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlTextAttribute(DataType = "integer")]
      public string Value
      {
         get
         {
            return this.valueField;
         }
         set
         {
            this.valueField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC204.xsd")]
   public partial class TpContrto_CodErro
   {

      private string codErroField;

      private string valueField;

      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string CodErro
      {
         get
         {
            return this.codErroField;
         }
         set
         {
            this.codErroField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlTextAttribute()]
      public string Value
      {
         get
         {
            return this.valueField;
         }
         set
         {
            this.valueField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC204.xsd")]
   public partial class CPF_CodErro
   {

      private string codErroField;

      private string valueField;

      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string CodErro
      {
         get
         {
            return this.codErroField;
         }
         set
         {
            this.codErroField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlTextAttribute()]
      public string Value
      {
         get
         {
            return this.valueField;
         }
         set
         {
            this.valueField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC204.xsd")]
   public partial class CondcDivgte_CodErro
   {

      private string codErroField;

      private string valueField;

      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string CodErro
      {
         get
         {
            return this.codErroField;
         }
         set
         {
            this.codErroField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlTextAttribute(DataType = "integer")]
      public string Value
      {
         get
         {
            return this.valueField;
         }
         set
         {
            this.valueField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC204.xsd")]
   public partial class CNPJ_CodErro
   {

      private string codErroField;

      private string valueField;

      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string CodErro
      {
         get
         {
            return this.codErroField;
         }
         set
         {
            this.codErroField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlTextAttribute()]
      public string Value
      {
         get
         {
            return this.valueField;
         }
         set
         {
            this.valueField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC204.xsd")]
   public partial class Grupo_SitLiquidPortldd_ComplexType
   {

      private string sitLiquidPortlddField;

      private System.DateTime dtSitLiquidPortlddField;

      private string mtvDevLiquidPortlddField;

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
      public string SitLiquidPortldd
      {
         get
         {
            return this.sitLiquidPortlddField;
         }
         set
         {
            this.sitLiquidPortlddField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
      public System.DateTime DtSitLiquidPortldd
      {
         get
         {
            return this.dtSitLiquidPortlddField;
         }
         set
         {
            this.dtSitLiquidPortlddField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
      public string MtvDevLiquidPortldd
      {
         get
         {
            return this.mtvDevLiquidPortlddField;
         }
         set
         {
            this.mtvDevLiquidPortlddField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC204.xsd")]
   public partial class SISARQComplexType
   {

      private ACTC204ComplexType itemField;

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute("ACTC204")]
      public ACTC204ComplexType Item
      {
         get
         {
            return this.itemField;
         }
         set
         {
            this.itemField = value;
         }
      }
   }
}
