//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace FastConsig.CTC.Model.ACTC602
{
   using FastConsig.CTC.Model.Interfaces;
   using System.Xml.Serialization;


   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC602.xsd")]
   [System.Xml.Serialization.XmlRootAttribute("ACTCDOC", Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC602.xsd", IsNullable = false)]
   public partial class ACTC602 : IACTC
   {

      private BCARQComplexType bCARQField;

      private SISARQComplexType sISARQField;

      private string eSTARQField;

      /// <remarks/>
      public BCARQComplexType BCARQ
      {
         get
         {
            return this.bCARQField;
         }
         set
         {
            this.bCARQField = value;
         }
      }

      /// <remarks/>
      public SISARQComplexType SISARQ
      {
         get
         {
            return this.sISARQField;
         }
         set
         {
            this.sISARQField = value;
         }
      }

      /// <remarks/>
      public string ESTARQ
      {
         get
         {
            return this.eSTARQField;
         }
         set
         {
            this.eSTARQField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC602.xsd")]
   public partial class BCARQComplexType
   {

      private string nomArqField;

      private string numCtrlEmisField;

      private string numCtrlDestOrField;

      private string iSPBEmissorField;

      private string iSPBDestinatarioField;

      private System.DateTime dtHrArqField;

      private string sitReqField;

      private Grupo_SeqComplexType grupo_SeqField;

      private System.DateTime dtRefField;

      /// <remarks/>
      public string NomArq
      {
         get
         {
            return this.nomArqField;
         }
         set
         {
            this.nomArqField = value;
         }
      }

      /// <remarks/>
      public string NumCtrlEmis
      {
         get
         {
            return this.numCtrlEmisField;
         }
         set
         {
            this.numCtrlEmisField = value;
         }
      }

      /// <remarks/>
      public string NumCtrlDestOr
      {
         get
         {
            return this.numCtrlDestOrField;
         }
         set
         {
            this.numCtrlDestOrField = value;
         }
      }

      /// <remarks/>
      public string ISPBEmissor
      {
         get
         {
            return this.iSPBEmissorField;
         }
         set
         {
            this.iSPBEmissorField = value;
         }
      }

      /// <remarks/>
      public string ISPBDestinatario
      {
         get
         {
            return this.iSPBDestinatarioField;
         }
         set
         {
            this.iSPBDestinatarioField = value;
         }
      }

      /// <remarks/>
      public System.DateTime DtHrArq
      {
         get
         {
            return this.dtHrArqField;
         }
         set
         {
            this.dtHrArqField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
      public string SitReq
      {
         get
         {
            return this.sitReqField;
         }
         set
         {
            this.sitReqField = value;
         }
      }

      /// <remarks/>
      public Grupo_SeqComplexType Grupo_Seq
      {
         get
         {
            return this.grupo_SeqField;
         }
         set
         {
            this.grupo_SeqField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
      public System.DateTime DtRef
      {
         get
         {
            return this.dtRefField;
         }
         set
         {
            this.dtRefField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC602.xsd")]
   public partial class Grupo_SeqComplexType
   {

      private string numSeqField;

      private Indr indrContField;

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
      public string NumSeq
      {
         get
         {
            return this.numSeqField;
         }
         set
         {
            this.numSeqField = value;
         }
      }

      /// <remarks/>
      public Indr IndrCont
      {
         get
         {
            return this.indrContField;
         }
         set
         {
            this.indrContField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC602.xsd")]
   public enum Indr
   {

      /// <remarks/>
      S,

      /// <remarks/>
      N,
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC602.xsd")]
   public partial class ACTC602ComplexType
   {

      private Grupo_ACTC602_PortlddComplexType[] grupo_ACTC602_PortlddField;

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute("Grupo_ACTC602_Portldd")]
      public Grupo_ACTC602_PortlddComplexType[] Grupo_ACTC602_Portldd
      {
         get
         {
            return this.grupo_ACTC602_PortlddField;
         }
         set
         {
            this.grupo_ACTC602_PortlddField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC602.xsd")]
   public partial class Grupo_ACTC602_PortlddComplexType
   {

      private string identdPartAdmdoField;

      private string nUPortlddCTCField;

      private string identdIFPropntField;

      private Grupo_ACTC60X_IdentdContrtoComplexType grupo_ACTC602_IdentdContrtoField;

      private Grupo_ACTC_CliComplexType_CodErro grupo_ACTC602_CliField;

      private Grupo_ACTC602_PropPortlddComplexType grupo_ACTC602_PropPortlddField;

      private Grupo_EndCartaPortldd_ComplexType grupo_ACTC602_EndCartaPortlddField;

      /// <remarks/>
      public string IdentdPartAdmdo
      {
         get
         {
            return this.identdPartAdmdoField;
         }
         set
         {
            this.identdPartAdmdoField = value;
         }
      }

      /// <remarks/>
      public string NUPortlddCTC
      {
         get
         {
            return this.nUPortlddCTCField;
         }
         set
         {
            this.nUPortlddCTCField = value;
         }
      }

      /// <remarks/>
      public string IdentdIFPropnt
      {
         get
         {
            return this.identdIFPropntField;
         }
         set
         {
            this.identdIFPropntField = value;
         }
      }

      /// <remarks/>
      public Grupo_ACTC60X_IdentdContrtoComplexType Grupo_ACTC602_IdentdContrto
      {
         get
         {
            return this.grupo_ACTC602_IdentdContrtoField;
         }
         set
         {
            this.grupo_ACTC602_IdentdContrtoField = value;
         }
      }

      /// <remarks/>
      public Grupo_ACTC_CliComplexType_CodErro Grupo_ACTC602_Cli
      {
         get
         {
            return this.grupo_ACTC602_CliField;
         }
         set
         {
            this.grupo_ACTC602_CliField = value;
         }
      }

      /// <remarks/>
      public Grupo_ACTC602_PropPortlddComplexType Grupo_ACTC602_PropPortldd
      {
         get
         {
            return this.grupo_ACTC602_PropPortlddField;
         }
         set
         {
            this.grupo_ACTC602_PropPortlddField = value;
         }
      }

      /// <remarks/>
      public Grupo_EndCartaPortldd_ComplexType Grupo_ACTC602_EndCartaPortldd
      {
         get
         {
            return this.grupo_ACTC602_EndCartaPortlddField;
         }
         set
         {
            this.grupo_ACTC602_EndCartaPortlddField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC602.xsd")]
   public partial class Grupo_ACTC60X_IdentdContrtoComplexType : Grupo_IdentdContrto_ComplexType_1
   {

      private TpCt_CodErro tpCtField;

      private Agencia_CodErro agCliField;

      private CtBancaria_CodErro ctCliField;

      private CtPagto_CodErro ctPagtoField;

      private CtConjtaSoldria_CodErro ctConjtaSoldriaField;

      /// <remarks/>
      public TpCt_CodErro TpCt
      {
         get
         {
            return this.tpCtField;
         }
         set
         {
            this.tpCtField = value;
         }
      }

      /// <remarks/>
      public Agencia_CodErro AgCli
      {
         get
         {
            return this.agCliField;
         }
         set
         {
            this.agCliField = value;
         }
      }

      /// <remarks/>
      public CtBancaria_CodErro CtCli
      {
         get
         {
            return this.ctCliField;
         }
         set
         {
            this.ctCliField = value;
         }
      }

      /// <remarks/>
      public CtPagto_CodErro CtPagto
      {
         get
         {
            return this.ctPagtoField;
         }
         set
         {
            this.ctPagtoField = value;
         }
      }

      /// <remarks/>
      public CtConjtaSoldria_CodErro CtConjtaSoldria
      {
         get
         {
            return this.ctConjtaSoldriaField;
         }
         set
         {
            this.ctConjtaSoldriaField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC602.xsd")]
   public partial class TpCt_CodErro
   {

      private string codErroField;

      private string valueField;

      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string CodErro
      {
         get
         {
            return this.codErroField;
         }
         set
         {
            this.codErroField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlTextAttribute()]
      public string Value
      {
         get
         {
            return this.valueField;
         }
         set
         {
            this.valueField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC602.xsd")]
   public partial class Agencia_CodErro
   {

      private string codErroField;

      private string valueField;

      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string CodErro
      {
         get
         {
            return this.codErroField;
         }
         set
         {
            this.codErroField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlTextAttribute(DataType = "integer")]
      public string Value
      {
         get
         {
            return this.valueField;
         }
         set
         {
            this.valueField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC602.xsd")]
   public partial class CtBancaria_CodErro
   {

      private string codErroField;

      private string valueField;

      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string CodErro
      {
         get
         {
            return this.codErroField;
         }
         set
         {
            this.codErroField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlTextAttribute(DataType = "integer")]
      public string Value
      {
         get
         {
            return this.valueField;
         }
         set
         {
            this.valueField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC602.xsd")]
   public partial class CtPagto_CodErro
   {

      private string codErroField;

      private string valueField;

      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string CodErro
      {
         get
         {
            return this.codErroField;
         }
         set
         {
            this.codErroField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlTextAttribute(DataType = "integer")]
      public string Value
      {
         get
         {
            return this.valueField;
         }
         set
         {
            this.valueField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC602.xsd")]
   public partial class CtConjtaSoldria_CodErro
   {

      private string codErroField;

      private CtConjtaSoldria valueField;

      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string CodErro
      {
         get
         {
            return this.codErroField;
         }
         set
         {
            this.codErroField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlTextAttribute()]
      public CtConjtaSoldria Value
      {
         get
         {
            return this.valueField;
         }
         set
         {
            this.valueField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC602.xsd")]
   public enum CtConjtaSoldria
   {

      /// <remarks/>
      S,

      /// <remarks/>
      N,
   }

   /// <remarks/>
   [System.Xml.Serialization.XmlIncludeAttribute(typeof(Grupo_ACTC60X_IdentdContrtoComplexType))]
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC602.xsd")]
   public partial class Grupo_IdentdContrto_ComplexType_1 : Grupo_IdentdContrto_ComplexType
   {

      private CNPJ_CodErro cNPJCorrespBancField;

      /// <remarks/>
      public CNPJ_CodErro CNPJCorrespBanc
      {
         get
         {
            return this.cNPJCorrespBancField;
         }
         set
         {
            this.cNPJCorrespBancField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC602.xsd")]
   public partial class CNPJ_CodErro
   {

      private string codErroField;

      private string valueField;

      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string CodErro
      {
         get
         {
            return this.codErroField;
         }
         set
         {
            this.codErroField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlTextAttribute()]
      public string Value
      {
         get
         {
            return this.valueField;
         }
         set
         {
            this.valueField = value;
         }
      }
   }

   /// <remarks/>
   [System.Xml.Serialization.XmlIncludeAttribute(typeof(Grupo_ACTC701_IdentdContrtoComplexType))]
   [System.Xml.Serialization.XmlIncludeAttribute(typeof(Grupo_ACTC70X_IdentdContrtoComplexType))]
   [System.Xml.Serialization.XmlIncludeAttribute(typeof(Grupo_ACTC10X_IdentdContrtoComplexType))]
   [System.Xml.Serialization.XmlIncludeAttribute(typeof(Grupo_IdentdContrto_ComplexType_1))]
   [System.Xml.Serialization.XmlIncludeAttribute(typeof(Grupo_ACTC60X_IdentdContrtoComplexType))]
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC602.xsd")]
   public partial class Grupo_IdentdContrto_ComplexType
   {

      private CodContrtoOr_CodErro codContrtoOrField;

      private CNPJBase_CodErro cNPJBase_IFOrContrtoField;

      private TpContrto_CodErro tpContrtoField;

      private string codErroField;

      /// <remarks/>
      public CodContrtoOr_CodErro CodContrtoOr
      {
         get
         {
            return this.codContrtoOrField;
         }
         set
         {
            this.codContrtoOrField = value;
         }
      }

      /// <remarks/>
      public CNPJBase_CodErro CNPJBase_IFOrContrto
      {
         get
         {
            return this.cNPJBase_IFOrContrtoField;
         }
         set
         {
            this.cNPJBase_IFOrContrtoField = value;
         }
      }

      /// <remarks/>
      public TpContrto_CodErro TpContrto
      {
         get
         {
            return this.tpContrtoField;
         }
         set
         {
            this.tpContrtoField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string CodErro
      {
         get
         {
            return this.codErroField;
         }
         set
         {
            this.codErroField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC602.xsd")]
   public partial class CodContrtoOr_CodErro
   {

      private string codErroField;

      private string valueField;

      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string CodErro
      {
         get
         {
            return this.codErroField;
         }
         set
         {
            this.codErroField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlTextAttribute()]
      public string Value
      {
         get
         {
            return this.valueField;
         }
         set
         {
            this.valueField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC602.xsd")]
   public partial class CNPJBase_CodErro
   {

      private string codErroField;

      private string valueField;

      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string CodErro
      {
         get
         {
            return this.codErroField;
         }
         set
         {
            this.codErroField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlTextAttribute()]
      public string Value
      {
         get
         {
            return this.valueField;
         }
         set
         {
            this.valueField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC602.xsd")]
   public partial class TpContrto_CodErro
   {

      private string codErroField;

      private string valueField;

      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string CodErro
      {
         get
         {
            return this.codErroField;
         }
         set
         {
            this.codErroField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlTextAttribute()]
      public string Value
      {
         get
         {
            return this.valueField;
         }
         set
         {
            this.valueField = value;
         }
      }
   }

   /// <remarks/>
   [System.Xml.Serialization.XmlIncludeAttribute(typeof(Grupo_ACTC70X_IdentdContrtoComplexType))]
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC602.xsd")]
   public partial class Grupo_ACTC701_IdentdContrtoComplexType : Grupo_IdentdContrto_ComplexType
   {

      private TpEnteCons_CodErro tpEnteConsField;

      private CNPJ_CodErro cNPJCorrespBancField;

      /// <remarks/>
      public TpEnteCons_CodErro TpEnteCons
      {
         get
         {
            return this.tpEnteConsField;
         }
         set
         {
            this.tpEnteConsField = value;
         }
      }

      /// <remarks/>
      public CNPJ_CodErro CNPJCorrespBanc
      {
         get
         {
            return this.cNPJCorrespBancField;
         }
         set
         {
            this.cNPJCorrespBancField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC602.xsd")]
   public partial class TpEnteCons_CodErro
   {

      private string codErroField;

      private string valueField;

      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string CodErro
      {
         get
         {
            return this.codErroField;
         }
         set
         {
            this.codErroField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlTextAttribute(DataType = "integer")]
      public string Value
      {
         get
         {
            return this.valueField;
         }
         set
         {
            this.valueField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC602.xsd")]
   public partial class Grupo_ACTC70X_IdentdContrtoComplexType : Grupo_ACTC701_IdentdContrtoComplexType
   {

      private TpCt_CodErro tpCtField;

      private Agencia_CodErro agCliField;

      private CtBancaria_CodErro ctCliField;

      private CtPagto_CodErro ctPagtoField;

      private CtConjtaSoldria_CodErro ctConjtaSoldriaField;

      /// <remarks/>
      public TpCt_CodErro TpCt
      {
         get
         {
            return this.tpCtField;
         }
         set
         {
            this.tpCtField = value;
         }
      }

      /// <remarks/>
      public Agencia_CodErro AgCli
      {
         get
         {
            return this.agCliField;
         }
         set
         {
            this.agCliField = value;
         }
      }

      /// <remarks/>
      public CtBancaria_CodErro CtCli
      {
         get
         {
            return this.ctCliField;
         }
         set
         {
            this.ctCliField = value;
         }
      }

      /// <remarks/>
      public CtPagto_CodErro CtPagto
      {
         get
         {
            return this.ctPagtoField;
         }
         set
         {
            this.ctPagtoField = value;
         }
      }

      /// <remarks/>
      public CtConjtaSoldria_CodErro CtConjtaSoldria
      {
         get
         {
            return this.ctConjtaSoldriaField;
         }
         set
         {
            this.ctConjtaSoldriaField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC602.xsd")]
   public partial class Grupo_ACTC10X_IdentdContrtoComplexType : Grupo_IdentdContrto_ComplexType
   {

      private TpEnteCons_CodErro tpEnteConsField;

      private CNPJ_CodErro cNPJCorrespBancField;

      /// <remarks/>
      public TpEnteCons_CodErro TpEnteCons
      {
         get
         {
            return this.tpEnteConsField;
         }
         set
         {
            this.tpEnteConsField = value;
         }
      }

      /// <remarks/>
      public CNPJ_CodErro CNPJCorrespBanc
      {
         get
         {
            return this.cNPJCorrespBancField;
         }
         set
         {
            this.cNPJCorrespBancField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC602.xsd")]
   public partial class Grupo_ACTC_CliComplexType_CodErro
   {

      private TpPessoa_CodErro tpCliField;

      private CNPJ_CPF_CodErro cNPJ_CPFCliField;

      private Nome_CodErro nomCliField;

      private Telefone_CodErro telCliField;

      private Email_CodErro emailCliField;

      private Texto_CodErro logradEndCliField;

      private Texto_CodErro compEndCliField;

      private NumEnd_CodErro numEndCliField;

      private CidEnd_CodErro cidEndCliField;

      private UF_CodErro uFEndCliField;

      private CEP_CodErro cEPEndCliField;

      private string codErroField;

      /// <remarks/>
      public TpPessoa_CodErro TpCli
      {
         get
         {
            return this.tpCliField;
         }
         set
         {
            this.tpCliField = value;
         }
      }

      /// <remarks/>
      public CNPJ_CPF_CodErro CNPJ_CPFCli
      {
         get
         {
            return this.cNPJ_CPFCliField;
         }
         set
         {
            this.cNPJ_CPFCliField = value;
         }
      }

      /// <remarks/>
      public Nome_CodErro NomCli
      {
         get
         {
            return this.nomCliField;
         }
         set
         {
            this.nomCliField = value;
         }
      }

      /// <remarks/>
      public Telefone_CodErro TelCli
      {
         get
         {
            return this.telCliField;
         }
         set
         {
            this.telCliField = value;
         }
      }

      /// <remarks/>
      public Email_CodErro EmailCli
      {
         get
         {
            return this.emailCliField;
         }
         set
         {
            this.emailCliField = value;
         }
      }

      /// <remarks/>
      public Texto_CodErro LogradEndCli
      {
         get
         {
            return this.logradEndCliField;
         }
         set
         {
            this.logradEndCliField = value;
         }
      }

      /// <remarks/>
      public Texto_CodErro CompEndCli
      {
         get
         {
            return this.compEndCliField;
         }
         set
         {
            this.compEndCliField = value;
         }
      }

      /// <remarks/>
      public NumEnd_CodErro NumEndCli
      {
         get
         {
            return this.numEndCliField;
         }
         set
         {
            this.numEndCliField = value;
         }
      }

      /// <remarks/>
      public CidEnd_CodErro CidEndCli
      {
         get
         {
            return this.cidEndCliField;
         }
         set
         {
            this.cidEndCliField = value;
         }
      }

      /// <remarks/>
      public UF_CodErro UFEndCli
      {
         get
         {
            return this.uFEndCliField;
         }
         set
         {
            this.uFEndCliField = value;
         }
      }

      /// <remarks/>
      public CEP_CodErro CEPEndCli
      {
         get
         {
            return this.cEPEndCliField;
         }
         set
         {
            this.cEPEndCliField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string CodErro
      {
         get
         {
            return this.codErroField;
         }
         set
         {
            this.codErroField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC602.xsd")]
   public partial class TpPessoa_CodErro
   {

      private string codErroField;

      private TpPessoa valueField;

      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string CodErro
      {
         get
         {
            return this.codErroField;
         }
         set
         {
            this.codErroField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlTextAttribute()]
      public TpPessoa Value
      {
         get
         {
            return this.valueField;
         }
         set
         {
            this.valueField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC602.xsd")]
   public enum TpPessoa
   {

      /// <remarks/>
      F,

      /// <remarks/>
      J,
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC602.xsd")]
   public partial class CNPJ_CPF_CodErro
   {

      private string codErroField;

      private string valueField;

      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string CodErro
      {
         get
         {
            return this.codErroField;
         }
         set
         {
            this.codErroField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlTextAttribute()]
      public string Value
      {
         get
         {
            return this.valueField;
         }
         set
         {
            this.valueField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC602.xsd")]
   public partial class Nome_CodErro
   {

      private string codErroField;

      private string valueField;

      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string CodErro
      {
         get
         {
            return this.codErroField;
         }
         set
         {
            this.codErroField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlTextAttribute()]
      public string Value
      {
         get
         {
            return this.valueField;
         }
         set
         {
            this.valueField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC602.xsd")]
   public partial class Telefone_CodErro
   {

      private string codErroField;

      private string valueField;

      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string CodErro
      {
         get
         {
            return this.codErroField;
         }
         set
         {
            this.codErroField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlTextAttribute()]
      public string Value
      {
         get
         {
            return this.valueField;
         }
         set
         {
            this.valueField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC602.xsd")]
   public partial class Email_CodErro
   {

      private string codErroField;

      private string valueField;

      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string CodErro
      {
         get
         {
            return this.codErroField;
         }
         set
         {
            this.codErroField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlTextAttribute()]
      public string Value
      {
         get
         {
            return this.valueField;
         }
         set
         {
            this.valueField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC602.xsd")]
   public partial class Texto_CodErro
   {

      private string codErroField;

      private string valueField;

      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string CodErro
      {
         get
         {
            return this.codErroField;
         }
         set
         {
            this.codErroField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlTextAttribute()]
      public string Value
      {
         get
         {
            return this.valueField;
         }
         set
         {
            this.valueField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC602.xsd")]
   public partial class NumEnd_CodErro
   {

      private string codErroField;

      private string valueField;

      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string CodErro
      {
         get
         {
            return this.codErroField;
         }
         set
         {
            this.codErroField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlTextAttribute()]
      public string Value
      {
         get
         {
            return this.valueField;
         }
         set
         {
            this.valueField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC602.xsd")]
   public partial class CidEnd_CodErro
   {

      private string codErroField;

      private string valueField;

      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string CodErro
      {
         get
         {
            return this.codErroField;
         }
         set
         {
            this.codErroField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlTextAttribute()]
      public string Value
      {
         get
         {
            return this.valueField;
         }
         set
         {
            this.valueField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC602.xsd")]
   public partial class UF_CodErro
   {

      private string codErroField;

      private string valueField;

      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string CodErro
      {
         get
         {
            return this.codErroField;
         }
         set
         {
            this.codErroField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlTextAttribute()]
      public string Value
      {
         get
         {
            return this.valueField;
         }
         set
         {
            this.valueField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC602.xsd")]
   public partial class CEP_CodErro
   {

      private string codErroField;

      private string valueField;

      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string CodErro
      {
         get
         {
            return this.codErroField;
         }
         set
         {
            this.codErroField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlTextAttribute()]
      public string Value
      {
         get
         {
            return this.valueField;
         }
         set
         {
            this.valueField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC602.xsd")]
   public partial class Grupo_ACTC602_PropPortlddComplexType
   {

      private decimal vlrMaxCobField;

      private System.DateTime dtRefSaldDevdrContbField;

      private string codMoedaField;

      private Grupo_ACTCX01_CheqEspclComplexType grupo_ACTC602_CheqEspclField;

      private Grupo_ACTCX01_AdintDpsitanteComplexType grupo_ACTC602_AdintDpsitanteField;

      /// <remarks/>
      public decimal VlrMaxCob
      {
         get
         {
            return this.vlrMaxCobField;
         }
         set
         {
            this.vlrMaxCobField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
      public System.DateTime DtRefSaldDevdrContb
      {
         get
         {
            return this.dtRefSaldDevdrContbField;
         }
         set
         {
            this.dtRefSaldDevdrContbField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
      public string CodMoeda
      {
         get
         {
            return this.codMoedaField;
         }
         set
         {
            this.codMoedaField = value;
         }
      }

      /// <remarks/>
      public Grupo_ACTCX01_CheqEspclComplexType Grupo_ACTC602_CheqEspcl
      {
         get
         {
            return this.grupo_ACTC602_CheqEspclField;
         }
         set
         {
            this.grupo_ACTC602_CheqEspclField = value;
         }
      }

      /// <remarks/>
      public Grupo_ACTCX01_AdintDpsitanteComplexType Grupo_ACTC602_AdintDpsitante
      {
         get
         {
            return this.grupo_ACTC602_AdintDpsitanteField;
         }
         set
         {
            this.grupo_ACTC602_AdintDpsitanteField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC602.xsd")]
   public partial class Grupo_ACTCX01_CheqEspclComplexType
   {

      private Valor_CodErro vlrSaldDevdrContbField;

      private TpTaxa_CodErro tpTxField;

      private Percentual_CodErro txJurosNomlField;

      private Percentual_CodErro txJurosEftField;

      private Percentual_CodErro txCETField;

      private Percentual_CodErro tarCheqEspclField;

      private Qtd_CodErro qtdDiasIsenField;

      private string codErroField;

      /// <remarks/>
      public Valor_CodErro VlrSaldDevdrContb
      {
         get
         {
            return this.vlrSaldDevdrContbField;
         }
         set
         {
            this.vlrSaldDevdrContbField = value;
         }
      }

      /// <remarks/>
      public TpTaxa_CodErro TpTx
      {
         get
         {
            return this.tpTxField;
         }
         set
         {
            this.tpTxField = value;
         }
      }

      /// <remarks/>
      public Percentual_CodErro TxJurosNoml
      {
         get
         {
            return this.txJurosNomlField;
         }
         set
         {
            this.txJurosNomlField = value;
         }
      }

      /// <remarks/>
      public Percentual_CodErro TxJurosEft
      {
         get
         {
            return this.txJurosEftField;
         }
         set
         {
            this.txJurosEftField = value;
         }
      }

      /// <remarks/>
      public Percentual_CodErro TxCET
      {
         get
         {
            return this.txCETField;
         }
         set
         {
            this.txCETField = value;
         }
      }

      /// <remarks/>
      public Percentual_CodErro TarCheqEspcl
      {
         get
         {
            return this.tarCheqEspclField;
         }
         set
         {
            this.tarCheqEspclField = value;
         }
      }

      /// <remarks/>
      public Qtd_CodErro QtdDiasIsen
      {
         get
         {
            return this.qtdDiasIsenField;
         }
         set
         {
            this.qtdDiasIsenField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string CodErro
      {
         get
         {
            return this.codErroField;
         }
         set
         {
            this.codErroField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC602.xsd")]
   public partial class Valor_CodErro
   {

      private string codErroField;

      private decimal valueField;

      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string CodErro
      {
         get
         {
            return this.codErroField;
         }
         set
         {
            this.codErroField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlTextAttribute()]
      public decimal Value
      {
         get
         {
            return this.valueField;
         }
         set
         {
            this.valueField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC602.xsd")]
   public partial class TpTaxa_CodErro
   {

      private string codErroField;

      private string valueField;

      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string CodErro
      {
         get
         {
            return this.codErroField;
         }
         set
         {
            this.codErroField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlTextAttribute(DataType = "integer")]
      public string Value
      {
         get
         {
            return this.valueField;
         }
         set
         {
            this.valueField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC602.xsd")]
   public partial class Percentual_CodErro
   {

      private string codErroField;

      private decimal valueField;

      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string CodErro
      {
         get
         {
            return this.codErroField;
         }
         set
         {
            this.codErroField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlTextAttribute()]
      public decimal Value
      {
         get
         {
            return this.valueField;
         }
         set
         {
            this.valueField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC602.xsd")]
   public partial class Qtd_CodErro
   {

      private string codErroField;

      private string valueField;

      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string CodErro
      {
         get
         {
            return this.codErroField;
         }
         set
         {
            this.codErroField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlTextAttribute(DataType = "integer")]
      public string Value
      {
         get
         {
            return this.valueField;
         }
         set
         {
            this.valueField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC602.xsd")]
   public partial class Grupo_ACTCX01_AdintDpsitanteComplexType
   {

      private Valor_CodErro vlrSaldDevdrContbADField;

      private TpTaxa_CodErro tpTxADField;

      private Percentual_CodErro txJurosNomlADField;

      private Percentual_CodErro txJurosEftADField;

      private Percentual_CodErro txCETADField;

      private Valor_CodErro tarADField;

      private string codErroField;

      /// <remarks/>
      public Valor_CodErro VlrSaldDevdrContbAD
      {
         get
         {
            return this.vlrSaldDevdrContbADField;
         }
         set
         {
            this.vlrSaldDevdrContbADField = value;
         }
      }

      /// <remarks/>
      public TpTaxa_CodErro TpTxAD
      {
         get
         {
            return this.tpTxADField;
         }
         set
         {
            this.tpTxADField = value;
         }
      }

      /// <remarks/>
      public Percentual_CodErro TxJurosNomlAD
      {
         get
         {
            return this.txJurosNomlADField;
         }
         set
         {
            this.txJurosNomlADField = value;
         }
      }

      /// <remarks/>
      public Percentual_CodErro TxJurosEftAD
      {
         get
         {
            return this.txJurosEftADField;
         }
         set
         {
            this.txJurosEftADField = value;
         }
      }

      /// <remarks/>
      public Percentual_CodErro TxCETAD
      {
         get
         {
            return this.txCETADField;
         }
         set
         {
            this.txCETADField = value;
         }
      }

      /// <remarks/>
      public Valor_CodErro TarAD
      {
         get
         {
            return this.tarADField;
         }
         set
         {
            this.tarADField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string CodErro
      {
         get
         {
            return this.codErroField;
         }
         set
         {
            this.codErroField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC602.xsd")]
   public partial class Grupo_EndCartaPortldd_ComplexType
   {

      private Texto_CodErro logradEndCartaPortlddField;

      private Texto_CodErro compEndCartaPortlddField;

      private NumEnd_CodErro numEndCartaPortlddField;

      private CidEnd_CodErro cidEndCartaPortlddField;

      private UF_CodErro uFEndCartaPortlddField;

      private CEP_CodErro cEPEndCartaPortlddField;

      private string codErroField;

      /// <remarks/>
      public Texto_CodErro LogradEndCartaPortldd
      {
         get
         {
            return this.logradEndCartaPortlddField;
         }
         set
         {
            this.logradEndCartaPortlddField = value;
         }
      }

      /// <remarks/>
      public Texto_CodErro CompEndCartaPortldd
      {
         get
         {
            return this.compEndCartaPortlddField;
         }
         set
         {
            this.compEndCartaPortlddField = value;
         }
      }

      /// <remarks/>
      public NumEnd_CodErro NumEndCartaPortldd
      {
         get
         {
            return this.numEndCartaPortlddField;
         }
         set
         {
            this.numEndCartaPortlddField = value;
         }
      }

      /// <remarks/>
      public CidEnd_CodErro CidEndCartaPortldd
      {
         get
         {
            return this.cidEndCartaPortlddField;
         }
         set
         {
            this.cidEndCartaPortlddField = value;
         }
      }

      /// <remarks/>
      public UF_CodErro UFEndCartaPortldd
      {
         get
         {
            return this.uFEndCartaPortlddField;
         }
         set
         {
            this.uFEndCartaPortlddField = value;
         }
      }

      /// <remarks/>
      public CEP_CodErro CEPEndCartaPortldd
      {
         get
         {
            return this.cEPEndCartaPortlddField;
         }
         set
         {
            this.cEPEndCartaPortlddField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string CodErro
      {
         get
         {
            return this.codErroField;
         }
         set
         {
            this.codErroField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC602.xsd")]
   public partial class SISARQComplexType
   {

      private ACTC602ComplexType itemField;

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute("ACTC602")]
      public ACTC602ComplexType Item
      {
         get
         {
            return this.itemField;
         }
         set
         {
            this.itemField = value;
         }
      }
   }
}
