//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace FastConsig.CTC.Model.ACTC923
{
   using FastConsig.CTC.Model.Interfaces;
   using System.Xml.Serialization;


   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC923.xsd")]
   [System.Xml.Serialization.XmlRootAttribute("ACTCDOC", Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC923.xsd", IsNullable = false)]
   public partial class ACTC923 : IACTC
   {

      private BCARQComplexType_ACTC923 bCARQField;

      private SISARQComplexType_ACTC923 sISARQField;

      private string eSTARQField;

      /// <remarks/>
      public BCARQComplexType_ACTC923 BCARQ
      {
         get
         {
            return this.bCARQField;
         }
         set
         {
            this.bCARQField = value;
         }
      }

      /// <remarks/>
      public SISARQComplexType_ACTC923 SISARQ
      {
         get
         {
            return this.sISARQField;
         }
         set
         {
            this.sISARQField = value;
         }
      }

      /// <remarks/>
      public string ESTARQ
      {
         get
         {
            return this.eSTARQField;
         }
         set
         {
            this.eSTARQField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC923.xsd")]
   public partial class BCARQComplexType_ACTC923
   {

      private string nomArqField;

      private string numCtrlEmisField;

      private string numCtrlDestOrField;

      private string iSPBEmissorField;

      private string iSPBDestinatarioField;

      private System.DateTime dtHrArqField;

      private string sitReqField;

      private Grupo_SeqComplexType_ACTC923 grupo_SeqField;

      private System.DateTime dtRefField;

      /// <remarks/>
      public string NomArq
      {
         get
         {
            return this.nomArqField;
         }
         set
         {
            this.nomArqField = value;
         }
      }

      /// <remarks/>
      public string NumCtrlEmis
      {
         get
         {
            return this.numCtrlEmisField;
         }
         set
         {
            this.numCtrlEmisField = value;
         }
      }

      /// <remarks/>
      public string NumCtrlDestOr
      {
         get
         {
            return this.numCtrlDestOrField;
         }
         set
         {
            this.numCtrlDestOrField = value;
         }
      }

      /// <remarks/>
      public string ISPBEmissor
      {
         get
         {
            return this.iSPBEmissorField;
         }
         set
         {
            this.iSPBEmissorField = value;
         }
      }

      /// <remarks/>
      public string ISPBDestinatario
      {
         get
         {
            return this.iSPBDestinatarioField;
         }
         set
         {
            this.iSPBDestinatarioField = value;
         }
      }

      /// <remarks/>
      public System.DateTime DtHrArq
      {
         get
         {
            return this.dtHrArqField;
         }
         set
         {
            this.dtHrArqField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
      public string SitReq
      {
         get
         {
            return this.sitReqField;
         }
         set
         {
            this.sitReqField = value;
         }
      }

      /// <remarks/>
      public Grupo_SeqComplexType_ACTC923 Grupo_Seq
      {
         get
         {
            return this.grupo_SeqField;
         }
         set
         {
            this.grupo_SeqField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
      public System.DateTime DtRef
      {
         get
         {
            return this.dtRefField;
         }
         set
         {
            this.dtRefField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC923.xsd")]
   public partial class Grupo_SeqComplexType_ACTC923
   {

      private string numSeqField;

      private Indr indrContField;

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
      public string NumSeq
      {
         get
         {
            return this.numSeqField;
         }
         set
         {
            this.numSeqField = value;
         }
      }

      /// <remarks/>
      public Indr IndrCont
      {
         get
         {
            return this.indrContField;
         }
         set
         {
            this.indrContField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC923.xsd")]
   public enum Indr
   {

      /// <remarks/>
      S,

      /// <remarks/>
      N,
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC923.xsd")]
   public partial class SitLiquidPortldd_CodErro
   {

      private string codErroField;

      private string valueField;

      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string CodErro
      {
         get
         {
            return this.codErroField;
         }
         set
         {
            this.codErroField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlTextAttribute(DataType = "integer")]
      public string Value
      {
         get
         {
            return this.valueField;
         }
         set
         {
            this.valueField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC923.xsd")]
   public partial class SitPortlddCTC_CodErro
   {

      private string codErroField;

      private string valueField;

      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string CodErro
      {
         get
         {
            return this.codErroField;
         }
         set
         {
            this.codErroField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlTextAttribute(DataType = "integer")]
      public string Value
      {
         get
         {
            return this.valueField;
         }
         set
         {
            this.valueField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC923.xsd")]
   public partial class TpEnteCons_CodErro
   {

      private string codErroField;

      private string valueField;

      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string CodErro
      {
         get
         {
            return this.codErroField;
         }
         set
         {
            this.codErroField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlTextAttribute(DataType = "integer")]
      public string Value
      {
         get
         {
            return this.valueField;
         }
         set
         {
            this.valueField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC923.xsd")]
   public partial class TpContrto_CodErro
   {

      private string codErroField;

      private string valueField;

      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string CodErro
      {
         get
         {
            return this.codErroField;
         }
         set
         {
            this.codErroField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlTextAttribute()]
      public string Value
      {
         get
         {
            return this.valueField;
         }
         set
         {
            this.valueField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC923.xsd")]
   public partial class Data_CodErro
   {

      private string codErroField;

      private System.DateTime valueField;

      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string CodErro
      {
         get
         {
            return this.codErroField;
         }
         set
         {
            this.codErroField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlTextAttribute(DataType = "date")]
      public System.DateTime Value
      {
         get
         {
            return this.valueField;
         }
         set
         {
            this.valueField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC923.xsd")]
   public partial class ControleIF_CodErro
   {

      private string codErroField;

      private string valueField;

      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string CodErro
      {
         get
         {
            return this.codErroField;
         }
         set
         {
            this.codErroField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlTextAttribute()]
      public string Value
      {
         get
         {
            return this.valueField;
         }
         set
         {
            this.valueField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC923.xsd")]
   public partial class CNPJBase_CodErro
   {

      private string codErroField;

      private string valueField;

      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string CodErro
      {
         get
         {
            return this.codErroField;
         }
         set
         {
            this.codErroField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlTextAttribute()]
      public string Value
      {
         get
         {
            return this.valueField;
         }
         set
         {
            this.valueField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC923.xsd")]
   public partial class Grupo_ACTC923RET_RelatPosAnlRecsdComplexType
   {

      private CNPJBase_CodErro identdPartAdmdoField;

      private ControleIF_CodErro numCtrlIFField;

      private Data_CodErro dtIniApurcField;

      private Data_CodErro dtFimApurcField;

      private CNPJBase_CodErro iSPBPropntField;

      private CNPJBase_CodErro iSPBOrigdrField;

      private TpContrto_CodErro tpContrtoField;

      private TpEnteCons_CodErro tpEnteConsField;

      private SitPortlddCTC_CodErro sitPortlddCTCField;

      private SitLiquidPortldd_CodErro sitLiquidPortlddField;

      private string codErroField;

      /// <remarks/>
      public CNPJBase_CodErro IdentdPartAdmdo
      {
         get
         {
            return this.identdPartAdmdoField;
         }
         set
         {
            this.identdPartAdmdoField = value;
         }
      }

      /// <remarks/>
      public ControleIF_CodErro NumCtrlIF
      {
         get
         {
            return this.numCtrlIFField;
         }
         set
         {
            this.numCtrlIFField = value;
         }
      }

      /// <remarks/>
      public Data_CodErro DtIniApurc
      {
         get
         {
            return this.dtIniApurcField;
         }
         set
         {
            this.dtIniApurcField = value;
         }
      }

      /// <remarks/>
      public Data_CodErro DtFimApurc
      {
         get
         {
            return this.dtFimApurcField;
         }
         set
         {
            this.dtFimApurcField = value;
         }
      }

      /// <remarks/>
      public CNPJBase_CodErro ISPBPropnt
      {
         get
         {
            return this.iSPBPropntField;
         }
         set
         {
            this.iSPBPropntField = value;
         }
      }

      /// <remarks/>
      public CNPJBase_CodErro ISPBOrigdr
      {
         get
         {
            return this.iSPBOrigdrField;
         }
         set
         {
            this.iSPBOrigdrField = value;
         }
      }

      /// <remarks/>
      public TpContrto_CodErro TpContrto
      {
         get
         {
            return this.tpContrtoField;
         }
         set
         {
            this.tpContrtoField = value;
         }
      }

      /// <remarks/>
      public TpEnteCons_CodErro TpEnteCons
      {
         get
         {
            return this.tpEnteConsField;
         }
         set
         {
            this.tpEnteConsField = value;
         }
      }

      /// <remarks/>
      public SitPortlddCTC_CodErro SitPortlddCTC
      {
         get
         {
            return this.sitPortlddCTCField;
         }
         set
         {
            this.sitPortlddCTCField = value;
         }
      }

      /// <remarks/>
      public SitLiquidPortldd_CodErro SitLiquidPortldd
      {
         get
         {
            return this.sitLiquidPortlddField;
         }
         set
         {
            this.sitLiquidPortlddField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string CodErro
      {
         get
         {
            return this.codErroField;
         }
         set
         {
            this.codErroField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC923.xsd")]
   public partial class Grupo_ACTC923RET_RelatPosAnlActoComplexType
   {

      private string identdPartAdmdoField;

      private string numCtrlIFField;

      private string numCtrlCIPField;

      private System.DateTime dtSolictcField;

      private string sitSolictcField;

      /// <remarks/>
      public string IdentdPartAdmdo
      {
         get
         {
            return this.identdPartAdmdoField;
         }
         set
         {
            this.identdPartAdmdoField = value;
         }
      }

      /// <remarks/>
      public string NumCtrlIF
      {
         get
         {
            return this.numCtrlIFField;
         }
         set
         {
            this.numCtrlIFField = value;
         }
      }

      /// <remarks/>
      public string NumCtrlCIP
      {
         get
         {
            return this.numCtrlCIPField;
         }
         set
         {
            this.numCtrlCIPField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
      public System.DateTime DtSolictc
      {
         get
         {
            return this.dtSolictcField;
         }
         set
         {
            this.dtSolictcField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
      public string SitSolictc
      {
         get
         {
            return this.sitSolictcField;
         }
         set
         {
            this.sitSolictcField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC923.xsd")]
   public partial class ACTC923RETComplexType
   {

      private Grupo_ACTC923RET_RelatPosAnlActoComplexType grupo_ACTC923RET_RelatPosAnlActoField;

      private Grupo_ACTC923RET_RelatPosAnlRecsdComplexType grupo_ACTC923RET_RelatPosAnlRecsdField;

      /// <remarks/>
      public Grupo_ACTC923RET_RelatPosAnlActoComplexType Grupo_ACTC923RET_RelatPosAnlActo
      {
         get
         {
            return this.grupo_ACTC923RET_RelatPosAnlActoField;
         }
         set
         {
            this.grupo_ACTC923RET_RelatPosAnlActoField = value;
         }
      }

      /// <remarks/>
      public Grupo_ACTC923RET_RelatPosAnlRecsdComplexType Grupo_ACTC923RET_RelatPosAnlRecsd
      {
         get
         {
            return this.grupo_ACTC923RET_RelatPosAnlRecsdField;
         }
         set
         {
            this.grupo_ACTC923RET_RelatPosAnlRecsdField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC923.xsd")]
   public partial class ACTC923ComplexType
   {

      private string identdPartAdmdoField;

      private string numCtrlIFField;

      private System.DateTime dtIniApurcField;

      private System.DateTime dtFimApurcField;

      private string iSPBPropntField;

      private string iSPBOrigdrField;

      private string tpContrtoField;

      private string tpEnteConsField;

      private string sitPortlddCTCField;

      private string sitLiquidPortlddField;

      /// <remarks/>
      public string IdentdPartAdmdo
      {
         get
         {
            return this.identdPartAdmdoField;
         }
         set
         {
            this.identdPartAdmdoField = value;
         }
      }

      /// <remarks/>
      public string NumCtrlIF
      {
         get
         {
            return this.numCtrlIFField;
         }
         set
         {
            this.numCtrlIFField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
      public System.DateTime DtIniApurc
      {
         get
         {
            return this.dtIniApurcField;
         }
         set
         {
            this.dtIniApurcField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
      public System.DateTime DtFimApurc
      {
         get
         {
            return this.dtFimApurcField;
         }
         set
         {
            this.dtFimApurcField = value;
         }
      }

      /// <remarks/>
      public string ISPBPropnt
      {
         get
         {
            return this.iSPBPropntField;
         }
         set
         {
            this.iSPBPropntField = value;
         }
      }

      /// <remarks/>
      public string ISPBOrigdr
      {
         get
         {
            return this.iSPBOrigdrField;
         }
         set
         {
            this.iSPBOrigdrField = value;
         }
      }

      /// <remarks/>
      public string TpContrto
      {
         get
         {
            return this.tpContrtoField;
         }
         set
         {
            this.tpContrtoField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
      public string TpEnteCons
      {
         get
         {
            return this.tpEnteConsField;
         }
         set
         {
            this.tpEnteConsField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
      public string SitPortlddCTC
      {
         get
         {
            return this.sitPortlddCTCField;
         }
         set
         {
            this.sitPortlddCTCField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
      public string SitLiquidPortldd
      {
         get
         {
            return this.sitLiquidPortlddField;
         }
         set
         {
            this.sitLiquidPortlddField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC923.xsd")]
   public partial class SISARQComplexType_ACTC923
   {

      private object itemField;

      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute("ACTC923", typeof(ACTC923ComplexType))]
      [System.Xml.Serialization.XmlElementAttribute("ACTC923RET", typeof(ACTC923RETComplexType))]
      public object Item
      {
         get
         {
            return this.itemField;
         }
         set
         {
            this.itemField = value;
         }
      }
   }
}
