CREATE TABLE FastConsig.dbo.ConsignadoOcorrencia (
  Id int IDENTITY,
  Codigo varchar(5) NULL,
  Descricao varchar(255) NOT NULL,
  Acao int NOT NULL,
  Ocorrencia int NULL,
  TipoConsignado char(1) NOT NULL DEFAULT ('I'),
  CONSTRAINT PK_ConsignadoOcorrencia PRIMARY KEY CLUSTERED (Id)
)
ON [PRIMARY]
GO

ALTER TABLE FastConsig.dbo.ConsignadoOcorrencia
  ADD CONSTRAINT ConsignadoOcorrencia_FK FOREIGN KEY (Ocorrencia) REFERENCES dbo.Ocorrencias (Id)
GO

SET DATEFORMAT ymd
SET ARITHABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS, XACT_ABORT OFF
GO

SET IDENTITY_INSERT FastConsig.dbo.ConsignadoOcorrencia ON
GO
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (2, 'AD', 'O documento de identificação enviado não corresponde a um arquivo PDF/A válido', 4, 3, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (3, 'AM', 'Agência da Conta Corrente do segurado divergente', 4, 3, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (4, 'AN', 'Conta Corrente/DV do Favorecido Inválido.', 4, 3, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (5, 'AO', 'Nome invalido o nome esta em branco', 4, 3, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (6, 'AP', 'Data de inicio/fim do contrato invalida', 4, 3, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (7, 'AR', 'A assinatura a rogo é invalida ou não foi informada', 4, 3, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (8, 'AS', 'O(s) benefício(s) relacionado(s) ao CPF do titular não possui(em) representante legal', 2, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (9, 'AT', 'O termo de autorização enviado não corresponde a um arquivo PDF/A válido', 4, 3, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (10, 'AV', 'Não é possível realizar a operação até que seja concluído o processamento da folha de pagamento do INSS', 3, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (11, 'AX', 'O empréstimo tem uma alteração em aberto', 2, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (12, 'AY', 'Sigla do Estado do Favorecido Inválida', 4, 3, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (13, 'AZ', 'Os valores informados para os campos numeroParcelas e valorParcela são iguais aos valores atuais do empréstimo', 2, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (14, 'BC', 'Requicisão sem CBC', 4, 3, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (15, 'BD', 'Inclusão efetuada com sucesso', 1, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (16, 'BF', 'Exclusão (ou baixa) efetuada com sucesso', 2, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (17, 'BI', 'Benefício inexistente', 2, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (18, 'BJ', 'O benefício já estava desbloqueado', 4, 3, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (19, 'BL', 'Valor da parcela inválido', 4, 3, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (20, 'BM', 'Numero de contrato invalido', 4, 3, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (21, 'BN', 'Desbloqueio indeferido', 2, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (22, 'BR', 'Reativação efetuada com sucesso', 4, 3, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (23, 'BS', 'Suspensão efetuada com sucesso', 4, 3, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (24, 'CA', 'Código do banco inválido', 4, 3, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (25, 'CD', 'CPF não encontrado na base ou CPF de benefício inelegível', 2, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (26, 'CE', 'O CPF do representante legal da requisição e o CPF da requisição são diferentes', 2, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (27, 'CH', 'Requisição sem chave identificadora do termo', 3, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (28, 'CI', 'Canal de atendimento inválido', 4, 3, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (29, 'CJ', 'O CPF ou o CNPJ do Correspondente estão invalidos', 4, 3, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (30, 'CR', 'A requisição está sem o número do CPF do representante legal', 2, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (31, 'CT', 'O valor da CET (custo efetivo total) é invalido', 4, 3, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (32, 'CV', 'Periodo invalido', 3, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (33, 'CX', 'O classificador da situação de portabilidade é inválido', 2, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (34, 'CY', 'A instituição Financeira origem não existe', 2, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (35, 'D3', 'Dados do benefício estão incompletos, inconsistentes ou nulos: Valor Margem Disponível na Próxima Competência. Entrar em contato com a DATAPREV', 2, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (36, 'D4', 'Dados do benefício estão incompletos, inconsistentes ou nulos: Valor Margem Disponível Cartão. Entrar em contato com a DATAPREV', 2, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (37, 'D5', 'Dados do benefício estão incompletos, inconsistentes ou nulos: Agência Bancária. Entrar em contato com a DATAPREV', 2, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (38, 'D6', 'Dados do benefício estão incompletos, inconsistentes ou nulos: Conta Corrente. Entrar em contato com a DATAPREV', 2, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (39, 'D7', 'Dados do benefício estão incompletos, inconsistentes ou nulos: Valor Mensalidade Reajustada. Entrar em contato com a DATAPREV', 2, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (40, 'DA', 'A data e hora da autorização digital do beneficiário é uma data inválida. Utilize o formato DdMMyyyyhh24mmss ', 4, 3, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (41, 'DH', 'A data hora de criação do termo é uma data inválida ou uma data futura', 4, 3, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (42, 'DI', 'Tipo de documento inválido', 4, 3, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (43, 'DJ', 'A quantidade de solicitações na inclusão de desconto de cartão ou na exclusão de desconto de cartão está inválida!', 2, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (44, 'DK', 'Não é possível mais de um contrato de desconto cartão para um mesmo beneficio', 2, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (45, 'DR', 'Não foi encontrado na base o CPF com o CPF do representante legal cuja data fim do representante legal é maior ou igual à data atual', 2, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (46, 'EP', 'Erro no processamento', 3, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (47, 'EX', 'Token de autorização expirado', 3, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (48, 'FH', 'Operação fora do horário permitido', 3, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (49, 'GA', 'Na consulta de portabilidade
•O(s) campo(s) obrigatório(s) não foram informados
•Nas demais operações:
•O(s) campo(s) obrigatório(s) não informados:', 2, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (50, 'GE', 'Na Consulta de Portabilidade, na Consulta Extrato do Benefício, na Consulta empréstimos suspensos
	•Não foram localizados registros
	Nas demais operações
	•<campo1, campo2, campo 3> não existe(m)', 4, 3, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (51, 'GS', 'Não existe registro de portabilidade com o número único informado', 2, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (52, 'H3', 'É possível que tenha ocorrido uma mudança emergencial de sistema, por motivo legal ou outro, ou mesma alguma falha de sistema. Entrar em contato com a DATAPREV.', 3, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (53, 'HM', 'Mutuário não identificado', 2, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (54, 'HN', 'Tipo de benefício não permite empréstimo', 2, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (55, 'HP', 'Benefício recebido por procurador', 2, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (56, 'HQ', 'Benefício é do tipo PA', 2, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (57, 'HR', 'Quantidade de contratos permitida excedida', 2, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (58, 'HS', 'Benefício não pertence ao banco', 2, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (59, 'HV', 'Quantidade de parcelas inválida', 2, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (60, 'HW', 'Margem consignável excedida.', 2, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (61, 'HX', 'Empréstimo já cadastrado', 4, 3, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (62, 'HY', 'Empréstimo inexistente', 2, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (63, 'HZ', 'Não é possível fazer a operação com o empréstimo nesta situação', 4, 3, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (64, 'IA', 'Nome divergente', 2, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (65, 'IB', 'Benefício suspenso/cessado pela APS ou pelo Sisob', 2, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (66, 'IE', 'Benefício bloqueado para empréstimo pelo beneficiário', 2, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (67, 'IF', 'Beneficio bloqueado na concessão', 2, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (68, 'IN', 'Serviço/Sistema Indisponível.', 3, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (69, 'IO', 'O valor do IOF é Inválido', 3, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (70, 'IQ', 'Contrato já suspenso pelo Banco', 4, 3, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (71, 'IR', 'Prazo da operação é maior que a data de extinção de cota do benefício', 2, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (72, 'IV', 'Token de autorização de consulta inválido', 3, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (73, 'LE', 'Limite de registros retornados excedido ', 3, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (74, 'ME', 'O motivo de exclusão do empréstimo é inválido', 3, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (75, 'MN', 'É obrigatorio o preenchimento de todos os campos do termo de autorização', 4, 3, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (76, 'NB', 'Requisição sem número do benefício', 4, 3, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (77, 'NC', 'A requisição está sem número de contrato.', 4, 3, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (78, 'OA', 'O valor do saldo limite do cartão está inválido', 2, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (79, 'OB', 'O valor utilizado no mês pelo cartão está inválido', 2, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (80, 'OC', 'O percentual está inválido', 2, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (81, 'OD', 'O valor Limite de cartão está inválido', 2, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (82, 'OE', 'O valor do desconto está inválido', 2, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (83, 'OF', 'O CBC da IF pagadora está inválido', 4, 3, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (84, 'OG', 'Benefício sendo atualizado por outra operação', 3, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (85, 'OH', 'O número do contrato está inválido (caracteres não permitidos e/ou com espaço à direita)', 2, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (86, 'OI', 'É obrigatório o envio das informações da autorização digital ou das informações da autorização através do envio de PDF/A
OT	O tamanho do(s) campo(s) está incorreto: <campo 1>, <campo 2>', 4, 3, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (87, 'OJ', 'A requisição não está de acordo com o contrato da API', 2, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (88, 'OK', 'Campo(s) não codificado(s) em Base64: <documento e/ou termo>', 3, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (89, 'OL', 'A lista enviada na solicitação está inválida', 2, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (90, 'OM', 'O benefício não possui o valor da margem cadastrado', 3, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (91, 'ON', 'Operação não permitida', 2, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (92, 'OP', 'Instituição financeira penalizada para esta operação', 3, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (93, 'OS', 'O CPF não corresponde ao CPF do representante legal ativo', 2, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (94, 'OT', 'Tamanho dos campos incorretos', 4, 3, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (95, 'OU', 'O valor da taxa anual está inválido', 3, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (96, 'OV', 'O valor do custo efetivo anual está inválido', 3, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (97, 'OX', 'A data Limite das Operações não está cadastrada', 3, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (98, 'OZ', 'O serviço esta suspenso. Temino processamento de folha', 3, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (99, 'P1', 'Dados de parâmetros internos não cadastrados corretamente: Competência Atual. Entrar em contato com a DATAPREV', 3, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (100, 'P2', 'Dados de parâmetros internos não cadastrados corretamente: Última Competência Fechada. Entrar em contato com a DATAPREV', 3, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (101, 'P4', 'Dados de parâmetros internos não cadastrados corretamente: Data Limite da Operação. Entrar em contato com a DATAPREV', 3, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (102, 'P5', 'Dados de parâmetros internos não cadastrados corretamente: Data Limite de Averbação. Entrar em contato com a DATAPREV', 3, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (103, 'P6', 'Dados de parâmetros internos não cadastrados corretamente: Carência. Entrar em contato com a DATAPREV', 3, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (104, 'PA', 'O código do proponente está inválido', 2, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (105, 'PB', 'O NU foi encontrado na base para um CBC proponente diferente', 2, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (106, 'PC', 'A última parcela paga ao banco origem está inválida', 2, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (107, 'PD', 'A requisição está com o número do CPF do representante legal, e este benefício não possui um representante legal ativo', 2, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (108, 'PE', 'O NU foi encontrado na base para um benefício diferente', 2, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (109, 'PF', 'O CPF da requisição não correspondente ao CPF do benefício', 2, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (110, 'PG', 'Código do NU inválido', 2, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (111, 'PH', 'O NU foi encontrado na base para uma portabilidade, mas para um NB diferente', 2, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (112, 'PI', 'O valor do empréstimo está inválido', 2, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (113, 'PJ', 'O valor pago está inválido', 2, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (114, 'PK', 'O NU foi encontrado na base para uma portabilidade, mas para um CBC proponente diferente', 2, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (115, 'PL', 'O empréstimo está em processo de refinanciamento', 2, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (116, 'PQ', 'A lista de contratos excluídos está inválida', 2, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (117, 'PS', 'A instituição Financeira proponente não possui convênio para realizar a operação de averbação por portabilidade', 3, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (118, 'PU', 'O NU foi encontrado na base para uma portabilidade com mesmo NB e IF proponente, mas para um contrato diferente', 2, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (119, 'PX', 'O NU foi encontrado na base para uma portabilidade com mesmo NB, IF proponente e contrato', 2, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (120, 'PZ', 'O documento enviado não corresponde a um arquivo PDF/A válido', 4, 3, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (121, 'RA', 'A lista de contratos quitados está inválida', 2, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (122, 'RB', 'O valor do troco está inválido', 2, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (123, 'RD', 'Requisiçao sem o termo digitalizado de autorização do beneficiario', 4, 3, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (124, 'RG', 'O código do motivo da reversão do refinanciamento está inválido', 4, 3, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (125, 'RI', 'Não foi encontrado na base o CPF com o CPF do representante legal', 2, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (126, 'RL', 'A requisição está sem o número do CPF do representante legal, e este benefício possui um representante legal ativo', 2, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (127, 'RM', 'O contrato informado não foi um contrato criado em um refinanciamento', 2, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (128, 'RN', 'A requisição esta com o numero do CPF do representante legal, e este beneficio não possui representante legal ativo', 2, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (129, 'RR', 'Desbloqueio indeferido', 2, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (130, 'SF', 'A requisição está sem o CPF ou o CPF informado está com o DV inválido', 2, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (131, 'TN', 'Requisição sem as informações de identificação de autorização digital', 4, 3, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (132, 'VT', 'O valor da taxa anual esta invalido', 3, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (216, '0000', 'Serviço Realizado com Sucesso', 1, NULL, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (217, '0002', 'Órgão Inexistente', 4, 3, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (218, '0008', 'Convênio Inexistente', 4, 3, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (219, '0024', 'Número do contrato incorreto', 4, 3, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (220, '0029', 'Número do contrato existente', 4, 3, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (221, '0056', 'Órgão não está ativo', 2, NULL, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (222, '0087', 'Senha do funcionário expirada ou bloqueada', 4, 3, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (223, '0001', 'Serviço Realizado com Sucesso', 1, NULL, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (224, '2027', 'Valor da Prestação incorreto. I Órgão incorreto. I Matricula incorreta', 2, NULL, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (225, '2035', 'Servidor inativo', 2, NULL, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (226, '2046', 'CPF não confere com a matrícula', 2, NULL, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (227, '2048', 'Servidor falecido', 2, NULL, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (228, '2109', 'Valor da prestação não informado I órgão não informado I Matricula não informada', 2, NULL, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (229, '2215', 'Registro está sendo utilizado em outra operação', 2, NULL, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (230, '2282', 'Senha do servidor não autenticada', 4, 3, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (231, '4003', 'Nenhum contrato vigente', 2, NULL, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (232, '4004', 'Quantidade de contratos vigentes insuficiente', 2, NULL, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (233, '4005', 'Não foi possivel recuperar todos os contratos vigentes', 2, NULL, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (234, '4006', 'O contrato pertence a outro vínculo', 2, NULL, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (235, '4007', 'Situação do servidor não permite consignação', 2, NULL, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (236, '4008', 'Rubrica não possui autorização para realizar consignação', 2, NULL, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (237, '4009', 'Nenhum vínculo encontrado para este servidor', 4, 3, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (238, '4010', 'Valor e prazo iguais ao do contrato a ser alterado', 2, NULL, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (239, '4011', 'Consignatária sem rubrica associada para este órgão', 4, 3, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (240, '4012', 'Contrato renovado dentro do mês não pode ser excluido', 2, NULL, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (241, '4013', 'Contrato já se encontra quitado', 1, NULL, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (242, '4014', 'Contrato sem renovação', 1, NULL, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (243, '4015', 'Contrato sem rubrica disponível', 2, NULL, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (244, '4016', 'Servidor ou Pensionista com renovação no mês corrente', 2, NULL, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (245, '4017', 'Rubrica não pertence a esta consignatária', 2, NULL, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (246, '4018', 'Rubrica não pode ser tratada por mov. De consignação', 2, NULL, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (247, '4019', 'Servidor ou Pensionista bloqueado para rubrica/sequência', 2, NULL, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (248, '4020', 'Atualização noa permitida, conforme 3º do art. 25º', 3, NULL, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (249, '4021', 'Rubrica não é facultativa', 2, NULL, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (250, '4022', 'Prazo informado maior que o prazo estabelcido pelo MP', 2, NULL, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (251, '4023', 'Problemas com a consignatária', 3, NULL, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (252, '4024', 'Matrícula ou òrgão inválido', 2, NULL, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (253, '4025', 'Cronograma do Órgão não implantado', 3, NULL, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (254, '4026', 'Rubrica não cadastrada', 3, NULL, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (255, '4027', 'Rubrica desativada', 3, NULL, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (256, '4028', 'Situação funcional da rubrica imcopatível com a do servidor', 2, NULL, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (257, '4029', 'Rubrica com incopatibilidade determinada po decisão judicial', 2, NULL, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (258, '4030', 'Valor inferior ao minimo permitido', 2, NULL, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (259, '4031', 'Inclusão de rubrica/sequência já existente para o servidor/pensionista', 2, NULL, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (260, '4032', 'Beneficiário excluido de pagamento', 2, NULL, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (261, '4033', 'Beneficiário suspenso de pagamento', 2, NULL, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (262, '4034', 'Servidor/Pensionista sem contrato ativo', 4, 3, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (263, '4035', 'Contratos zerados', 4, 3, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (264, '4036', 'Tipo de consignação só permite amortização', 2, NULL, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (265, '4037', 'Cnotrato não pode desfazer renovação', 2, NULL, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (266, '4038', 'Rubrica/Sequência do contrato', 3, NULL, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (267, '4039', 'Contrato não pode ser alterado', 2, NULL, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (268, '4040', 'Já existe uma consignação de cartão vigente. Tipo de consignação', 2, NULL, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (269, '4041', 'Consignação de cartão deve possuir prazo igual a 1', 2, NULL, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (270, '4042', 'Não permitida renovação de Consignação de cartão', 2, NULL, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (271, '8001', 'CPF incorreto', 2, NULL, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (272, '8010', 'Consignatária inexistente', 3, NULL, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (273, '8014', 'Servidor inexistente', 2, NULL, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (274, '8017', 'Contrato não localizado', 4, 3, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (275, '8028', 'Código de origem da transação incorreto', 4, 3, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (276, '8030', 'Código identificação servidor incorreto', 4, 3, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (277, '8035', 'Registro Hold incorreto', 4, 3, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (278, '8036', 'Consignatária incorreta', 4, 3, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (279, '8039', 'Senha do funcionário incorreta', 4, 3, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (280, '8056', 'Senha da consignatária incorreta', 4, 3, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (281, '8058', 'Funcionário não tem margem para esta solicitação', 2, NULL, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (282, '8060', 'Senha da consignatária bloqueada', 4, 3, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (283, '8083', 'Senha da consignatária não informada', 4, 3, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (284, '8084', 'Senha do servidor da transação não informada', 4, 3, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (285, '8087', 'Condigo da companhia não informado', 4, 3, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (286, '8089', 'CPF do servidor não informado', 2, NULL, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (287, '8111', 'Código de origem da transação não informado', 4, 3, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (288, '8112', 'Código identificação servidor não informado', 4, 3, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (289, '8133', 'Ação não executada. Número de sequência indisponivel', 3, NULL, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (290, '8888', 'Serviço indisponível', 3, NULL, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (291, '3', 'Ativo', 1, NULL, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (292, '4', 'Renovado', 1, NULL, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (293, '5', 'Quintado', 1, NULL, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (294, '6', 'Encerrado Consignatária', 2, NULL, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (295, '7', 'Suspenso com Bloqueio de Margem Consignavel', 2, NULL, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (296, '8', 'Suspenso sem Bloqueio de Margem Consignavel', 2, NULL, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (297, '9', 'Portado', 2, NULL, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (298, '10', 'Aguardando Anuência', 3, NULL, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (299, '11', 'Anuência Recusada', 2, NULL, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (300, '12', 'Anuência Expirada', 4, 3, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (301, '13', 'Anuência Interrompida por Restrição', 2, NULL, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (302, '14', 'Aguardando Encerramento do Contrato Portado', 3, NULL, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (303, '15', 'Portabilidade Cancelada por Prazo', 2, NULL, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (304, '16', 'Encerrado por Falta de Autorização', 2, NULL, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (305, 'AB', 'Tipo de Operação Inválido', 4, 3, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (306, '0000', 'Ativo', 1, NULL, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (307, '4050', 'Rubrica  possui  restrição  de  consignação  ativa  com  o  servidor/pensionista', 2, NULL, 'S')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (308, 'BP', '<Alteração de NU ou Alteração de CBC> realizada com sucesso', 4, 3, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (309, 'D9', 'Dados do benefício estão incompletos, inconsistentes ou nulos: Sigla da UF. Entrar em contato com a DATAPREV', 4, 3, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (310, 'GT', 'O NU foi encontrado na base para uma portabilidade, mas para uma IF origem diferente', 4, 3, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (311, 'GU', 'O NU foi encontrado na base para uma portabilidade e a IF proponente é igual a IF sendo informada', 4, 3, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (312, 'GV', 'O NU foi encontrado na base para uma portabilidade, mas já foi realizada a averbação por portabilidade', 4, 3, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (313, 'GX', 'O NU novo já encontrado na base', 4, 3, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (314, 'HT', 'Início do desconto informado já ultrapassado', 4, 3, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (315, 'IT', 'Beneficio bloqueado por TBM', 2, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (316, 'P7', 'Dados de parâmetros internos não cadastrados corretamente: Data de Implantação Margem. Entrar em contato com a DATAPREV', 4, 3, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (317, 'TC', 'Tipo desconto do cartão inválido', 2, NULL, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (318, 'RH', 'O período de reversão do refinanciamento já foi encerrado para o contrato', 4, 3, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (319, 'TV', 'O valor do IOF é Inválido	', 4, 3, 'I')
INSERT FastConsig.dbo.ConsignadoOcorrencia(Id, Codigo, Descricao, Acao, Ocorrencia, TipoConsignado) VALUES (320, 'TP', 'A data do primeiro desconto está inválida	', 4, 3, 'I')
GO
SET IDENTITY_INSERT FastConsig.dbo.ConsignadoOcorrencia OFF
GO