CREATE DATABASE FastConsig
ON PRIMARY(
    NAME = N'FastConsig',
    FILENAME = N'D:\rdsdbdata\DATA\FastConsig.mdf',
    SIZE = 10240KB,
    MAXSIZE = UNLIMITED,
    FILEGROWTH = 1024KB
)
LOG ON(
    NAME = N'FastConsig_log',
    FILENAME = N'D:\rdsdbdata\DATA\FastConsig_log.ldf',
    SIZE = 5120KB,
    MAXSIZE = UNLIMITED,
    FILEGROWTH = 10%
)
GO

ALTER DATABASE FastConsig
  SET
    ANSI_NULL_DEFAULT OFF,
    ANSI_NULLS OFF,
    ANSI_PADDING OFF,
    ANSI_WARNINGS OFF,
    ARITHABORT OFF,
    AUTO_CLOSE OFF,
    AUTO_CREATE_STATISTICS ON,
    AUTO_SHRINK OFF,
    AUTO_UPDATE_STATISTICS ON,
    AUTO_UPDATE_STATISTICS_ASYNC OFF,
    CONCAT_NULL_YIELDS_NULL OFF,
    CURSOR_CLOSE_ON_COMMIT OFF,
    CURSOR_DEFAULT GLOBAL,
    DATE_CORRELATION_OPTIMIZATION OFF,
    MULTI_USER,
    NUMERIC_ROUNDABORT OFF,
    PAGE_VERIFY CHECKSUM,
    PARAMETERIZATION SIMPLE,
    QUOTED_IDENTIFIER OFF,
    READ_COMMITTED_SNAPSHOT OFF,
    RECOVERY FULL,
    RECURSIVE_TRIGGERS OFF
    WITH ROLLBACK IMMEDIATE
GO

ALTER DATABASE FastConsig
  SET DISABLE_BROKER
GO

ALTER DATABASE FastConsig
  SET ALLOW_SNAPSHOT_ISOLATION OFF
GO

ALTER DATABASE FastConsig
  SET FILESTREAM (NON_TRANSACTED_ACCESS = OFF)
GO

ALTER DATABASE FastConsig
  SET QUERY_STORE = OFF
GO

USE FastConsig
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

USE FastConsig
GO

IF DB_NAME() <> N'FastConsig' SET NOEXEC ON
GO


USE master
GO

IF DB_NAME() <> N'master' SET NOEXEC ON
GO


--
-- Set transaction isolation level
--
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO

--
-- Start Transaction
--
BEGIN TRANSACTION
GO

--
-- Create login [FastConsig]
--
CREATE LOGIN FastConsig
WITH 
PASSWORD = '!F@stC@nsig!'
,DEFAULT_DATABASE = FastConsig
,DEFAULT_LANGUAGE = Brazilian
,CHECK_POLICY = OFF
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN
 IF @@TRANCOUNT>0 ROLLBACK
SET NOEXEC ON
 END
GO

--
-- Commit Transaction
--
IF @@TRANCOUNT>0 COMMIT TRANSACTION
GO

--
-- Set NOEXEC to off
--
SET NOEXEC OFF
GO

USE FastConsig
GO

IF DB_NAME() <> N'FastConsig' SET NOEXEC ON
GO


--
-- Set transaction isolation level
--
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
GO

--
-- Start Transaction
--
BEGIN TRANSACTION
GO

--
-- Create user [FastConsig]
--
CREATE USER FastConsig
  FOR LOGIN FastConsig
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN
 IF @@TRANCOUNT>0 ROLLBACK
SET NOEXEC ON
 END
GO

--
-- Alter authorization on schema [db_datawriter]
--
ALTER AUTHORIZATION ON SCHEMA :: db_datawriter TO FastConsig
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN
 IF @@TRANCOUNT>0 ROLLBACK
SET NOEXEC ON
 END
GO

--
-- Alter authorization on schema [db_datareader]
--
ALTER AUTHORIZATION ON SCHEMA :: db_datareader TO FastConsig
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN
 IF @@TRANCOUNT>0 ROLLBACK
SET NOEXEC ON
 END
GO

--
-- Commit Transaction
--
IF @@TRANCOUNT>0 COMMIT TRANSACTION
GO

--
-- Set NOEXEC to off
--
SET NOEXEC OFF
GO