CREATE TABLE FastConsig.dbo.TipoAgenda (
  Id int IDENTITY,
  Descricao varchar(100) NULL,
  CONSTRAINT PK_TipoAgenda_Id PRIMARY KEY CLUSTERED (Id)
)
ON [PRIMARY]
GO

SET DATEFORMAT ymd
SET ARITHABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS, XACT_ABORT OFF
GO

SET IDENTITY_INSERT FastConsig.dbo.TipoAgenda ON
GO
INSERT FastConsig.dbo.TipoAgenda(Id, Descricao) VALUES (1, 'Expressão CRON')
GO
SET IDENTITY_INSERT FastConsig.dbo.TipoAgenda OFF
GO

SET DATEFORMAT ymd
SET ARITHABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS, XACT_ABORT OFF
GO

SET IDENTITY_INSERT FastConsig.dbo.TipoTarefa ON
GO
INSERT FastConsig.dbo.TipoTarefa(Id, Descricao) VALUES (1, 'Recorrente')
GO
SET IDENTITY_INSERT FastConsig.dbo.TipoTarefa OFF
GO