CREATE TABLE FastConsig.dbo.Tarefas (
  Id int IDENTITY,
  TipoTarefa int NULL,
  TipoAgenda int NULL,
  Fila int NULL,
  Agenda varchar(100) NULL,
  Assembly varchar(200) NULL,
  ClassName varchar(200) NULL,
  Nome varchar(200) NULL,
  Parametros varchar(max) NULL,
  Ativo bit NULL,
  CONSTRAINT PK_Tarefas_Id PRIMARY KEY CLUSTERED (Id),
  CONSTRAINT KEY_Tarefas_Nome UNIQUE (Nome)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE FastConsig.dbo.Tarefas
  ADD CONSTRAINT FK_Tarefas_Fila FOREIGN KEY (Fila) REFERENCES dbo.Fila (Id)
GO

ALTER TABLE FastConsig.dbo.Tarefas
  ADD CONSTRAINT FK_Tarefas_TipoAgenda FOREIGN KEY (TipoAgenda) REFERENCES dbo.TipoAgenda (Id)
GO

ALTER TABLE FastConsig.dbo.Tarefas
  ADD CONSTRAINT FK_Tarefas_TipoTarefa FOREIGN KEY (TipoTarefa) REFERENCES dbo.TipoTarefa (Id)
GO

--
-- Script was generated by Devart dbForge Studio 2022 for SQL Server, Version 6.4.124.0
-- Product home page: http://www.devart.com/dbforge/sql/studio
-- Script date 16/09/2024 23:28:28
-- Server version: 16.00.1000
--

SET DATEFORMAT ymd
SET ARITHABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS, XACT_ABORT OFF
GO

SET IDENTITY_INSERT FastConsig.dbo.Tarefas ON
GO
INSERT FastConsig.dbo.Tarefas(Id, TipoTarefa, TipoAgenda, Fila, Agenda, Assembly, ClassName, Nome, Parametros) VALUES (1, 1, 1, 3, '0 */1 * * *', 'FastConsig.Scheduler.Tarefas', 'FastConsig.Scheduler.Tarefas.SincronizarPromotoras', 'Sincronização de Promotoras', NULL)
INSERT FastConsig.dbo.Tarefas(Id, TipoTarefa, TipoAgenda, Fila, Agenda, Assembly, ClassName, Nome, Parametros) VALUES (2, 1, 1, 3, '0 */1 * * *', 'FastConsig.Scheduler.Tarefas', 'FastConsig.Scheduler.Tarefas.SincronizarRedeLojas', 'Sincronização de Rede de Lojas', NULL)
INSERT FastConsig.dbo.Tarefas(Id, TipoTarefa, TipoAgenda, Fila, Agenda, Assembly, ClassName, Nome, Parametros) VALUES (3, 1, 1, 3, '0 */1 * * *', 'FastConsig.Scheduler.Tarefas', 'FastConsig.Scheduler.Tarefas.SincronizarLojas', 'Sincronização de Lojas', NULL)
INSERT FastConsig.dbo.Tarefas(Id, TipoTarefa, TipoAgenda, Fila, Agenda, Assembly, ClassName, Nome, Parametros) VALUES (4, 1, 1, 3, '0 */1 * * *', 'FastConsig.Scheduler.Tarefas', 'FastConsig.Scheduler.Tarefas.SincronizarGerentes', 'Sincronização de Gerentes', NULL)
INSERT FastConsig.dbo.Tarefas(Id, TipoTarefa, TipoAgenda, Fila, Agenda, Assembly, ClassName, Nome, Parametros) VALUES (5, 1, 1, 3, '0 */1 * * *', 'FastConsig.Scheduler.Tarefas', 'FastConsig.Scheduler.Tarefas.SincronizarBancos', 'Sincronização de Bancos', NULL)
INSERT FastConsig.dbo.Tarefas(Id, TipoTarefa, TipoAgenda, Fila, Agenda, Assembly, ClassName, Nome, Parametros) VALUES (6, 1, 1, 6, '0 */1 * * *', 'FastConsig.Scheduler.Tarefas', 'FastConsig.Scheduler.Tarefas.ProcessamentoArquivosPortabilidade', 'Processamento Arquivos Portabilidade - Entrada/Saída', NULL)
INSERT FastConsig.dbo.Tarefas(Id, TipoTarefa, TipoAgenda, Fila, Agenda, Assembly, ClassName, Nome, Parametros) VALUES (7, 1, 1, 4, '0 */1 * * *', 'FastConsig.Scheduler.Tarefas', 'FastConsig.Scheduler.Tarefas.AverbacaoDataPrev', 'Averbação DataPrev', NULL)
INSERT FastConsig.dbo.Tarefas(Id, TipoTarefa, TipoAgenda, Fila, Agenda, Assembly, ClassName, Nome, Parametros) VALUES (8, 1, 1, 5, '0 */1 * * *', 'FastConsig.Scheduler.Tarefas', 'FastConsig.Scheduler.Tarefas.AverbacaoSerpro', 'Averbação Serpro', NULL)
INSERT FastConsig.dbo.Tarefas(Id, TipoTarefa, TipoAgenda, Fila, Agenda, Assembly, ClassName, Nome, Parametros) VALUES (9, 1, 1, 3, '0 */1 * * *', 'FastConsig.Scheduler.Tarefas', 'FastConsig.Scheduler.Tarefas.ProfissionaisCertificados', 'Download/Processamento Profissionais Certificados FEBRABAN', NULL)
GO
SET IDENTITY_INSERT FastConsig.dbo.Tarefas OFF
GO