CREATE TABLE FastConsig.dbo.Perfil (
  Id int IDENTITY,
  Nome varchar(50) NOT NULL,
  Habilitado bit NOT NULL,
  Externo bit NULL,
  CONSTRAINT PK_Perfil PRIMARY KEY CLUSTERED (Id)
)
ON [PRIMARY]
GO

SET DATEFORMAT ymd
SET ARITHABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS, XACT_ABORT OFF
GO

SET IDENTITY_INSERT FastConsig.dbo.Perfil ON
GO
INSERT FastConsig.dbo.Perfil(Id, Nome, Habilitado, Externo) VALUES (1, 'Administrador', CONVERT(bit, 'True'), CONVERT(bit, 'False'))
GO
SET IDENTITY_INSERT FastConsig.dbo.Perfil OFF
GO