CREATE TABLE FastConsig.dbo.TipoFormalizacao (
  Id int IDENTITY,
  Descricao varchar(50) NULL,
  CONSTRAINT PK_TipoFormalizacao_Id PRIMARY KEY CLUSTERED (Id)
)
ON [PRIMARY]
GO

SET DATEFORMAT ymd
SET ARITHABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS, XACT_ABORT OFF
GO

SET IDENTITY_INSERT FastConsig.dbo.TipoFormalizacao ON
GO
INSERT FastConsig.dbo.TipoFormalizacao(Id, Descricao) VALUES (1, 'Digital')
INSERT FastConsig.dbo.TipoFormalizacao(Id, Descricao) VALUES (2, 'Fisica')
GO
SET IDENTITY_INSERT FastConsig.dbo.TipoFormalizacao OFF
GO