CREATE TABLE FastConsig.dbo.TipoCompromisso (
  Id int IDENTITY,
  Descricao varchar(50) NOT NULL,
  Visivel bit NULL,
  CONSTRAINT PK_TipoCompromisso_Id PRIMARY KEY CLUSTERED (Id)
)
ON [PRIMARY]
GO

SET DATEFORMAT ymd
SET ARITHABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS, XACT_ABORT OFF
GO

SET IDENTITY_INSERT FastConsig.dbo.TipoCompromisso ON
GO
INSERT FastConsig.dbo.TipoCompromisso(Id, Descricao, Visivel) VALUES (1, 'Cliente', CONVERT(bit, 'True'))
GO
SET IDENTITY_INSERT FastConsig.dbo.TipoCompromisso OFF
GO