CREATE TABLE FastConsig.dbo.TipoPolitica (
  Id int IDENTITY,
  Descricao varchar(50) NOT NULL,
  CONSTRAINT PK_TipoPolitica_Id PRIMARY KEY CLUSTERED (Id)
)
ON [PRIMARY]
GO

SET DATEFORMAT ymd
SET ARITHABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS, XACT_ABORT OFF
GO

SET IDENTITY_INSERT FastConsig.dbo.TipoPolitica ON
GO
INSERT FastConsig.dbo.TipoPolitica(Id, Descricao) VALUES (1, 'Politica')
INSERT FastConsig.dbo.TipoPolitica(Id, Descricao) VALUES (2, 'Consulta')
GO
SET IDENTITY_INSERT FastConsig.dbo.TipoPolitica OFF
GO