CREATE TABLE FastConsig.dbo.TipoPessoa (
  Id int IDENTITY,
  Codigo char(1) NOT NULL,
  Descricao varchar(50) NOT NULL,
  CONSTRAINT PK_TipoPessoa_Id PRIMARY KEY CLUSTERED (Id)
)
ON [PRIMARY]
GO

SET DATEFORMAT ymd
SET ARITHABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS, XACT_ABORT OFF
GO

SET IDENTITY_INSERT FastConsig.dbo.TipoPessoa ON
GO
INSERT FastConsig.dbo.TipoPessoa(Id, Codigo, Descricao) VALUES (1, 'F', 'Pessoa Fisica')
INSERT FastConsig.dbo.TipoPessoa(Id, Codigo, Descricao) VALUES (2, 'J', 'Pessoa Juridica')
GO
SET IDENTITY_INSERT FastConsig.dbo.TipoPessoa OFF
GO	