CREATE TABLE FastConsig.dbo.OcorrenciasINSS (
  Id int IDENTITY,
  Codigo varchar(5) NULL,
  Descricao varchar(255) NOT NULL,
  Acao int NOT NULL,
  Ocorrencia int NULL,
  CONSTRAINT PK_OcorrenciasINSS PRIMARY KEY CLUSTERED (Id)
)
ON [PRIMARY]
GO

ALTER TABLE FastConsig.dbo.OcorrenciasINSS
  ADD CONSTRAINT OcorrenciasINSS_FK FOREIGN KEY (Ocorrencia) REFERENCES dbo.Ocorrencias (Id)
GO

ALTER TABLE FastConsig.dbo.OcorrenciasINSS
  ADD CONSTRAINT FK_OcorrenciasINSS_Acao FOREIGN KEY (Acao) REFERENCES dbo.OcorrenciasConsignadoAcao (Id)
GO

SET DATEFORMAT ymd
SET ARITHABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS, XACT_ABORT OFF
GO

SET IDENTITY_INSERT FastConsig.dbo.OcorrenciasINSS ON
GO
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (1, 'AD', 'O documento de identificação enviado não corresponde a um arquivo PDF/A válido', 4, 1)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (2, 'AM', 'Agência da Conta Corrente do segurado divergente', 4, 1)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (3, 'AN', 'Conta Corrente/DV do Favorecido Inválido.', 4, 1)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (4, 'AO', 'Nome invalido o nome esta em branco', 4, 1)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (5, 'AP', 'Data de inicio/fim do contrato invalida', 4, 1)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (6, 'AR', 'A assinatura a rogo é invalida ou não foi informada', 4, 1)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (7, 'AS', 'O(s) benefício(s) relacionado(s) ao CPF do titular não possui(em) representante legal', 2, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (8, 'AT', 'O termo de autorização enviado não corresponde a um arquivo PDF/A válido', 4, 1)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (9, 'AV', 'Não é possível realizar a operação até que seja concluído o processamento da folha de pagamento do INSS', 3, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (10, 'AX', 'O empréstimo tem uma alteração em aberto', 2, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (11, 'AY', 'Sigla do Estado do Favorecido Inválida', 4, 1)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (12, 'AZ', 'Os valores informados para os campos numeroParcelas e valorParcela são iguais aos valores atuais do empréstimo', 2, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (13, 'BC', 'Requicisão sem CBC', 4, 1)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (14, 'BD', 'Inclusão efetuada com sucesso', 1, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (15, 'BF', 'Exclusão (ou baixa) efetuada com sucesso', 2, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (16, 'BI', 'Benefício inexistente', 2, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (17, 'BJ', 'O benefício já estava desbloqueado', 4, 1)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (18, 'BL', 'Valor da parcela inválido', 4, 1)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (19, 'BM', 'Numero de contrato invalido', 4, 1)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (20, 'BN', 'Desbloqueio indeferido', 2, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (21, 'BR', 'Reativação efetuada com sucesso', 4, 1)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (22, 'BS', 'Suspensão efetuada com sucesso', 4, 1)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (23, 'CA', 'Código do banco inválido', 4, 1)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (24, 'CD', 'CPF não encontrado na base ou CPF de benefício inelegível', 2, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (25, 'CE', 'O CPF do representante legal da requisição e o CPF da requisição são diferentes', 2, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (26, 'CH', 'Requisição sem chave identificadora do termo', 3, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (27, 'CI', 'Canal de atendimento inválido', 4, 1)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (28, 'CJ', 'O CPF ou o CNPJ do Correspondente estão invalidos', 4, 1)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (29, 'CR', 'A requisição está sem o número do CPF do representante legal', 2, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (30, 'CT', 'O valor da CET (custo efetivo total) é invalido', 4, 1)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (31, 'CV', 'Periodo invalido', 3, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (32, 'CX', 'O classificador da situação de portabilidade é inválido', 2, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (33, 'CY', 'A instituição Financeira origem não existe', 2, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (34, 'D3', 'Dados do benefício estão incompletos, inconsistentes ou nulos: Valor Margem Disponível na Próxima Competência. Entrar em contato com a DATAPREV', 2, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (35, 'D4', 'Dados do benefício estão incompletos, inconsistentes ou nulos: Valor Margem Disponível Cartão. Entrar em contato com a DATAPREV', 2, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (36, 'D5', 'Dados do benefício estão incompletos, inconsistentes ou nulos: Agência Bancária. Entrar em contato com a DATAPREV', 2, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (37, 'D6', 'Dados do benefício estão incompletos, inconsistentes ou nulos: Conta Corrente. Entrar em contato com a DATAPREV', 2, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (38, 'D7', 'Dados do benefício estão incompletos, inconsistentes ou nulos: Valor Mensalidade Reajustada. Entrar em contato com a DATAPREV', 2, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (39, 'DA', 'A data e hora da autorização digital do beneficiário é uma data inválida. Utilize o formato DdMMyyyyhh24mmss ', 4, 1)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (40, 'DH', 'A data hora de criação do termo é uma data inválida ou uma data futura', 4, 1)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (41, 'DI', 'Tipo de documento inválido', 4, 1)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (42, 'DJ', 'A quantidade de solicitações na inclusão de desconto de cartão ou na exclusão de desconto de cartão está inválida!', 2, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (43, 'DK', 'Não é possível mais de um contrato de desconto cartão para um mesmo beneficio', 2, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (44, 'DR', 'Não foi encontrado na base o CPF com o CPF do representante legal cuja data fim do representante legal é maior ou igual à data atual', 2, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (45, 'EP', 'Erro no processamento', 3, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (46, 'EX', 'Token de autorização expirado', 3, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (47, 'FH', 'Operação fora do horário permitido', 3, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (48, 'GA', 'Na consulta de portabilidade
•O(s) campo(s) obrigatório(s) não foram informados
•Nas demais operações:
•O(s) campo(s) obrigatório(s) não informados:', 2, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (49, 'GE', 'Na Consulta de Portabilidade, na Consulta Extrato do Benefício, na Consulta empréstimos suspensos
	•Não foram localizados registros
	Nas demais operações
	•<campo1, campo2, campo 3> não existe(m)', 4, 1)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (50, 'GS', 'Não existe registro de portabilidade com o número único informado', 2, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (51, 'H3', 'É possível que tenha ocorrido uma mudança emergencial de sistema, por motivo legal ou outro, ou mesma alguma falha de sistema. Entrar em contato com a DATAPREV.', 3, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (52, 'HM', 'Mutuário não identificado', 2, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (53, 'HN', 'Tipo de benefício não permite empréstimo', 2, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (54, 'HP', 'Benefício recebido por procurador', 2, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (55, 'HQ', 'Benefício é do tipo PA', 2, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (56, 'HR', 'Quantidade de contratos permitida excedida', 2, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (57, 'HS', 'Benefício não pertence ao banco', 2, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (58, 'HV', 'Quantidade de parcelas inválida', 2, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (59, 'HW', 'Margem consignável excedida.', 2, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (60, 'HX', 'Empréstimo já cadastrado', 4, 1)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (61, 'HY', 'Empréstimo inexistente', 2, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (62, 'HZ', 'Não é possível fazer a operação com o empréstimo nesta situação', 4, 1)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (63, 'IA', 'Nome divergente', 2, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (64, 'IB', 'Benefício suspenso/cessado pela APS ou pelo Sisob', 2, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (65, 'IE', 'Benefício bloqueado para empréstimo pelo beneficiário', 2, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (66, 'IF', 'Beneficio bloqueado na concessão', 2, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (67, 'IN', 'Serviço/Sistema Indisponível.', 3, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (68, 'IO', 'O valor do IOF é Inválido', 3, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (69, 'IQ', 'Contrato já suspenso pelo Banco', 4, 1)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (70, 'IR', 'Prazo da operação é maior que a data de extinção de cota do benefício', 2, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (71, 'IV', 'Token de autorização de consulta inválido', 3, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (72, 'LE', 'Limite de registros retornados excedido ', 3, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (73, 'ME', 'O motivo de exclusão do empréstimo é inválido', 3, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (74, 'MN', 'É obrigatorio o preenchimento de todos os campos do termo de autorização', 4, 1)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (75, 'NB', 'Requisição sem número do benefício', 4, 1)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (76, 'NC', 'A requisição está sem número de contrato.', 4, 1)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (77, 'OA', 'O valor do saldo limite do cartão está inválido', 2, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (78, 'OB', 'O valor utilizado no mês pelo cartão está inválido', 2, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (79, 'OC', 'O percentual está inválido', 2, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (80, 'OD', 'O valor Limite de cartão está inválido', 2, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (81, 'OE', 'O valor do desconto está inválido', 2, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (82, 'OF', 'O CBC da IF pagadora está inválido', 4, 1)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (83, 'OG', 'Benefício sendo atualizado por outra operação', 3, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (84, 'OH', 'O número do contrato está inválido (caracteres não permitidos e/ou com espaço à direita)', 2, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (85, 'OI', 'É obrigatório o envio das informações da autorização digital ou das informações da autorização através do envio de PDF/A
OT	O tamanho do(s) campo(s) está incorreto: <campo 1>, <campo 2>', 4, 1)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (86, 'OJ', 'A requisição não está de acordo com o contrato da API', 2, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (87, 'OK', 'Campo(s) não codificado(s) em Base64: <documento e/ou termo>', 3, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (88, 'OL', 'A lista enviada na solicitação está inválida', 2, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (89, 'OM', 'O benefício não possui o valor da margem cadastrado', 3, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (90, 'ON', 'Operação não permitida', 2, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (91, 'OP', 'Instituição financeira penalizada para esta operação', 3, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (92, 'OS', 'O CPF não corresponde ao CPF do representante legal ativo', 2, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (93, 'OT', 'Tamanho dos campos incorretos', 4, 1)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (94, 'OU', 'O valor da taxa anual está inválido', 3, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (95, 'OV', 'O valor do custo efetivo anual está inválido', 3, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (96, 'OX', 'A data Limite das Operações não está cadastrada', 3, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (97, 'OZ', 'O serviço esta suspenso. Temino processamento de folha', 3, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (98, 'P1', 'Dados de parâmetros internos não cadastrados corretamente: Competência Atual. Entrar em contato com a DATAPREV', 3, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (99, 'P2', 'Dados de parâmetros internos não cadastrados corretamente: Última Competência Fechada. Entrar em contato com a DATAPREV', 3, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (100, 'P4', 'Dados de parâmetros internos não cadastrados corretamente: Data Limite da Operação. Entrar em contato com a DATAPREV', 3, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (101, 'P5', 'Dados de parâmetros internos não cadastrados corretamente: Data Limite de Averbação. Entrar em contato com a DATAPREV', 3, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (102, 'P6', 'Dados de parâmetros internos não cadastrados corretamente: Carência. Entrar em contato com a DATAPREV', 3, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (103, 'PA', 'O código do proponente está inválido', 2, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (104, 'PB', 'O NU foi encontrado na base para um CBC proponente diferente', 2, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (105, 'PC', 'A última parcela paga ao banco origem está inválida', 2, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (106, 'PD', 'A requisição está com o número do CPF do representante legal, e este benefício não possui um representante legal ativo', 2, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (107, 'PE', 'O NU foi encontrado na base para um benefício diferente', 2, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (108, 'PF', 'O CPF da requisição não correspondente ao CPF do benefício', 2, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (109, 'PG', 'Código do NU inválido', 2, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (110, 'PH', 'O NU foi encontrado na base para uma portabilidade, mas para um NB diferente', 2, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (111, 'PI', 'O valor do empréstimo está inválido', 2, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (112, 'PJ', 'O valor pago está inválido', 2, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (113, 'PK', 'O NU foi encontrado na base para uma portabilidade, mas para um CBC proponente diferente', 2, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (114, 'PL', 'O empréstimo está em processo de refinanciamento', 2, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (115, 'PQ', 'A lista de contratos excluídos está inválida', 2, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (116, 'PS', 'A instituição Financeira proponente não possui convênio para realizar a operação de averbação por portabilidade', 3, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (117, 'PU', 'O NU foi encontrado na base para uma portabilidade com mesmo NB e IF proponente, mas para um contrato diferente', 2, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (118, 'PX', 'O NU foi encontrado na base para uma portabilidade com mesmo NB, IF proponente e contrato', 2, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (119, 'PZ', 'O documento enviado não corresponde a um arquivo PDF/A válido', 4, 1)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (120, 'RA', 'A lista de contratos quitados está inválida', 2, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (121, 'RB', 'O valor do troco está inválido', 2, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (122, 'RD', 'Requisiçao sem o termo digitalizado de autorização do beneficiario', 4, 1)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (123, 'RG', 'O código do motivo da reversão do refinanciamento está inválido', 4, 1)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (124, 'RI', 'Não foi encontrado na base o CPF com o CPF do representante legal', 2, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (125, 'RL', 'A requisição está sem o número do CPF do representante legal, e este benefício possui um representante legal ativo', 2, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (126, 'RM', 'O contrato informado não foi um contrato criado em um refinanciamento', 2, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (127, 'RN', 'A requisição esta com o numero do CPF do representante legal, e este beneficio não possui representante legal ativo', 2, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (128, 'RR', 'Desbloqueio indeferido', 2, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (129, 'SF', 'A requisição está sem o CPF ou o CPF informado está com o DV inválido', 2, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (130, 'TN', 'Requisição sem as informações de identificação de autorização digital', 4, 1)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (131, 'VT', 'O valor da taxa anual esta invalido', 3, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (132, 'AB', 'Tipo de Operação Inválido', 4, 1)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (133, 'BP', '<Alteração de NU ou Alteração de CBC> realizada com sucesso', 4, 1)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (134, 'D9', 'Dados do benefício estão incompletos, inconsistentes ou nulos: Sigla da UF. Entrar em contato com a DATAPREV', 4, 1)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (135, 'GT', 'O NU foi encontrado na base para uma portabilidade, mas para uma IF origem diferente', 4, 1)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (136, 'GU', 'O NU foi encontrado na base para uma portabilidade e a IF proponente é igual a IF sendo informada', 4, 1)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (137, 'GV', 'O NU foi encontrado na base para uma portabilidade, mas já foi realizada a averbação por portabilidade', 4, 1)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (138, 'GX', 'O NU novo já encontrado na base', 4, 1)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (139, 'HT', 'Início do desconto informado já ultrapassado', 4, 1)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (140, 'IT', 'Beneficio bloqueado por TBM', 2, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (141, 'P7', 'Dados de parâmetros internos não cadastrados corretamente: Data de Implantação Margem. Entrar em contato com a DATAPREV', 4, 1)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (142, 'TC', 'Tipo desconto do cartão inválido', 2, NULL)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (143, 'RH', 'O período de reversão do refinanciamento já foi encerrado para o contrato', 4, 1)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (144, 'TV', 'O valor do IOF é Inválido	', 4, 1)
INSERT FastConsig.dbo.OcorrenciasINSS(Id, Codigo, Descricao, Acao, Ocorrencia) VALUES (145, 'TP', 'A data do primeiro desconto está inválida	', 4, 1)
GO
SET IDENTITY_INSERT FastConsig.dbo.OcorrenciasINSS OFF
GO