//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastConsig.Core.Web.Credito.INSS
{


   public partial class CapturaINSS
   {

      /// <summary>
      /// btnVoltar control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomLinkButton btnVoltar;

      /// <summary>
      /// btnSalvar control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomLinkButton btnSalvar;

      /// <summary>
      /// btnRejeitarProposta control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomLinkButton btnRejeitarProposta;

      /// <summary>
      /// btnPendenciar control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomLinkButton btnPendenciar;

      /// <summary>
      /// btnSubmeter control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomLinkButton btnSubmeter;

      /// <summary>
      /// btnReenviarMensagem control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomLinkButton btnReenviarMensagem;

      /// <summary>
      /// btnReenviarLinkCombateaFraude control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomLinkButton btnReenviarLinkCombateaFraude;

      /// <summary>
      /// btnReenviarLinkAssinatura control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomLinkButton btnReenviarLinkAssinatura;

      /// <summary>
      /// btnDesbloquearProposta control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomLinkButton btnDesbloquearProposta;

      /// <summary>
      /// tabPropostasTab control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.HtmlControls.HtmlAnchor tabPropostasTab;

      /// <summary>
      /// tabConsultasTab control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.HtmlControls.HtmlAnchor tabConsultasTab;

      /// <summary>
      /// tabOcorrenciasTab control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.HtmlControls.HtmlAnchor tabOcorrenciasTab;

      /// <summary>
      /// tabChecklistTab control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.HtmlControls.HtmlAnchor tabChecklistTab;

      /// <summary>
      /// tabTrilhaAuditoriaTab control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.HtmlControls.HtmlAnchor tabTrilhaAuditoriaTab;

      /// <summary>
      /// tabHistoricoTab control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.HtmlControls.HtmlAnchor tabHistoricoTab;

      /// <summary>
      /// tabLogsTab control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.HtmlControls.HtmlAnchor tabLogsTab;

      /// <summary>
      /// tabArquivosTab control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.HtmlControls.HtmlAnchor tabArquivosTab;

      /// <summary>
      /// txtProposta control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomTextBox txtProposta;

      /// <summary>
      /// ddlPromotora control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomDropDownList ddlPromotora;

      /// <summary>
      /// ddlGerente control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomDropDownList ddlGerente;

      /// <summary>
      /// ddlRedeLojas control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomDropDownList ddlRedeLojas;

      /// <summary>
      /// ddlLojas control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomDropDownList ddlLojas;

      /// <summary>
      /// ddlProduto control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomDropDownList ddlProduto;

      /// <summary>
      /// ddlTipoComunicacao control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomDropDownList ddlTipoComunicacao;

      /// <summary>
      /// txtProfissionalCertificado control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomTextBox txtProfissionalCertificado;

      /// <summary>
      /// txtDigitador control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomTextBox txtDigitador;

      /// <summary>
      /// txtCPF control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomTextBox txtCPF;

      /// <summary>
      /// txtNome control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomTextBox txtNome;

      /// <summary>
      /// txtDataNascimento control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomTextBox txtDataNascimento;

      /// <summary>
      /// ddlNacionalidade control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomDropDownList ddlNacionalidade;

      /// <summary>
      /// txtNaturalidade control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomTextBox txtNaturalidade;

      /// <summary>
      /// ddlSexo control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomDropDownList ddlSexo;

      /// <summary>
      /// ddlEstadoCivil control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomDropDownList ddlEstadoCivil;

      /// <summary>
      /// ddlTipoDocumento control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomDropDownList ddlTipoDocumento;

      /// <summary>
      /// txtNumeroDocumentoIdentidade control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomTextBox txtNumeroDocumentoIdentidade;

      /// <summary>
      /// ddlEmissorDocumento control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomDropDownList ddlEmissorDocumento;

      /// <summary>
      /// ddlUFEmissaoDocumentoIdentidade control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomDropDownList ddlUFEmissaoDocumentoIdentidade;

      /// <summary>
      /// txtDataEmissaoDocumentoIdentidade control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomTextBox txtDataEmissaoDocumentoIdentidade;

      /// <summary>
      /// txtMae control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomTextBox txtMae;

      /// <summary>
      /// txtPai control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomTextBox txtPai;

      /// <summary>
      /// txtCelular control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomTextBox txtCelular;

      /// <summary>
      /// txtEmail control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomTextBox txtEmail;

      /// <summary>
      /// ddlPPE control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomDropDownList ddlPPE;

      /// <summary>
      /// txtCEPResidencial control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomTextBox txtCEPResidencial;

      /// <summary>
      /// txtEnderecoResidencial control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomTextBox txtEnderecoResidencial;

      /// <summary>
      /// txtNumeroResidencial control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomTextBox txtNumeroResidencial;

      /// <summary>
      /// txtComplementoResidencial control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomTextBox txtComplementoResidencial;

      /// <summary>
      /// txtBairroResidencial control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomTextBox txtBairroResidencial;

      /// <summary>
      /// txtCidadeResidencial control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomTextBox txtCidadeResidencial;

      /// <summary>
      /// txtEstadoResidencial control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomTextBox txtEstadoResidencial;

      /// <summary>
      /// txtTelefoneResidencial control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomTextBox txtTelefoneResidencial;

      /// <summary>
      /// txtEmpresa control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomTextBox txtEmpresa;

      /// <summary>
      /// txtCargo control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomTextBox txtCargo;

      /// <summary>
      /// ddlOcupacao control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomDropDownList ddlOcupacao;

      /// <summary>
      /// ddlIndicadorAnalfabetismo control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomDropDownList ddlIndicadorAnalfabetismo;

      /// <summary>
      /// ddlEspecieBeneficio control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomDropDownList ddlEspecieBeneficio;

      /// <summary>
      /// txtNumeroBeneficio control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomTextBox txtNumeroBeneficio;

      /// <summary>
      /// txtBancoBeneficio control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomTextBox txtBancoBeneficio;

      /// <summary>
      /// txtAgenciaBeneficio control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomTextBox txtAgenciaBeneficio;

      /// <summary>
      /// txtContaBeneficio control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomTextBox txtContaBeneficio;

      /// <summary>
      /// txtRendimentos control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomTextBox txtRendimentos;

      /// <summary>
      /// txtOutrosRendimentos control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomTextBox txtOutrosRendimentos;

      /// <summary>
      /// divContratosRefin control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.HtmlControls.HtmlGenericControl divContratosRefin;

      /// <summary>
      /// ContratosRepeater control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.WebControls.Repeater ContratosRepeater;

      /// <summary>
      /// lblDataLiberacaoPopUpSimulacaoOperacao control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomLabel lblDataLiberacaoPopUpSimulacaoOperacao;

      /// <summary>
      /// lblDataPrimeiroVencimentoPopUpSimulacaoOperacao control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomLabel lblDataPrimeiroVencimentoPopUpSimulacaoOperacao;

      /// <summary>
      /// lblValorFinanciadoTotalPopUpSimulacaoOperacao control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomLabel lblValorFinanciadoTotalPopUpSimulacaoOperacao;

      /// <summary>
      /// lblValorEntradaPopUpSimulacaoOperacao control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomLabel lblValorEntradaPopUpSimulacaoOperacao;

      /// <summary>
      /// lblValorLiberadoPopUpSimulacaoOperacao control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomLabel lblValorLiberadoPopUpSimulacaoOperacao;

      /// <summary>
      /// lblQtdParcelas control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomLabel lblQtdParcelas;

      /// <summary>
      /// lblValorParcela control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomLabel lblValorParcela;

      /// <summary>
      /// lblValorSeguroPopUpSimulacaoOperacao control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomLabel lblValorSeguroPopUpSimulacaoOperacao;

      /// <summary>
      /// label2 control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.HtmlControls.HtmlGenericControl label2;

      /// <summary>
      /// txtValorTAC control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomLabel txtValorTAC;

      /// <summary>
      /// txtValorTF control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomLabel txtValorTF;

      /// <summary>
      /// txtValorPST control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomLabel txtValorPST;

      /// <summary>
      /// lblValorIOF control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomLabel lblValorIOF;

      /// <summary>
      /// txtTaxaMes control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomLabel txtTaxaMes;

      /// <summary>
      /// txtTaxaAno control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomLabel txtTaxaAno;

      /// <summary>
      /// lblCETMes control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomLabel lblCETMes;

      /// <summary>
      /// lblCETAno control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomLabel lblCETAno;

      /// <summary>
      /// ddlMeioLiberacao control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomDropDownList ddlMeioLiberacao;

      /// <summary>
      /// divBancoLiberacao control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.HtmlControls.HtmlGenericControl divBancoLiberacao;

      /// <summary>
      /// lblBancoLiberacao control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblBancoLiberacao;

      /// <summary>
      /// txtBancoLiberacao control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomTextBox txtBancoLiberacao;

      /// <summary>
      /// divAgenciaLiberacao control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.HtmlControls.HtmlGenericControl divAgenciaLiberacao;

      /// <summary>
      /// lblAgenciaLiberacao control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblAgenciaLiberacao;

      /// <summary>
      /// txtAgenciaLiberacao control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomTextBox txtAgenciaLiberacao;

      /// <summary>
      /// divContaLiberacao control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.HtmlControls.HtmlGenericControl divContaLiberacao;

      /// <summary>
      /// lblContaLiberacao control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblContaLiberacao;

      /// <summary>
      /// txtContaLiberacao control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomTextBox txtContaLiberacao;

      /// <summary>
      /// divChavePIX control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.HtmlControls.HtmlGenericControl divChavePIX;

      /// <summary>
      /// lblChavePIX control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblChavePIX;

      /// <summary>
      /// txtChavePIX control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomTextBox txtChavePIX;

      /// <summary>
      /// treeConsultas control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.WebControls.TreeView treeConsultas;

      /// <summary>
      /// btnAdicionarOcorrencia control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomLinkButton btnAdicionarOcorrencia;

      /// <summary>
      /// rptOcorrencias control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.WebControls.Repeater rptOcorrencias;

      /// <summary>
      /// rptOcorrenciasCheckList control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.WebControls.Repeater rptOcorrenciasCheckList;

      /// <summary>
      /// rptTrilhaAuditoria control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.WebControls.Repeater rptTrilhaAuditoria;

      /// <summary>
      /// ConteudoHistoricoAlteracoes control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.HtmlControls.HtmlGenericControl ConteudoHistoricoAlteracoes;

      /// <summary>
      /// rptLog control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.WebControls.Repeater rptLog;

      /// <summary>
      /// rptArquivos control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.WebControls.Repeater rptArquivos;

      /// <summary>
      /// divCarregarArquivos control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.HtmlControls.HtmlGenericControl divCarregarArquivos;

      /// <summary>
      /// UpdatePanel1 control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.UpdatePanel UpdatePanel1;

      /// <summary>
      /// fileUpload control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.WebControls.FileUpload fileUpload;

      /// <summary>
      /// HdntipoArquivo control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.WebControls.HiddenField HdntipoArquivo;

      /// <summary>
      /// ddlTipoDocumentoUpload control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomDropDownList ddlTipoDocumentoUpload;

      /// <summary>
      /// btnCarregarArquivo control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomLinkButton btnCarregarArquivo;

      /// <summary>
      /// HiddenTab control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.WebControls.HiddenField HiddenTab;

      /// <summary>
      /// pnlPopupJustificativaAprovacao control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.WebControls.Panel pnlPopupJustificativaAprovacao;

      /// <summary>
      /// CustomTextBox7 control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomTextBox CustomTextBox7;

      /// <summary>
      /// btnJustificativaAprovacaoOk control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.WebControls.Button btnJustificativaAprovacaoOk;

      /// <summary>
      /// btnJustificativaAprovacaoCancelar control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.WebControls.Button btnJustificativaAprovacaoCancelar;

      /// <summary>
      /// pnlPopupOcorrencia control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.WebControls.Panel pnlPopupOcorrencia;

      /// <summary>
      /// txtOcorrencia control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomTextBox txtOcorrencia;

      /// <summary>
      /// txtDataHoraOcorrencia control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomTextBox txtDataHoraOcorrencia;

      /// <summary>
      /// txtOcorrenciaRestritiva control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomTextBox txtOcorrenciaRestritiva;

      /// <summary>
      /// txtComplementoOcorrencia control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomTextBox txtComplementoOcorrencia;

      /// <summary>
      /// txtOcorrenciaLiberada control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomTextBox txtOcorrenciaLiberada;

      /// <summary>
      /// txtOcorrenciaDataLiberacao control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomTextBox txtOcorrenciaDataLiberacao;

      /// <summary>
      /// txtOcorrenciaUsuarioLiberador control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomTextBox txtOcorrenciaUsuarioLiberador;

      /// <summary>
      /// txtJustificativaOcorrencia control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomTextBox txtJustificativaOcorrencia;

      /// <summary>
      /// btnSairOcorrencia control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.WebControls.Button btnSairOcorrencia;

      /// <summary>
      /// btnJustificativaAprovacaoOcorrenciaOk control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.WebControls.Button btnJustificativaAprovacaoOcorrenciaOk;

      /// <summary>
      /// btnCancelarOcorrencia control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.WebControls.Button btnCancelarOcorrencia;

      /// <summary>
      /// pnlPopupJustificativaRecusa control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.WebControls.Panel pnlPopupJustificativaRecusa;

      /// <summary>
      /// ddlOcorrenciaRecusa control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomDropDownList ddlOcorrenciaRecusa;

      /// <summary>
      /// CustomTextBox6 control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomTextBox CustomTextBox6;

      /// <summary>
      /// btnJustificativaRecusaOk control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.WebControls.Button btnJustificativaRecusaOk;

      /// <summary>
      /// btnJustificativaCancelar control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.WebControls.Button btnJustificativaCancelar;

      /// <summary>
      /// pnlPopupPendenciarProposta control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.WebControls.Panel pnlPopupPendenciarProposta;

      /// <summary>
      /// ddlOcorrenciaPendencia control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomDropDownList ddlOcorrenciaPendencia;

      /// <summary>
      /// txtObservacoesPendencia control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomTextBox txtObservacoesPendencia;

      /// <summary>
      /// btnPendenciarOk control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.WebControls.Button btnPendenciarOk;

      /// <summary>
      /// btnPendenciarPropostaCancelar control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.WebControls.Button btnPendenciarPropostaCancelar;

      /// <summary>
      /// pnlPopupAdicionarOcorrencia control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.WebControls.Panel pnlPopupAdicionarOcorrencia;

      /// <summary>
      /// ddlOcorrenciaProposta control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomDropDownList ddlOcorrenciaProposta;

      /// <summary>
      /// CustomTextBox1 control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomTextBox CustomTextBox1;

      /// <summary>
      /// bntAdicionarOcorrenciaOK control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.WebControls.Button bntAdicionarOcorrenciaOK;

      /// <summary>
      /// btnAdicionarOcorrenciaCancel control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::System.Web.UI.WebControls.Button btnAdicionarOcorrenciaCancel;
   }
}
