//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastConsig.Core.Web.Seguranca
{


   public partial class AlterarSenha
   {

      /// <summary>
      /// txtSenhaAtual control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomTextBox txtSenhaAtual;

      /// <summary>
      /// txtNovaSenha control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomTextBox txtNovaSenha;

      /// <summary>
      /// txtConfirmacaoSenha control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomTextBox txtConfirmacaoSenha;

      /// <summary>
      /// cmdAlterarSenha control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomButton cmdAlterarSenha;
   }
}
