//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastConsig.Core.Web.Configuracoes
{


   public partial class EditarPromotora
   {

      /// <summary>
      /// btnSalvar control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomLinkButton btnSalvar;

      /// <summary>
      /// btnExcluir control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomLinkButton btnExcluir;

      /// <summary>
      /// btnVoltar control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomLinkButton btnVoltar;

      /// <summary>
      /// txtCodigo control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomTextBox txtCodigo;

      /// <summary>
      /// txtCnpj control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomTextBox txtCnpj;

      /// <summary>
      /// txtDescricao control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomTextBox txtDescricao;

      /// <summary>
      /// txtNomeFantasia control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomTextBox txtNomeFantasia;

      /// <summary>
      /// ddlGerente control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomDropDownList ddlGerente;

      /// <summary>
      /// txtCEP control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomTextBox txtCEP;

      /// <summary>
      /// txtEndereco control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomTextBox txtEndereco;

      /// <summary>
      /// txtNumero control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomTextBox txtNumero;

      /// <summary>
      /// txtComplemento control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomTextBox txtComplemento;

      /// <summary>
      /// txtBairro control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomTextBox txtBairro;

      /// <summary>
      /// txtCidade control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomTextBox txtCidade;

      /// <summary>
      /// txtEstado control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomTextBox txtEstado;

      /// <summary>
      /// txtTelefone control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomTextBox txtTelefone;

      /// <summary>
      /// txtEmail control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomTextBox txtEmail;

      /// <summary>
      /// chkAtivo control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomCheckBox chkAtivo;

      /// <summary>
      /// chkCorrespondente control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomCheckBox chkCorrespondente;
   }
}
