//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastConsig.Core.Web.Configuracoes
{


   public partial class EditarStatus
   {

      /// <summary>
      /// btnSalvar control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomLinkButton btnSalvar;

      /// <summary>
      /// btnExcluir control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomLinkButton btnExcluir;

      /// <summary>
      /// btnVoltar control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomLinkButton btnVoltar;

      /// <summary>
      /// txtCodigo control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomTextBox txtCodigo;

      /// <summary>
      /// txtDescricao control.
      /// </summary>
      /// <remarks>
      /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
      protected global::Framework.Web.UI.Controls.CustomTextBox txtDescricao;
   }
}
