//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace FastConsig.CTC.Model.ACTC855
{
   using FastConsig.CTC.Model.Interfaces;
   using System.Xml.Serialization;


   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC855ERR.xsd")]
   [System.Xml.Serialization.XmlRootAttribute("ACTCDOC", Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC855ERR.xsd", IsNullable = false)]
   public partial class ACTC855ERR : IACTC
   {

      private BCARQERRComplexType bCARQField;

      /// <remarks/>
      public BCARQERRComplexType BCARQ
      {
         get
         {
            return this.bCARQField;
         }
         set
         {
            this.bCARQField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC855ERR.xsd")]
   public partial class BCARQERRComplexType
   {

      private NomArqCodErr_ComplexType nomArqField;

      /// <remarks/>
      public NomArqCodErr_ComplexType NomArq
      {
         get
         {
            return this.nomArqField;
         }
         set
         {
            this.nomArqField = value;
         }
      }
   }

   /// <remarks/>
   [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
   [System.SerializableAttribute()]
   [System.Diagnostics.DebuggerStepThroughAttribute()]
   [System.ComponentModel.DesignerCategoryAttribute("code")]
   [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cip-bancos.org.br/ARQ/ACTC855ERR.xsd")]
   public partial class NomArqCodErr_ComplexType
   {

      private string codErroField;

      private string valueField;

      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string CodErro
      {
         get
         {
            return this.codErroField;
         }
         set
         {
            this.codErroField = value;
         }
      }

      /// <remarks/>
      [System.Xml.Serialization.XmlTextAttribute()]
      public string Value
      {
         get
         {
            return this.valueField;
         }
         set
         {
            this.valueField = value;
         }
      }
   }
}
