<?xml version="1.0" encoding="UTF-8"?>
<xs:schema id="ACTC702"
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:cat="http://www.cip-bancos.org.br/catalogomsg"
	targetNamespace="http://www.cip-bancos.org.br/ARQ/ACTC702.xsd"
	xmlns="http://www.cip-bancos.org.br/ARQ/ACTC702.xsd"
	elementFormDefault="qualified"
    version="1.11.0">

	<!-- Definição dos Tipos Globais -->
	<xs:include schemaLocation="ACTCTIPOS.xsd" />

	<!-- Definição do ACTCDOC -->
	<xs:complexType name="ACTCDOCComplexType">
		<xs:sequence>
			<xs:element name="BCARQ" type="BCARQComplexType" />
			<xs:element name="SISARQ" type="SISARQComplexType" />
			<xs:element name="ESTARQ" type="ESTARQSimpleType" minOccurs="0" />
		</xs:sequence>
	</xs:complexType>

	<!-- Definição do ACTCDOC -->
	<xs:element name="ACTCDOC" type="ACTCDOCComplexType">
		<xs:annotation>
			<xs:documentation>
			</xs:documentation>
		</xs:annotation>
	</xs:element>

	<!-- Definição do SISARQ -->
	<xs:complexType name="SISARQComplexType">
		<xs:choice>
			<xs:element name="ACTC702" type="ACTC702ComplexType">
				<xs:annotation>
					<xs:documentation>
						<cat:InfMensagem>
							<cat:Mensagem>
								CTC informa solicitação de troca de modalidade
							</cat:Mensagem>
							<cat:Emissor>CTC</cat:Emissor>
							<cat:Destinatario>IF Credora Original</cat:Destinatario>
						</cat:InfMensagem>
					</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:choice>
	</xs:complexType>

	<xs:complexType name="ACTC702ComplexType">
		<xs:sequence>
			<xs:element name="Grupo_ACTC702_Portldd" type="Grupo_ACTC702_PortlddComplexType" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>
						Grupo Portabilidade
					</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="Grupo_ACTC702_PortlddComplexType">
		<xs:sequence>
			<xs:element name="IdentdPartAdmdo" type="CNPJBase">
				<xs:annotation>
					<xs:documentation>
						Identificador do participante administrado
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="NUPortlddCTC" type="NU">
				<xs:annotation>
					<xs:documentation>
						<cat:InfCampo>
							<cat:DescricaoCampo>
								Número da portabilidade no CTC
							</cat:DescricaoCampo>
						</cat:InfCampo>
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="IdentdIFPropnt" type="CNPJBase">
				<xs:annotation>
					<xs:documentation>
						<cat:InfCampo>
							<cat:DescricaoCampo>
								Identificador do solicitante da transferência
							</cat:DescricaoCampo>
						</cat:InfCampo>
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="Grupo_ACTC702_IdentdContrto" type="Grupo_ACTC70X_IdentdContrtoComplexType">
				<xs:annotation>
					<xs:documentation>
						Grupo Identificador Contrato
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="Grupo_ACTC702_Cli" type="Grupo_ACTC_CliComplexType_CodErro" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>
						Grupo Cliente
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="DtRefCalcSaldDevdr" type="Data" minOccurs="0" maxOccurs="3">
				<xs:annotation>
					<xs:documentation>
						Data Referência para Cálculo Saldo Devedor Contábil
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="Grupo_ACTC702_PropPortldd" type="Grupo_ACTC702_PropPortlddComplexType">
				<xs:annotation>
					<xs:documentation>
						Grupo Proposta Portabilidade
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="Grupo_ACTC702_EndImovel" type="Grupo_EndImovl_ComplexType" minOccurs="0">
				<xs:annotation>
					<xs:documentation>
						Endereço Carta Portabilidade
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="EmailConttoPropnt" type="Email" minOccurs="0">
				<xs:annotation>
					<xs:documentation>
						Email Contato Proponente
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="TelConttoPropnt" type="Telefone" minOccurs="0">
				<xs:annotation>
					<xs:documentation>
						Telefone Contato Proponente
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="Grupo_ACTC702_EndCartaPortldd" type="Grupo_EndCartaPortldd_ComplexType">
				<xs:annotation>
					<xs:documentation>
						Endereço Carta Portabilidade
					</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:schema>